// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: container_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Repeated fields — all scalar types + message + enum
struct Testcompat_RepeatedAllTypes: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var repDouble: [Double] {
    get {return _storage._repDouble}
    set {_uniqueStorage()._repDouble = newValue}
  }

  var repFloat: [Float] {
    get {return _storage._repFloat}
    set {_uniqueStorage()._repFloat = newValue}
  }

  var repInt32: [Int32] {
    get {return _storage._repInt32}
    set {_uniqueStorage()._repInt32 = newValue}
  }

  var repInt64: [Int64] {
    get {return _storage._repInt64}
    set {_uniqueStorage()._repInt64 = newValue}
  }

  var repUint32: [UInt32] {
    get {return _storage._repUint32}
    set {_uniqueStorage()._repUint32 = newValue}
  }

  var repUint64: [UInt64] {
    get {return _storage._repUint64}
    set {_uniqueStorage()._repUint64 = newValue}
  }

  var repSint32: [Int32] {
    get {return _storage._repSint32}
    set {_uniqueStorage()._repSint32 = newValue}
  }

  var repSint64: [Int64] {
    get {return _storage._repSint64}
    set {_uniqueStorage()._repSint64 = newValue}
  }

  var repFixed32: [UInt32] {
    get {return _storage._repFixed32}
    set {_uniqueStorage()._repFixed32 = newValue}
  }

  var repFixed64: [UInt64] {
    get {return _storage._repFixed64}
    set {_uniqueStorage()._repFixed64 = newValue}
  }

  var repSfixed32: [Int32] {
    get {return _storage._repSfixed32}
    set {_uniqueStorage()._repSfixed32 = newValue}
  }

  var repSfixed64: [Int64] {
    get {return _storage._repSfixed64}
    set {_uniqueStorage()._repSfixed64 = newValue}
  }

  var repBool: [Bool] {
    get {return _storage._repBool}
    set {_uniqueStorage()._repBool = newValue}
  }

  var repString: [String] {
    get {return _storage._repString}
    set {_uniqueStorage()._repString = newValue}
  }

  var repBytes: [Data] {
    get {return _storage._repBytes}
    set {_uniqueStorage()._repBytes = newValue}
  }

  var repMsg: [Testcompat_ScalarMessage] {
    get {return _storage._repMsg}
    set {_uniqueStorage()._repMsg = newValue}
  }

  var repEnum: [Testcompat_Status] {
    get {return _storage._repEnum}
    set {_uniqueStorage()._repEnum = newValue}
  }

  var repSimple: [Testcompat_SimpleMessage] {
    get {return _storage._repSimple}
    set {_uniqueStorage()._repSimple = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Maps — all 7 key types (int32, int64, uint32, uint64, sint32, sint64, bool, string, fixed32, fixed64, sfixed32, sfixed64)
struct Testcompat_MapAllKeyTypes: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mapStringString: Dictionary<String,String> = [:]

  var mapInt32String: Dictionary<Int32,String> = [:]

  var mapInt64String: Dictionary<Int64,String> = [:]

  var mapUint32String: Dictionary<UInt32,String> = [:]

  var mapUint64String: Dictionary<UInt64,String> = [:]

  var mapSint32String: Dictionary<Int32,String> = [:]

  var mapSint64String: Dictionary<Int64,String> = [:]

  var mapFixed32String: Dictionary<UInt32,String> = [:]

  var mapFixed64String: Dictionary<UInt64,String> = [:]

  var mapSfixed32String: Dictionary<Int32,String> = [:]

  var mapSfixed64String: Dictionary<Int64,String> = [:]

  var mapBoolString: Dictionary<Bool,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Maps — diverse value types
struct Testcompat_MapAllValueTypes: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var mapSInt32: Dictionary<String,Int32> = [:]

  var mapSInt64: Dictionary<String,Int64> = [:]

  var mapSDouble: Dictionary<String,Double> = [:]

  var mapSFloat: Dictionary<String,Float> = [:]

  var mapSBool: Dictionary<String,Bool> = [:]

  var mapSBytes: Dictionary<String,Data> = [:]

  var mapSString: Dictionary<String,String> = [:]

  var mapSMsg: Dictionary<String,Testcompat_ScalarMessage> = [:]

  var mapSEnum: Dictionary<String,Testcompat_Status> = [:]

  var mapSSimple: Dictionary<String,Testcompat_SimpleMessage> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Mixed map + repeated in one message
struct Testcompat_MixedContainers: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ids: [Int32] = []

  var names: [String] = []

  var scores: Dictionary<String,Int32> = [:]

  var entries: Dictionary<Int64,Testcompat_SimpleMessage> = [:]

  var items: [Testcompat_SimpleMessage] = []

  var statuses: Dictionary<String,Testcompat_Status> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_RepeatedAllTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RepeatedAllTypes"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}rep_double\0\u{3}rep_float\0\u{3}rep_int32\0\u{3}rep_int64\0\u{3}rep_uint32\0\u{3}rep_uint64\0\u{3}rep_sint32\0\u{3}rep_sint64\0\u{3}rep_fixed32\0\u{3}rep_fixed64\0\u{3}rep_sfixed32\0\u{3}rep_sfixed64\0\u{3}rep_bool\0\u{3}rep_string\0\u{3}rep_bytes\0\u{3}rep_msg\0\u{3}rep_enum\0\u{3}rep_simple\0")

  fileprivate class _StorageClass {
    var _repDouble: [Double] = []
    var _repFloat: [Float] = []
    var _repInt32: [Int32] = []
    var _repInt64: [Int64] = []
    var _repUint32: [UInt32] = []
    var _repUint64: [UInt64] = []
    var _repSint32: [Int32] = []
    var _repSint64: [Int64] = []
    var _repFixed32: [UInt32] = []
    var _repFixed64: [UInt64] = []
    var _repSfixed32: [Int32] = []
    var _repSfixed64: [Int64] = []
    var _repBool: [Bool] = []
    var _repString: [String] = []
    var _repBytes: [Data] = []
    var _repMsg: [Testcompat_ScalarMessage] = []
    var _repEnum: [Testcompat_Status] = []
    var _repSimple: [Testcompat_SimpleMessage] = []

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _repDouble = source._repDouble
      _repFloat = source._repFloat
      _repInt32 = source._repInt32
      _repInt64 = source._repInt64
      _repUint32 = source._repUint32
      _repUint64 = source._repUint64
      _repSint32 = source._repSint32
      _repSint64 = source._repSint64
      _repFixed32 = source._repFixed32
      _repFixed64 = source._repFixed64
      _repSfixed32 = source._repSfixed32
      _repSfixed64 = source._repSfixed64
      _repBool = source._repBool
      _repString = source._repString
      _repBytes = source._repBytes
      _repMsg = source._repMsg
      _repEnum = source._repEnum
      _repSimple = source._repSimple
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeRepeatedDoubleField(value: &_storage._repDouble) }()
        case 2: try { try decoder.decodeRepeatedFloatField(value: &_storage._repFloat) }()
        case 3: try { try decoder.decodeRepeatedInt32Field(value: &_storage._repInt32) }()
        case 4: try { try decoder.decodeRepeatedInt64Field(value: &_storage._repInt64) }()
        case 5: try { try decoder.decodeRepeatedUInt32Field(value: &_storage._repUint32) }()
        case 6: try { try decoder.decodeRepeatedUInt64Field(value: &_storage._repUint64) }()
        case 7: try { try decoder.decodeRepeatedSInt32Field(value: &_storage._repSint32) }()
        case 8: try { try decoder.decodeRepeatedSInt64Field(value: &_storage._repSint64) }()
        case 9: try { try decoder.decodeRepeatedFixed32Field(value: &_storage._repFixed32) }()
        case 10: try { try decoder.decodeRepeatedFixed64Field(value: &_storage._repFixed64) }()
        case 11: try { try decoder.decodeRepeatedSFixed32Field(value: &_storage._repSfixed32) }()
        case 12: try { try decoder.decodeRepeatedSFixed64Field(value: &_storage._repSfixed64) }()
        case 13: try { try decoder.decodeRepeatedBoolField(value: &_storage._repBool) }()
        case 14: try { try decoder.decodeRepeatedStringField(value: &_storage._repString) }()
        case 15: try { try decoder.decodeRepeatedBytesField(value: &_storage._repBytes) }()
        case 16: try { try decoder.decodeRepeatedMessageField(value: &_storage._repMsg) }()
        case 17: try { try decoder.decodeRepeatedEnumField(value: &_storage._repEnum) }()
        case 18: try { try decoder.decodeRepeatedMessageField(value: &_storage._repSimple) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._repDouble.isEmpty {
        try visitor.visitPackedDoubleField(value: _storage._repDouble, fieldNumber: 1)
      }
      if !_storage._repFloat.isEmpty {
        try visitor.visitPackedFloatField(value: _storage._repFloat, fieldNumber: 2)
      }
      if !_storage._repInt32.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._repInt32, fieldNumber: 3)
      }
      if !_storage._repInt64.isEmpty {
        try visitor.visitPackedInt64Field(value: _storage._repInt64, fieldNumber: 4)
      }
      if !_storage._repUint32.isEmpty {
        try visitor.visitPackedUInt32Field(value: _storage._repUint32, fieldNumber: 5)
      }
      if !_storage._repUint64.isEmpty {
        try visitor.visitPackedUInt64Field(value: _storage._repUint64, fieldNumber: 6)
      }
      if !_storage._repSint32.isEmpty {
        try visitor.visitPackedSInt32Field(value: _storage._repSint32, fieldNumber: 7)
      }
      if !_storage._repSint64.isEmpty {
        try visitor.visitPackedSInt64Field(value: _storage._repSint64, fieldNumber: 8)
      }
      if !_storage._repFixed32.isEmpty {
        try visitor.visitPackedFixed32Field(value: _storage._repFixed32, fieldNumber: 9)
      }
      if !_storage._repFixed64.isEmpty {
        try visitor.visitPackedFixed64Field(value: _storage._repFixed64, fieldNumber: 10)
      }
      if !_storage._repSfixed32.isEmpty {
        try visitor.visitPackedSFixed32Field(value: _storage._repSfixed32, fieldNumber: 11)
      }
      if !_storage._repSfixed64.isEmpty {
        try visitor.visitPackedSFixed64Field(value: _storage._repSfixed64, fieldNumber: 12)
      }
      if !_storage._repBool.isEmpty {
        try visitor.visitPackedBoolField(value: _storage._repBool, fieldNumber: 13)
      }
      if !_storage._repString.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repString, fieldNumber: 14)
      }
      if !_storage._repBytes.isEmpty {
        try visitor.visitRepeatedBytesField(value: _storage._repBytes, fieldNumber: 15)
      }
      if !_storage._repMsg.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repMsg, fieldNumber: 16)
      }
      if !_storage._repEnum.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._repEnum, fieldNumber: 17)
      }
      if !_storage._repSimple.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repSimple, fieldNumber: 18)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_RepeatedAllTypes, rhs: Testcompat_RepeatedAllTypes) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._repDouble != rhs_storage._repDouble {return false}
        if _storage._repFloat != rhs_storage._repFloat {return false}
        if _storage._repInt32 != rhs_storage._repInt32 {return false}
        if _storage._repInt64 != rhs_storage._repInt64 {return false}
        if _storage._repUint32 != rhs_storage._repUint32 {return false}
        if _storage._repUint64 != rhs_storage._repUint64 {return false}
        if _storage._repSint32 != rhs_storage._repSint32 {return false}
        if _storage._repSint64 != rhs_storage._repSint64 {return false}
        if _storage._repFixed32 != rhs_storage._repFixed32 {return false}
        if _storage._repFixed64 != rhs_storage._repFixed64 {return false}
        if _storage._repSfixed32 != rhs_storage._repSfixed32 {return false}
        if _storage._repSfixed64 != rhs_storage._repSfixed64 {return false}
        if _storage._repBool != rhs_storage._repBool {return false}
        if _storage._repString != rhs_storage._repString {return false}
        if _storage._repBytes != rhs_storage._repBytes {return false}
        if _storage._repMsg != rhs_storage._repMsg {return false}
        if _storage._repEnum != rhs_storage._repEnum {return false}
        if _storage._repSimple != rhs_storage._repSimple {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MapAllKeyTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapAllKeyTypes"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}map_string_string\0\u{3}map_int32_string\0\u{3}map_int64_string\0\u{3}map_uint32_string\0\u{3}map_uint64_string\0\u{3}map_sint32_string\0\u{3}map_sint64_string\0\u{3}map_fixed32_string\0\u{3}map_fixed64_string\0\u{3}map_sfixed32_string\0\u{3}map_sfixed64_string\0\u{3}map_bool_string\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.mapStringString) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufString>.self, value: &self.mapInt32String) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt64,SwiftProtobuf.ProtobufString>.self, value: &self.mapInt64String) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt32,SwiftProtobuf.ProtobufString>.self, value: &self.mapUint32String) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufString>.self, value: &self.mapUint64String) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSInt32,SwiftProtobuf.ProtobufString>.self, value: &self.mapSint32String) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSInt64,SwiftProtobuf.ProtobufString>.self, value: &self.mapSint64String) }()
      case 8: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufFixed32,SwiftProtobuf.ProtobufString>.self, value: &self.mapFixed32String) }()
      case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufFixed64,SwiftProtobuf.ProtobufString>.self, value: &self.mapFixed64String) }()
      case 10: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSFixed32,SwiftProtobuf.ProtobufString>.self, value: &self.mapSfixed32String) }()
      case 11: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSFixed64,SwiftProtobuf.ProtobufString>.self, value: &self.mapSfixed64String) }()
      case 12: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufBool,SwiftProtobuf.ProtobufString>.self, value: &self.mapBoolString) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mapStringString.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.mapStringString, fieldNumber: 1)
    }
    if !self.mapInt32String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufString>.self, value: self.mapInt32String, fieldNumber: 2)
    }
    if !self.mapInt64String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt64,SwiftProtobuf.ProtobufString>.self, value: self.mapInt64String, fieldNumber: 3)
    }
    if !self.mapUint32String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt32,SwiftProtobuf.ProtobufString>.self, value: self.mapUint32String, fieldNumber: 4)
    }
    if !self.mapUint64String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufUInt64,SwiftProtobuf.ProtobufString>.self, value: self.mapUint64String, fieldNumber: 5)
    }
    if !self.mapSint32String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSInt32,SwiftProtobuf.ProtobufString>.self, value: self.mapSint32String, fieldNumber: 6)
    }
    if !self.mapSint64String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSInt64,SwiftProtobuf.ProtobufString>.self, value: self.mapSint64String, fieldNumber: 7)
    }
    if !self.mapFixed32String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufFixed32,SwiftProtobuf.ProtobufString>.self, value: self.mapFixed32String, fieldNumber: 8)
    }
    if !self.mapFixed64String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufFixed64,SwiftProtobuf.ProtobufString>.self, value: self.mapFixed64String, fieldNumber: 9)
    }
    if !self.mapSfixed32String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSFixed32,SwiftProtobuf.ProtobufString>.self, value: self.mapSfixed32String, fieldNumber: 10)
    }
    if !self.mapSfixed64String.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufSFixed64,SwiftProtobuf.ProtobufString>.self, value: self.mapSfixed64String, fieldNumber: 11)
    }
    if !self.mapBoolString.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufBool,SwiftProtobuf.ProtobufString>.self, value: self.mapBoolString, fieldNumber: 12)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MapAllKeyTypes, rhs: Testcompat_MapAllKeyTypes) -> Bool {
    if lhs.mapStringString != rhs.mapStringString {return false}
    if lhs.mapInt32String != rhs.mapInt32String {return false}
    if lhs.mapInt64String != rhs.mapInt64String {return false}
    if lhs.mapUint32String != rhs.mapUint32String {return false}
    if lhs.mapUint64String != rhs.mapUint64String {return false}
    if lhs.mapSint32String != rhs.mapSint32String {return false}
    if lhs.mapSint64String != rhs.mapSint64String {return false}
    if lhs.mapFixed32String != rhs.mapFixed32String {return false}
    if lhs.mapFixed64String != rhs.mapFixed64String {return false}
    if lhs.mapSfixed32String != rhs.mapSfixed32String {return false}
    if lhs.mapSfixed64String != rhs.mapSfixed64String {return false}
    if lhs.mapBoolString != rhs.mapBoolString {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MapAllValueTypes: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapAllValueTypes"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}map_s_int32\0\u{3}map_s_int64\0\u{3}map_s_double\0\u{3}map_s_float\0\u{3}map_s_bool\0\u{3}map_s_bytes\0\u{3}map_s_string\0\u{3}map_s_msg\0\u{3}map_s_enum\0\u{3}map_s_simple\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: &self.mapSInt32) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt64>.self, value: &self.mapSInt64) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: &self.mapSDouble) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufFloat>.self, value: &self.mapSFloat) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: &self.mapSBool) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBytes>.self, value: &self.mapSBytes) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.mapSString) }()
      case 8: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_ScalarMessage>.self, value: &self.mapSMsg) }()
      case 9: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: &self.mapSEnum) }()
      case 10: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_SimpleMessage>.self, value: &self.mapSSimple) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.mapSInt32.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: self.mapSInt32, fieldNumber: 1)
    }
    if !self.mapSInt64.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt64>.self, value: self.mapSInt64, fieldNumber: 2)
    }
    if !self.mapSDouble.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufDouble>.self, value: self.mapSDouble, fieldNumber: 3)
    }
    if !self.mapSFloat.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufFloat>.self, value: self.mapSFloat, fieldNumber: 4)
    }
    if !self.mapSBool.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBool>.self, value: self.mapSBool, fieldNumber: 5)
    }
    if !self.mapSBytes.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufBytes>.self, value: self.mapSBytes, fieldNumber: 6)
    }
    if !self.mapSString.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.mapSString, fieldNumber: 7)
    }
    if !self.mapSMsg.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_ScalarMessage>.self, value: self.mapSMsg, fieldNumber: 8)
    }
    if !self.mapSEnum.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: self.mapSEnum, fieldNumber: 9)
    }
    if !self.mapSSimple.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_SimpleMessage>.self, value: self.mapSSimple, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MapAllValueTypes, rhs: Testcompat_MapAllValueTypes) -> Bool {
    if lhs.mapSInt32 != rhs.mapSInt32 {return false}
    if lhs.mapSInt64 != rhs.mapSInt64 {return false}
    if lhs.mapSDouble != rhs.mapSDouble {return false}
    if lhs.mapSFloat != rhs.mapSFloat {return false}
    if lhs.mapSBool != rhs.mapSBool {return false}
    if lhs.mapSBytes != rhs.mapSBytes {return false}
    if lhs.mapSString != rhs.mapSString {return false}
    if lhs.mapSMsg != rhs.mapSMsg {return false}
    if lhs.mapSEnum != rhs.mapSEnum {return false}
    if lhs.mapSSimple != rhs.mapSSimple {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MixedContainers: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MixedContainers"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ids\0\u{1}names\0\u{1}scores\0\u{1}entries\0\u{1}items\0\u{1}statuses\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedInt32Field(value: &self.ids) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.names) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: &self.scores) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Testcompat_SimpleMessage>.self, value: &self.entries) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 6: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: &self.statuses) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.ids.isEmpty {
      try visitor.visitPackedInt32Field(value: self.ids, fieldNumber: 1)
    }
    if !self.names.isEmpty {
      try visitor.visitRepeatedStringField(value: self.names, fieldNumber: 2)
    }
    if !self.scores.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: self.scores, fieldNumber: 3)
    }
    if !self.entries.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufInt64,Testcompat_SimpleMessage>.self, value: self.entries, fieldNumber: 4)
    }
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 5)
    }
    if !self.statuses.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: self.statuses, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MixedContainers, rhs: Testcompat_MixedContainers) -> Bool {
    if lhs.ids != rhs.ids {return false}
    if lhs.names != rhs.names {return false}
    if lhs.scores != rhs.scores {return false}
    if lhs.entries != rhs.entries {return false}
    if lhs.items != rhs.items {return false}
    if lhs.statuses != rhs.statuses {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
