// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: cross_file_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// References types from every other file
struct Testcompat_CrossFileAll: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// common_types
  var simple: Testcompat_SimpleMessage {
    get {return _storage._simple ?? Testcompat_SimpleMessage()}
    set {_uniqueStorage()._simple = newValue}
  }
  /// Returns true if `simple` has been explicitly set.
  var hasSimple: Bool {return _storage._simple != nil}
  /// Clears the value of `simple`. Subsequent reads from it will return its default value.
  mutating func clearSimple() {_uniqueStorage()._simple = nil}

  /// scalar_types
  var scalar: Testcompat_ScalarMessage {
    get {return _storage._scalar ?? Testcompat_ScalarMessage()}
    set {_uniqueStorage()._scalar = newValue}
  }
  /// Returns true if `scalar` has been explicitly set.
  var hasScalar: Bool {return _storage._scalar != nil}
  /// Clears the value of `scalar`. Subsequent reads from it will return its default value.
  mutating func clearScalar() {_uniqueStorage()._scalar = nil}

  /// container_types
  var repeatedAll: Testcompat_RepeatedAllTypes {
    get {return _storage._repeatedAll ?? Testcompat_RepeatedAllTypes()}
    set {_uniqueStorage()._repeatedAll = newValue}
  }
  /// Returns true if `repeatedAll` has been explicitly set.
  var hasRepeatedAll: Bool {return _storage._repeatedAll != nil}
  /// Clears the value of `repeatedAll`. Subsequent reads from it will return its default value.
  mutating func clearRepeatedAll() {_uniqueStorage()._repeatedAll = nil}

  /// oneof_types
  var oneofMsg: Testcompat_OneofComplex {
    get {return _storage._oneofMsg ?? Testcompat_OneofComplex()}
    set {_uniqueStorage()._oneofMsg = newValue}
  }
  /// Returns true if `oneofMsg` has been explicitly set.
  var hasOneofMsg: Bool {return _storage._oneofMsg != nil}
  /// Clears the value of `oneofMsg`. Subsequent reads from it will return its default value.
  mutating func clearOneofMsg() {_uniqueStorage()._oneofMsg = nil}

  /// nesting_types
  var nested: Testcompat_Nested1 {
    get {return _storage._nested ?? Testcompat_Nested1()}
    set {_uniqueStorage()._nested = newValue}
  }
  /// Returns true if `nested` has been explicitly set.
  var hasNested: Bool {return _storage._nested != nil}
  /// Clears the value of `nested`. Subsequent reads from it will return its default value.
  mutating func clearNested() {_uniqueStorage()._nested = nil}

  /// wkt_types
  var wkt: Testcompat_WKTHolder {
    get {return _storage._wkt ?? Testcompat_WKTHolder()}
    set {_uniqueStorage()._wkt = newValue}
  }
  /// Returns true if `wkt` has been explicitly set.
  var hasWkt: Bool {return _storage._wkt != nil}
  /// Clears the value of `wkt`. Subsequent reads from it will return its default value.
  mutating func clearWkt() {_uniqueStorage()._wkt = nil}

  /// common_types enum
  var status: Testcompat_Status {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  /// common_types enum
  var priority: Testcompat_Priority {
    get {return _storage._priority}
    set {_uniqueStorage()._priority = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Cross-file in repeated/map/oneof
struct Testcompat_CrossFileMixed: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var items: [Testcompat_SimpleMessage] = []

  var details: Dictionary<String,Testcompat_ScalarMessage> = [:]

  var pick: Testcompat_CrossFileMixed.OneOf_Pick? = nil

  var simplePick: Testcompat_SimpleMessage {
    get {
      if case .simplePick(let v)? = pick {return v}
      return Testcompat_SimpleMessage()
    }
    set {pick = .simplePick(newValue)}
  }

  var wktPick: Testcompat_WKTHolder {
    get {
      if case .wktPick(let v)? = pick {return v}
      return Testcompat_WKTHolder()
    }
    set {pick = .wktPick(newValue)}
  }

  var nestedPick: Testcompat_Nested1 {
    get {
      if case .nestedPick(let v)? = pick {return v}
      return Testcompat_Nested1()
    }
    set {pick = .nestedPick(newValue)}
  }

  var statuses: [Testcompat_Status] = []

  var statusMap: Dictionary<String,Testcompat_Status> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Pick: Equatable, Sendable {
    case simplePick(Testcompat_SimpleMessage)
    case wktPick(Testcompat_WKTHolder)
    case nestedPick(Testcompat_Nested1)

  }

  init() {}
}

/// Cross-package: reference proto2 types from proto3 file
struct Testcompat_CrossPackageRef: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var p2Basic: Testcompat2_Proto2Basic {
    get {return _storage._p2Basic ?? Testcompat2_Proto2Basic()}
    set {_uniqueStorage()._p2Basic = newValue}
  }
  /// Returns true if `p2Basic` has been explicitly set.
  var hasP2Basic: Bool {return _storage._p2Basic != nil}
  /// Clears the value of `p2Basic`. Subsequent reads from it will return its default value.
  mutating func clearP2Basic() {_uniqueStorage()._p2Basic = nil}

  var p2Defaults: Testcompat2_Proto2Defaults {
    get {return _storage._p2Defaults ?? Testcompat2_Proto2Defaults()}
    set {_uniqueStorage()._p2Defaults = newValue}
  }
  /// Returns true if `p2Defaults` has been explicitly set.
  var hasP2Defaults: Bool {return _storage._p2Defaults != nil}
  /// Clears the value of `p2Defaults`. Subsequent reads from it will return its default value.
  mutating func clearP2Defaults() {_uniqueStorage()._p2Defaults = nil}

  var p2List: [Testcompat2_Proto2Basic] {
    get {return _storage._p2List}
    set {_uniqueStorage()._p2List = newValue}
  }

  var label: String {
    get {return _storage._label}
    set {_uniqueStorage()._label = newValue}
  }

  var created: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._created = newValue}
  }
  /// Returns true if `created` has been explicitly set.
  var hasCreated: Bool {return _storage._created != nil}
  /// Clears the value of `created`. Subsequent reads from it will return its default value.
  mutating func clearCreated() {_uniqueStorage()._created = nil}

  var count: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {return _storage._count ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._count = newValue}
  }
  /// Returns true if `count` has been explicitly set.
  var hasCount: Bool {return _storage._count != nil}
  /// Clears the value of `count`. Subsequent reads from it will return its default value.
  mutating func clearCount() {_uniqueStorage()._count = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Deeply mixed: nesting + cross-file + WKT + oneof + map
struct Testcompat_MegaMixed: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var child: Testcompat_MegaMixed.Layer2 {
    get {return _storage._child ?? Testcompat_MegaMixed.Layer2()}
    set {_uniqueStorage()._child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  var hasChild: Bool {return _storage._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  mutating func clearChild() {_uniqueStorage()._child = nil}

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var branches: Dictionary<String,Testcompat_MegaMixed.Layer2> {
    get {return _storage._branches}
    set {_uniqueStorage()._branches = newValue}
  }

  var oneofs: [Testcompat_OneofComplex] {
    get {return _storage._oneofs}
    set {_uniqueStorage()._oneofs = newValue}
  }

  var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  var hasTs: Bool {return _storage._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  mutating func clearTs() {_uniqueStorage()._ts = nil}

  var nested: Testcompat_Nested1 {
    get {return _storage._nested ?? Testcompat_Nested1()}
    set {_uniqueStorage()._nested = newValue}
  }
  /// Returns true if `nested` has been explicitly set.
  var hasNested: Bool {return _storage._nested != nil}
  /// Clears the value of `nested`. Subsequent reads from it will return its default value.
  mutating func clearNested() {_uniqueStorage()._nested = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Layer2: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var inner: Testcompat_MegaMixed.Layer2.Layer3 {
      get {return _inner ?? Testcompat_MegaMixed.Layer2.Layer3()}
      set {_inner = newValue}
    }
    /// Returns true if `inner` has been explicitly set.
    var hasInner: Bool {return self._inner != nil}
    /// Clears the value of `inner`. Subsequent reads from it will return its default value.
    mutating func clearInner() {self._inner = nil}

    var list: [Testcompat_MegaMixed.Layer2.Layer3] = []

    var choice: Testcompat_MegaMixed.Layer2.OneOf_Choice? = nil

    var text: String {
      get {
        if case .text(let v)? = choice {return v}
        return String()
      }
      set {choice = .text(newValue)}
    }

    var msg: Testcompat_SimpleMessage {
      get {
        if case .msg(let v)? = choice {return v}
        return Testcompat_SimpleMessage()
      }
      set {choice = .msg(newValue)}
    }

    var unknownFields = SwiftProtobuf.UnknownStorage()

    enum OneOf_Choice: Equatable, Sendable {
      case text(String)
      case msg(Testcompat_SimpleMessage)

    }

    struct Layer3: @unchecked Sendable {
      // SwiftProtobuf.Message conformance is added in an extension below. See the
      // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
      // methods supported on all messages.

      var simple: Testcompat_SimpleMessage {
        get {return _storage._simple ?? Testcompat_SimpleMessage()}
        set {_uniqueStorage()._simple = newValue}
      }
      /// Returns true if `simple` has been explicitly set.
      var hasSimple: Bool {return _storage._simple != nil}
      /// Clears the value of `simple`. Subsequent reads from it will return its default value.
      mutating func clearSimple() {_uniqueStorage()._simple = nil}

      var scalar: Testcompat_ScalarMessage {
        get {return _storage._scalar ?? Testcompat_ScalarMessage()}
        set {_uniqueStorage()._scalar = newValue}
      }
      /// Returns true if `scalar` has been explicitly set.
      var hasScalar: Bool {return _storage._scalar != nil}
      /// Clears the value of `scalar`. Subsequent reads from it will return its default value.
      mutating func clearScalar() {_uniqueStorage()._scalar = nil}

      var wkt: Testcompat_WKTHolder {
        get {return _storage._wkt ?? Testcompat_WKTHolder()}
        set {_uniqueStorage()._wkt = newValue}
      }
      /// Returns true if `wkt` has been explicitly set.
      var hasWkt: Bool {return _storage._wkt != nil}
      /// Clears the value of `wkt`. Subsequent reads from it will return its default value.
      mutating func clearWkt() {_uniqueStorage()._wkt = nil}

      var flags: Dictionary<String,Testcompat_Status> {
        get {return _storage._flags}
        set {_uniqueStorage()._flags = newValue}
      }

      var unknownFields = SwiftProtobuf.UnknownStorage()

      init() {}

      fileprivate var _storage = _StorageClass.defaultInstance
    }

    init() {}

    fileprivate var _inner: Testcompat_MegaMixed.Layer2.Layer3? = nil
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Kitchen Sink — flat, all features, maximum diversity
struct Testcompat_KitchenSinkFlat: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// Scalars
  var int32Val: Int32 {
    get {return _storage._int32Val}
    set {_uniqueStorage()._int32Val = newValue}
  }

  var int64Val: Int64 {
    get {return _storage._int64Val}
    set {_uniqueStorage()._int64Val = newValue}
  }

  var uint32Val: UInt32 {
    get {return _storage._uint32Val}
    set {_uniqueStorage()._uint32Val = newValue}
  }

  var uint64Val: UInt64 {
    get {return _storage._uint64Val}
    set {_uniqueStorage()._uint64Val = newValue}
  }

  var sint32Val: Int32 {
    get {return _storage._sint32Val}
    set {_uniqueStorage()._sint32Val = newValue}
  }

  var sint64Val: Int64 {
    get {return _storage._sint64Val}
    set {_uniqueStorage()._sint64Val = newValue}
  }

  var fixed32Val: UInt32 {
    get {return _storage._fixed32Val}
    set {_uniqueStorage()._fixed32Val = newValue}
  }

  var fixed64Val: UInt64 {
    get {return _storage._fixed64Val}
    set {_uniqueStorage()._fixed64Val = newValue}
  }

  var sfixed32Val: Int32 {
    get {return _storage._sfixed32Val}
    set {_uniqueStorage()._sfixed32Val = newValue}
  }

  var sfixed64Val: Int64 {
    get {return _storage._sfixed64Val}
    set {_uniqueStorage()._sfixed64Val = newValue}
  }

  var doubleVal: Double {
    get {return _storage._doubleVal}
    set {_uniqueStorage()._doubleVal = newValue}
  }

  var floatVal: Float {
    get {return _storage._floatVal}
    set {_uniqueStorage()._floatVal = newValue}
  }

  var boolVal: Bool {
    get {return _storage._boolVal}
    set {_uniqueStorage()._boolVal = newValue}
  }

  var stringVal: String {
    get {return _storage._stringVal}
    set {_uniqueStorage()._stringVal = newValue}
  }

  var bytesVal: Data {
    get {return _storage._bytesVal}
    set {_uniqueStorage()._bytesVal = newValue}
  }

  /// Enum
  var status: Testcompat_Status {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  var priority: Testcompat_Priority {
    get {return _storage._priority}
    set {_uniqueStorage()._priority = newValue}
  }

  /// Repeated
  var repInt32: [Int32] {
    get {return _storage._repInt32}
    set {_uniqueStorage()._repInt32 = newValue}
  }

  var repString: [String] {
    get {return _storage._repString}
    set {_uniqueStorage()._repString = newValue}
  }

  var repStatus: [Testcompat_Status] {
    get {return _storage._repStatus}
    set {_uniqueStorage()._repStatus = newValue}
  }

  var repMsg: [Testcompat_SimpleMessage] {
    get {return _storage._repMsg}
    set {_uniqueStorage()._repMsg = newValue}
  }

  /// Map
  var mapSs: Dictionary<String,String> {
    get {return _storage._mapSs}
    set {_uniqueStorage()._mapSs = newValue}
  }

  var mapIs: Dictionary<Int32,String> {
    get {return _storage._mapIs}
    set {_uniqueStorage()._mapIs = newValue}
  }

  var mapSm: Dictionary<String,Testcompat_SimpleMessage> {
    get {return _storage._mapSm}
    set {_uniqueStorage()._mapSm = newValue}
  }

  var mapSe: Dictionary<String,Testcompat_Status> {
    get {return _storage._mapSe}
    set {_uniqueStorage()._mapSe = newValue}
  }

  /// Oneof
  var choice: OneOf_Choice? {
    get {return _storage._choice}
    set {_uniqueStorage()._choice = newValue}
  }

  var oneofStr: String {
    get {
      if case .oneofStr(let v)? = _storage._choice {return v}
      return String()
    }
    set {_uniqueStorage()._choice = .oneofStr(newValue)}
  }

  var oneofInt: Int32 {
    get {
      if case .oneofInt(let v)? = _storage._choice {return v}
      return 0
    }
    set {_uniqueStorage()._choice = .oneofInt(newValue)}
  }

  var oneofMsg: Testcompat_SimpleMessage {
    get {
      if case .oneofMsg(let v)? = _storage._choice {return v}
      return Testcompat_SimpleMessage()
    }
    set {_uniqueStorage()._choice = .oneofMsg(newValue)}
  }

  /// WKTs
  var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  var hasTs: Bool {return _storage._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  mutating func clearTs() {_uniqueStorage()._ts = nil}

  var dur: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _storage._dur ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_uniqueStorage()._dur = newValue}
  }
  /// Returns true if `dur` has been explicitly set.
  var hasDur: Bool {return _storage._dur != nil}
  /// Clears the value of `dur`. Subsequent reads from it will return its default value.
  mutating func clearDur() {_uniqueStorage()._dur = nil}

  var i64W: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {return _storage._i64W ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._i64W = newValue}
  }
  /// Returns true if `i64W` has been explicitly set.
  var hasI64W: Bool {return _storage._i64W != nil}
  /// Clears the value of `i64W`. Subsequent reads from it will return its default value.
  mutating func clearI64W() {_uniqueStorage()._i64W = nil}

  var strW: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _storage._strW ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_uniqueStorage()._strW = newValue}
  }
  /// Returns true if `strW` has been explicitly set.
  var hasStrW: Bool {return _storage._strW != nil}
  /// Clears the value of `strW`. Subsequent reads from it will return its default value.
  mutating func clearStrW() {_uniqueStorage()._strW = nil}

  var structV: SwiftProtobuf.Google_Protobuf_Struct {
    get {return _storage._structV ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_uniqueStorage()._structV = newValue}
  }
  /// Returns true if `structV` has been explicitly set.
  var hasStructV: Bool {return _storage._structV != nil}
  /// Clears the value of `structV`. Subsequent reads from it will return its default value.
  mutating func clearStructV() {_uniqueStorage()._structV = nil}

  /// Nested
  var scalarDetail: Testcompat_ScalarMessage {
    get {return _storage._scalarDetail ?? Testcompat_ScalarMessage()}
    set {_uniqueStorage()._scalarDetail = newValue}
  }
  /// Returns true if `scalarDetail` has been explicitly set.
  var hasScalarDetail: Bool {return _storage._scalarDetail != nil}
  /// Clears the value of `scalarDetail`. Subsequent reads from it will return its default value.
  mutating func clearScalarDetail() {_uniqueStorage()._scalarDetail = nil}

  var deepNested: Testcompat_Nested1 {
    get {return _storage._deepNested ?? Testcompat_Nested1()}
    set {_uniqueStorage()._deepNested = newValue}
  }
  /// Returns true if `deepNested` has been explicitly set.
  var hasDeepNested: Bool {return _storage._deepNested != nil}
  /// Clears the value of `deepNested`. Subsequent reads from it will return its default value.
  mutating func clearDeepNested() {_uniqueStorage()._deepNested = nil}

  var wktAll: Testcompat_WKTHolder {
    get {return _storage._wktAll ?? Testcompat_WKTHolder()}
    set {_uniqueStorage()._wktAll = newValue}
  }
  /// Returns true if `wktAll` has been explicitly set.
  var hasWktAll: Bool {return _storage._wktAll != nil}
  /// Clears the value of `wktAll`. Subsequent reads from it will return its default value.
  mutating func clearWktAll() {_uniqueStorage()._wktAll = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  /// Oneof
  enum OneOf_Choice: Equatable, Sendable {
    case oneofStr(String)
    case oneofInt(Int32)
    case oneofMsg(Testcompat_SimpleMessage)

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Kitchen Sink — deep 4 levels, each with repeated/map/oneof
struct Testcompat_DeepLevel4: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Int32 = 0

  var items: [String] = []

  var status: Testcompat_Status = .unspecified

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

struct Testcompat_DeepLevel3: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var child: Testcompat_DeepLevel4 {
    get {return _child ?? Testcompat_DeepLevel4()}
    set {_child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  var hasChild: Bool {return self._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  mutating func clearChild() {self._child = nil}

  var props: Dictionary<String,String> = [:]

  var flag: Bool = false

  var aux: Testcompat_SimpleMessage {
    get {return _aux ?? Testcompat_SimpleMessage()}
    set {_aux = newValue}
  }
  /// Returns true if `aux` has been explicitly set.
  var hasAux: Bool {return self._aux != nil}
  /// Clears the value of `aux`. Subsequent reads from it will return its default value.
  mutating func clearAux() {self._aux = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _child: Testcompat_DeepLevel4? = nil
  fileprivate var _aux: Testcompat_SimpleMessage? = nil
}

struct Testcompat_DeepLevel2: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var child: Testcompat_DeepLevel3 {
    get {return _child ?? Testcompat_DeepLevel3()}
    set {_child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  var hasChild: Bool {return self._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  mutating func clearChild() {self._child = nil}

  var count: Int32 = 0

  var numbers: [Int32] = []

  var pick: Testcompat_DeepLevel2.OneOf_Pick? = nil

  var text: String {
    get {
      if case .text(let v)? = pick {return v}
      return String()
    }
    set {pick = .text(newValue)}
  }

  var active: Bool {
    get {
      if case .active(let v)? = pick {return v}
      return false
    }
    set {pick = .active(newValue)}
  }

  var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  var hasTs: Bool {return self._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  mutating func clearTs() {self._ts = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Pick: Equatable, Sendable {
    case text(String)
    case active(Bool)

  }

  init() {}

  fileprivate var _child: Testcompat_DeepLevel3? = nil
  fileprivate var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

struct Testcompat_DeepLevel1: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var child: Testcompat_DeepLevel2 {
    get {return _storage._child ?? Testcompat_DeepLevel2()}
    set {_uniqueStorage()._child = newValue}
  }
  /// Returns true if `child` has been explicitly set.
  var hasChild: Bool {return _storage._child != nil}
  /// Clears the value of `child`. Subsequent reads from it will return its default value.
  mutating func clearChild() {_uniqueStorage()._child = nil}

  var name: String {
    get {return _storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  var tags: [String] {
    get {return _storage._tags}
    set {_uniqueStorage()._tags = newValue}
  }

  var scores: Dictionary<String,Int32> {
    get {return _storage._scores}
    set {_uniqueStorage()._scores = newValue}
  }

  var extras: [Testcompat_DeepLevel2] {
    get {return _storage._extras}
    set {_uniqueStorage()._extras = newValue}
  }

  var countW: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {return _storage._countW ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._countW = newValue}
  }
  /// Returns true if `countW` has been explicitly set.
  var hasCountW: Bool {return _storage._countW != nil}
  /// Clears the value of `countW`. Subsequent reads from it will return its default value.
  mutating func clearCountW() {_uniqueStorage()._countW = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_CrossFileAll: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CrossFileAll"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}simple\0\u{1}scalar\0\u{3}repeated_all\0\u{3}oneof_msg\0\u{1}nested\0\u{1}wkt\0\u{1}status\0\u{1}priority\0")

  fileprivate class _StorageClass {
    var _simple: Testcompat_SimpleMessage? = nil
    var _scalar: Testcompat_ScalarMessage? = nil
    var _repeatedAll: Testcompat_RepeatedAllTypes? = nil
    var _oneofMsg: Testcompat_OneofComplex? = nil
    var _nested: Testcompat_Nested1? = nil
    var _wkt: Testcompat_WKTHolder? = nil
    var _status: Testcompat_Status = .unspecified
    var _priority: Testcompat_Priority = .unspecified

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _simple = source._simple
      _scalar = source._scalar
      _repeatedAll = source._repeatedAll
      _oneofMsg = source._oneofMsg
      _nested = source._nested
      _wkt = source._wkt
      _status = source._status
      _priority = source._priority
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._simple) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._scalar) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._repeatedAll) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._oneofMsg) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._nested) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._wkt) }()
        case 7: try { try decoder.decodeSingularEnumField(value: &_storage._status) }()
        case 8: try { try decoder.decodeSingularEnumField(value: &_storage._priority) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._simple {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._scalar {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._repeatedAll {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._oneofMsg {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._nested {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._wkt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      if _storage._status != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 7)
      }
      if _storage._priority != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._priority, fieldNumber: 8)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_CrossFileAll, rhs: Testcompat_CrossFileAll) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._simple != rhs_storage._simple {return false}
        if _storage._scalar != rhs_storage._scalar {return false}
        if _storage._repeatedAll != rhs_storage._repeatedAll {return false}
        if _storage._oneofMsg != rhs_storage._oneofMsg {return false}
        if _storage._nested != rhs_storage._nested {return false}
        if _storage._wkt != rhs_storage._wkt {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._priority != rhs_storage._priority {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_CrossFileMixed: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CrossFileMixed"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}items\0\u{1}details\0\u{3}simple_pick\0\u{3}wkt_pick\0\u{3}nested_pick\0\u{1}statuses\0\u{3}status_map\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_ScalarMessage>.self, value: &self.details) }()
      case 3: try {
        var v: Testcompat_SimpleMessage?
        var hadOneofValue = false
        if let current = self.pick {
          hadOneofValue = true
          if case .simplePick(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.pick = .simplePick(v)
        }
      }()
      case 4: try {
        var v: Testcompat_WKTHolder?
        var hadOneofValue = false
        if let current = self.pick {
          hadOneofValue = true
          if case .wktPick(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.pick = .wktPick(v)
        }
      }()
      case 5: try {
        var v: Testcompat_Nested1?
        var hadOneofValue = false
        if let current = self.pick {
          hadOneofValue = true
          if case .nestedPick(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.pick = .nestedPick(v)
        }
      }()
      case 6: try { try decoder.decodeRepeatedEnumField(value: &self.statuses) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: &self.statusMap) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 1)
    }
    if !self.details.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_ScalarMessage>.self, value: self.details, fieldNumber: 2)
    }
    switch self.pick {
    case .simplePick?: try {
      guard case .simplePick(let v)? = self.pick else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .wktPick?: try {
      guard case .wktPick(let v)? = self.pick else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .nestedPick?: try {
      guard case .nestedPick(let v)? = self.pick else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    if !self.statuses.isEmpty {
      try visitor.visitPackedEnumField(value: self.statuses, fieldNumber: 6)
    }
    if !self.statusMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: self.statusMap, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_CrossFileMixed, rhs: Testcompat_CrossFileMixed) -> Bool {
    if lhs.items != rhs.items {return false}
    if lhs.details != rhs.details {return false}
    if lhs.pick != rhs.pick {return false}
    if lhs.statuses != rhs.statuses {return false}
    if lhs.statusMap != rhs.statusMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_CrossPackageRef: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".CrossPackageRef"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}p2_basic\0\u{3}p2_defaults\0\u{4}\u{2}p2_list\0\u{2}\u{6}label\0\u{1}created\0\u{1}count\0")

  fileprivate class _StorageClass {
    var _p2Basic: Testcompat2_Proto2Basic? = nil
    var _p2Defaults: Testcompat2_Proto2Defaults? = nil
    var _p2List: [Testcompat2_Proto2Basic] = []
    var _label: String = String()
    var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _count: SwiftProtobuf.Google_Protobuf_Int64Value? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _p2Basic = source._p2Basic
      _p2Defaults = source._p2Defaults
      _p2List = source._p2List
      _label = source._label
      _created = source._created
      _count = source._count
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if let v = _storage._p2Basic, !v.isInitialized {return false}
      if !SwiftProtobuf.Internal.areAllInitialized(_storage._p2List) {return false}
      return true
    }
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._p2Basic) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._p2Defaults) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._p2List) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._label) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._created) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._count) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._p2Basic {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._p2Defaults {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      if !_storage._p2List.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._p2List, fieldNumber: 4)
      }
      if !_storage._label.isEmpty {
        try visitor.visitSingularStringField(value: _storage._label, fieldNumber: 10)
      }
      try { if let v = _storage._created {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._count {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_CrossPackageRef, rhs: Testcompat_CrossPackageRef) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._p2Basic != rhs_storage._p2Basic {return false}
        if _storage._p2Defaults != rhs_storage._p2Defaults {return false}
        if _storage._p2List != rhs_storage._p2List {return false}
        if _storage._label != rhs_storage._label {return false}
        if _storage._created != rhs_storage._created {return false}
        if _storage._count != rhs_storage._count {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MegaMixed: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MegaMixed"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}name\0\u{1}branches\0\u{1}oneofs\0\u{1}ts\0\u{1}nested\0")

  fileprivate class _StorageClass {
    var _child: Testcompat_MegaMixed.Layer2? = nil
    var _name: String = String()
    var _branches: Dictionary<String,Testcompat_MegaMixed.Layer2> = [:]
    var _oneofs: [Testcompat_OneofComplex] = []
    var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _nested: Testcompat_Nested1? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _child = source._child
      _name = source._name
      _branches = source._branches
      _oneofs = source._oneofs
      _ts = source._ts
      _nested = source._nested
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._child) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_MegaMixed.Layer2>.self, value: &_storage._branches) }()
        case 4: try { try decoder.decodeRepeatedMessageField(value: &_storage._oneofs) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._ts) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._nested) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._child {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._branches.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_MegaMixed.Layer2>.self, value: _storage._branches, fieldNumber: 3)
      }
      if !_storage._oneofs.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._oneofs, fieldNumber: 4)
      }
      try { if let v = _storage._ts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._nested {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MegaMixed, rhs: Testcompat_MegaMixed) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._child != rhs_storage._child {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._branches != rhs_storage._branches {return false}
        if _storage._oneofs != rhs_storage._oneofs {return false}
        if _storage._ts != rhs_storage._ts {return false}
        if _storage._nested != rhs_storage._nested {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MegaMixed.Layer2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_MegaMixed.protoMessageName + ".Layer2"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}inner\0\u{1}list\0\u{1}text\0\u{1}msg\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._inner) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.list) }()
      case 3: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .text(v)
        }
      }()
      case 4: try {
        var v: Testcompat_SimpleMessage?
        var hadOneofValue = false
        if let current = self.choice {
          hadOneofValue = true
          if case .msg(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.choice = .msg(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._inner {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.list.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.list, fieldNumber: 2)
    }
    switch self.choice {
    case .text?: try {
      guard case .text(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    }()
    case .msg?: try {
      guard case .msg(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MegaMixed.Layer2, rhs: Testcompat_MegaMixed.Layer2) -> Bool {
    if lhs._inner != rhs._inner {return false}
    if lhs.list != rhs.list {return false}
    if lhs.choice != rhs.choice {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MegaMixed.Layer2.Layer3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_MegaMixed.Layer2.protoMessageName + ".Layer3"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}simple\0\u{1}scalar\0\u{1}wkt\0\u{1}flags\0")

  fileprivate class _StorageClass {
    var _simple: Testcompat_SimpleMessage? = nil
    var _scalar: Testcompat_ScalarMessage? = nil
    var _wkt: Testcompat_WKTHolder? = nil
    var _flags: Dictionary<String,Testcompat_Status> = [:]

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _simple = source._simple
      _scalar = source._scalar
      _wkt = source._wkt
      _flags = source._flags
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._simple) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._scalar) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._wkt) }()
        case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: &_storage._flags) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._simple {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._scalar {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._wkt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      if !_storage._flags.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: _storage._flags, fieldNumber: 4)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MegaMixed.Layer2.Layer3, rhs: Testcompat_MegaMixed.Layer2.Layer3) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._simple != rhs_storage._simple {return false}
        if _storage._scalar != rhs_storage._scalar {return false}
        if _storage._wkt != rhs_storage._wkt {return false}
        if _storage._flags != rhs_storage._flags {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_KitchenSinkFlat: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".KitchenSinkFlat"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}int32_val\0\u{3}int64_val\0\u{3}uint32_val\0\u{3}uint64_val\0\u{3}sint32_val\0\u{3}sint64_val\0\u{3}fixed32_val\0\u{3}fixed64_val\0\u{3}sfixed32_val\0\u{3}sfixed64_val\0\u{3}double_val\0\u{3}float_val\0\u{3}bool_val\0\u{3}string_val\0\u{3}bytes_val\0\u{1}status\0\u{1}priority\0\u{3}rep_int32\0\u{3}rep_string\0\u{3}rep_status\0\u{3}rep_msg\0\u{3}map_ss\0\u{3}map_is\0\u{3}map_sm\0\u{3}map_se\0\u{3}oneof_str\0\u{3}oneof_int\0\u{3}oneof_msg\0\u{1}ts\0\u{1}dur\0\u{3}i64_w\0\u{3}str_w\0\u{3}struct_v\0\u{3}scalar_detail\0\u{3}deep_nested\0\u{3}wkt_all\0")

  fileprivate class _StorageClass {
    var _int32Val: Int32 = 0
    var _int64Val: Int64 = 0
    var _uint32Val: UInt32 = 0
    var _uint64Val: UInt64 = 0
    var _sint32Val: Int32 = 0
    var _sint64Val: Int64 = 0
    var _fixed32Val: UInt32 = 0
    var _fixed64Val: UInt64 = 0
    var _sfixed32Val: Int32 = 0
    var _sfixed64Val: Int64 = 0
    var _doubleVal: Double = 0
    var _floatVal: Float = 0
    var _boolVal: Bool = false
    var _stringVal: String = String()
    var _bytesVal: Data = Data()
    var _status: Testcompat_Status = .unspecified
    var _priority: Testcompat_Priority = .unspecified
    var _repInt32: [Int32] = []
    var _repString: [String] = []
    var _repStatus: [Testcompat_Status] = []
    var _repMsg: [Testcompat_SimpleMessage] = []
    var _mapSs: Dictionary<String,String> = [:]
    var _mapIs: Dictionary<Int32,String> = [:]
    var _mapSm: Dictionary<String,Testcompat_SimpleMessage> = [:]
    var _mapSe: Dictionary<String,Testcompat_Status> = [:]
    var _choice: Testcompat_KitchenSinkFlat.OneOf_Choice?
    var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _dur: SwiftProtobuf.Google_Protobuf_Duration? = nil
    var _i64W: SwiftProtobuf.Google_Protobuf_Int64Value? = nil
    var _strW: SwiftProtobuf.Google_Protobuf_StringValue? = nil
    var _structV: SwiftProtobuf.Google_Protobuf_Struct? = nil
    var _scalarDetail: Testcompat_ScalarMessage? = nil
    var _deepNested: Testcompat_Nested1? = nil
    var _wktAll: Testcompat_WKTHolder? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _int32Val = source._int32Val
      _int64Val = source._int64Val
      _uint32Val = source._uint32Val
      _uint64Val = source._uint64Val
      _sint32Val = source._sint32Val
      _sint64Val = source._sint64Val
      _fixed32Val = source._fixed32Val
      _fixed64Val = source._fixed64Val
      _sfixed32Val = source._sfixed32Val
      _sfixed64Val = source._sfixed64Val
      _doubleVal = source._doubleVal
      _floatVal = source._floatVal
      _boolVal = source._boolVal
      _stringVal = source._stringVal
      _bytesVal = source._bytesVal
      _status = source._status
      _priority = source._priority
      _repInt32 = source._repInt32
      _repString = source._repString
      _repStatus = source._repStatus
      _repMsg = source._repMsg
      _mapSs = source._mapSs
      _mapIs = source._mapIs
      _mapSm = source._mapSm
      _mapSe = source._mapSe
      _choice = source._choice
      _ts = source._ts
      _dur = source._dur
      _i64W = source._i64W
      _strW = source._strW
      _structV = source._structV
      _scalarDetail = source._scalarDetail
      _deepNested = source._deepNested
      _wktAll = source._wktAll
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularInt32Field(value: &_storage._int32Val) }()
        case 2: try { try decoder.decodeSingularInt64Field(value: &_storage._int64Val) }()
        case 3: try { try decoder.decodeSingularUInt32Field(value: &_storage._uint32Val) }()
        case 4: try { try decoder.decodeSingularUInt64Field(value: &_storage._uint64Val) }()
        case 5: try { try decoder.decodeSingularSInt32Field(value: &_storage._sint32Val) }()
        case 6: try { try decoder.decodeSingularSInt64Field(value: &_storage._sint64Val) }()
        case 7: try { try decoder.decodeSingularFixed32Field(value: &_storage._fixed32Val) }()
        case 8: try { try decoder.decodeSingularFixed64Field(value: &_storage._fixed64Val) }()
        case 9: try { try decoder.decodeSingularSFixed32Field(value: &_storage._sfixed32Val) }()
        case 10: try { try decoder.decodeSingularSFixed64Field(value: &_storage._sfixed64Val) }()
        case 11: try { try decoder.decodeSingularDoubleField(value: &_storage._doubleVal) }()
        case 12: try { try decoder.decodeSingularFloatField(value: &_storage._floatVal) }()
        case 13: try { try decoder.decodeSingularBoolField(value: &_storage._boolVal) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._stringVal) }()
        case 15: try { try decoder.decodeSingularBytesField(value: &_storage._bytesVal) }()
        case 16: try { try decoder.decodeSingularEnumField(value: &_storage._status) }()
        case 17: try { try decoder.decodeSingularEnumField(value: &_storage._priority) }()
        case 18: try { try decoder.decodeRepeatedInt32Field(value: &_storage._repInt32) }()
        case 19: try { try decoder.decodeRepeatedStringField(value: &_storage._repString) }()
        case 20: try { try decoder.decodeRepeatedEnumField(value: &_storage._repStatus) }()
        case 21: try { try decoder.decodeRepeatedMessageField(value: &_storage._repMsg) }()
        case 22: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &_storage._mapSs) }()
        case 23: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufString>.self, value: &_storage._mapIs) }()
        case 24: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_SimpleMessage>.self, value: &_storage._mapSm) }()
        case 25: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: &_storage._mapSe) }()
        case 26: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._choice != nil {try decoder.handleConflictingOneOf()}
            _storage._choice = .oneofStr(v)
          }
        }()
        case 27: try {
          var v: Int32?
          try decoder.decodeSingularInt32Field(value: &v)
          if let v = v {
            if _storage._choice != nil {try decoder.handleConflictingOneOf()}
            _storage._choice = .oneofInt(v)
          }
        }()
        case 28: try {
          var v: Testcompat_SimpleMessage?
          var hadOneofValue = false
          if let current = _storage._choice {
            hadOneofValue = true
            if case .oneofMsg(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._choice = .oneofMsg(v)
          }
        }()
        case 29: try { try decoder.decodeSingularMessageField(value: &_storage._ts) }()
        case 30: try { try decoder.decodeSingularMessageField(value: &_storage._dur) }()
        case 31: try { try decoder.decodeSingularMessageField(value: &_storage._i64W) }()
        case 32: try { try decoder.decodeSingularMessageField(value: &_storage._strW) }()
        case 33: try { try decoder.decodeSingularMessageField(value: &_storage._structV) }()
        case 34: try { try decoder.decodeSingularMessageField(value: &_storage._scalarDetail) }()
        case 35: try { try decoder.decodeSingularMessageField(value: &_storage._deepNested) }()
        case 36: try { try decoder.decodeSingularMessageField(value: &_storage._wktAll) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      if _storage._int32Val != 0 {
        try visitor.visitSingularInt32Field(value: _storage._int32Val, fieldNumber: 1)
      }
      if _storage._int64Val != 0 {
        try visitor.visitSingularInt64Field(value: _storage._int64Val, fieldNumber: 2)
      }
      if _storage._uint32Val != 0 {
        try visitor.visitSingularUInt32Field(value: _storage._uint32Val, fieldNumber: 3)
      }
      if _storage._uint64Val != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._uint64Val, fieldNumber: 4)
      }
      if _storage._sint32Val != 0 {
        try visitor.visitSingularSInt32Field(value: _storage._sint32Val, fieldNumber: 5)
      }
      if _storage._sint64Val != 0 {
        try visitor.visitSingularSInt64Field(value: _storage._sint64Val, fieldNumber: 6)
      }
      if _storage._fixed32Val != 0 {
        try visitor.visitSingularFixed32Field(value: _storage._fixed32Val, fieldNumber: 7)
      }
      if _storage._fixed64Val != 0 {
        try visitor.visitSingularFixed64Field(value: _storage._fixed64Val, fieldNumber: 8)
      }
      if _storage._sfixed32Val != 0 {
        try visitor.visitSingularSFixed32Field(value: _storage._sfixed32Val, fieldNumber: 9)
      }
      if _storage._sfixed64Val != 0 {
        try visitor.visitSingularSFixed64Field(value: _storage._sfixed64Val, fieldNumber: 10)
      }
      if _storage._doubleVal.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._doubleVal, fieldNumber: 11)
      }
      if _storage._floatVal.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._floatVal, fieldNumber: 12)
      }
      if _storage._boolVal != false {
        try visitor.visitSingularBoolField(value: _storage._boolVal, fieldNumber: 13)
      }
      if !_storage._stringVal.isEmpty {
        try visitor.visitSingularStringField(value: _storage._stringVal, fieldNumber: 14)
      }
      if !_storage._bytesVal.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._bytesVal, fieldNumber: 15)
      }
      if _storage._status != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 16)
      }
      if _storage._priority != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._priority, fieldNumber: 17)
      }
      if !_storage._repInt32.isEmpty {
        try visitor.visitPackedInt32Field(value: _storage._repInt32, fieldNumber: 18)
      }
      if !_storage._repString.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._repString, fieldNumber: 19)
      }
      if !_storage._repStatus.isEmpty {
        try visitor.visitPackedEnumField(value: _storage._repStatus, fieldNumber: 20)
      }
      if !_storage._repMsg.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._repMsg, fieldNumber: 21)
      }
      if !_storage._mapSs.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: _storage._mapSs, fieldNumber: 22)
      }
      if !_storage._mapIs.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufInt32,SwiftProtobuf.ProtobufString>.self, value: _storage._mapIs, fieldNumber: 23)
      }
      if !_storage._mapSm.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_SimpleMessage>.self, value: _storage._mapSm, fieldNumber: 24)
      }
      if !_storage._mapSe.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_Status>.self, value: _storage._mapSe, fieldNumber: 25)
      }
      switch _storage._choice {
      case .oneofStr?: try {
        guard case .oneofStr(let v)? = _storage._choice else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 26)
      }()
      case .oneofInt?: try {
        guard case .oneofInt(let v)? = _storage._choice else { preconditionFailure() }
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 27)
      }()
      case .oneofMsg?: try {
        guard case .oneofMsg(let v)? = _storage._choice else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 28)
      }()
      case nil: break
      }
      try { if let v = _storage._ts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 29)
      } }()
      try { if let v = _storage._dur {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 30)
      } }()
      try { if let v = _storage._i64W {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 31)
      } }()
      try { if let v = _storage._strW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 32)
      } }()
      try { if let v = _storage._structV {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 33)
      } }()
      try { if let v = _storage._scalarDetail {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 34)
      } }()
      try { if let v = _storage._deepNested {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 35)
      } }()
      try { if let v = _storage._wktAll {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 36)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_KitchenSinkFlat, rhs: Testcompat_KitchenSinkFlat) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._int32Val != rhs_storage._int32Val {return false}
        if _storage._int64Val != rhs_storage._int64Val {return false}
        if _storage._uint32Val != rhs_storage._uint32Val {return false}
        if _storage._uint64Val != rhs_storage._uint64Val {return false}
        if _storage._sint32Val != rhs_storage._sint32Val {return false}
        if _storage._sint64Val != rhs_storage._sint64Val {return false}
        if _storage._fixed32Val != rhs_storage._fixed32Val {return false}
        if _storage._fixed64Val != rhs_storage._fixed64Val {return false}
        if _storage._sfixed32Val != rhs_storage._sfixed32Val {return false}
        if _storage._sfixed64Val != rhs_storage._sfixed64Val {return false}
        if _storage._doubleVal != rhs_storage._doubleVal {return false}
        if _storage._floatVal != rhs_storage._floatVal {return false}
        if _storage._boolVal != rhs_storage._boolVal {return false}
        if _storage._stringVal != rhs_storage._stringVal {return false}
        if _storage._bytesVal != rhs_storage._bytesVal {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._priority != rhs_storage._priority {return false}
        if _storage._repInt32 != rhs_storage._repInt32 {return false}
        if _storage._repString != rhs_storage._repString {return false}
        if _storage._repStatus != rhs_storage._repStatus {return false}
        if _storage._repMsg != rhs_storage._repMsg {return false}
        if _storage._mapSs != rhs_storage._mapSs {return false}
        if _storage._mapIs != rhs_storage._mapIs {return false}
        if _storage._mapSm != rhs_storage._mapSm {return false}
        if _storage._mapSe != rhs_storage._mapSe {return false}
        if _storage._choice != rhs_storage._choice {return false}
        if _storage._ts != rhs_storage._ts {return false}
        if _storage._dur != rhs_storage._dur {return false}
        if _storage._i64W != rhs_storage._i64W {return false}
        if _storage._strW != rhs_storage._strW {return false}
        if _storage._structV != rhs_storage._structV {return false}
        if _storage._scalarDetail != rhs_storage._scalarDetail {return false}
        if _storage._deepNested != rhs_storage._deepNested {return false}
        if _storage._wktAll != rhs_storage._wktAll {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_DeepLevel4: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeepLevel4"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0\u{1}items\0\u{1}status\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.value) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.items) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self.status) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.value != 0 {
      try visitor.visitSingularInt32Field(value: self.value, fieldNumber: 1)
    }
    if !self.items.isEmpty {
      try visitor.visitRepeatedStringField(value: self.items, fieldNumber: 2)
    }
    if self.status != .unspecified {
      try visitor.visitSingularEnumField(value: self.status, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_DeepLevel4, rhs: Testcompat_DeepLevel4) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.items != rhs.items {return false}
    if lhs.status != rhs.status {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_DeepLevel3: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeepLevel3"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}props\0\u{1}flag\0\u{1}aux\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._child) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.props) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.flag) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._aux) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._child {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.props.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.props, fieldNumber: 2)
    }
    if self.flag != false {
      try visitor.visitSingularBoolField(value: self.flag, fieldNumber: 3)
    }
    try { if let v = self._aux {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_DeepLevel3, rhs: Testcompat_DeepLevel3) -> Bool {
    if lhs._child != rhs._child {return false}
    if lhs.props != rhs.props {return false}
    if lhs.flag != rhs.flag {return false}
    if lhs._aux != rhs._aux {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_DeepLevel2: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeepLevel2"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}count\0\u{1}numbers\0\u{1}text\0\u{1}active\0\u{1}ts\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._child) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.count) }()
      case 3: try { try decoder.decodeRepeatedInt32Field(value: &self.numbers) }()
      case 4: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.pick != nil {try decoder.handleConflictingOneOf()}
          self.pick = .text(v)
        }
      }()
      case 5: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.pick != nil {try decoder.handleConflictingOneOf()}
          self.pick = .active(v)
        }
      }()
      case 6: try { try decoder.decodeSingularMessageField(value: &self._ts) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._child {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if self.count != 0 {
      try visitor.visitSingularInt32Field(value: self.count, fieldNumber: 2)
    }
    if !self.numbers.isEmpty {
      try visitor.visitPackedInt32Field(value: self.numbers, fieldNumber: 3)
    }
    switch self.pick {
    case .text?: try {
      guard case .text(let v)? = self.pick else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 4)
    }()
    case .active?: try {
      guard case .active(let v)? = self.pick else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    try { if let v = self._ts {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_DeepLevel2, rhs: Testcompat_DeepLevel2) -> Bool {
    if lhs._child != rhs._child {return false}
    if lhs.count != rhs.count {return false}
    if lhs.numbers != rhs.numbers {return false}
    if lhs.pick != rhs.pick {return false}
    if lhs._ts != rhs._ts {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_DeepLevel1: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DeepLevel1"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}child\0\u{1}name\0\u{1}tags\0\u{1}scores\0\u{1}extras\0\u{3}count_w\0")

  fileprivate class _StorageClass {
    var _child: Testcompat_DeepLevel2? = nil
    var _name: String = String()
    var _tags: [String] = []
    var _scores: Dictionary<String,Int32> = [:]
    var _extras: [Testcompat_DeepLevel2] = []
    var _countW: SwiftProtobuf.Google_Protobuf_Int64Value? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _child = source._child
      _name = source._name
      _tags = source._tags
      _scores = source._scores
      _extras = source._extras
      _countW = source._countW
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._child) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeRepeatedStringField(value: &_storage._tags) }()
        case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: &_storage._scores) }()
        case 5: try { try decoder.decodeRepeatedMessageField(value: &_storage._extras) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._countW) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._child {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._tags.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._tags, fieldNumber: 3)
      }
      if !_storage._scores.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: _storage._scores, fieldNumber: 4)
      }
      if !_storage._extras.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._extras, fieldNumber: 5)
      }
      try { if let v = _storage._countW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_DeepLevel1, rhs: Testcompat_DeepLevel1) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._child != rhs_storage._child {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._tags != rhs_storage._tags {return false}
        if _storage._scores != rhs_storage._scores {return false}
        if _storage._extras != rhs_storage._extras {return false}
        if _storage._countW != rhs_storage._countW {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
