// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: oneof_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Simple oneof with all scalar variant types
struct Testcompat_OneofScalars: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var value: Testcompat_OneofScalars.OneOf_Value? = nil

  var doubleVal: Double {
    get {
      if case .doubleVal(let v)? = value {return v}
      return 0
    }
    set {value = .doubleVal(newValue)}
  }

  var floatVal: Float {
    get {
      if case .floatVal(let v)? = value {return v}
      return 0
    }
    set {value = .floatVal(newValue)}
  }

  var int32Val: Int32 {
    get {
      if case .int32Val(let v)? = value {return v}
      return 0
    }
    set {value = .int32Val(newValue)}
  }

  var int64Val: Int64 {
    get {
      if case .int64Val(let v)? = value {return v}
      return 0
    }
    set {value = .int64Val(newValue)}
  }

  var uint32Val: UInt32 {
    get {
      if case .uint32Val(let v)? = value {return v}
      return 0
    }
    set {value = .uint32Val(newValue)}
  }

  var uint64Val: UInt64 {
    get {
      if case .uint64Val(let v)? = value {return v}
      return 0
    }
    set {value = .uint64Val(newValue)}
  }

  var boolVal: Bool {
    get {
      if case .boolVal(let v)? = value {return v}
      return false
    }
    set {value = .boolVal(newValue)}
  }

  var stringVal: String {
    get {
      if case .stringVal(let v)? = value {return v}
      return String()
    }
    set {value = .stringVal(newValue)}
  }

  var bytesVal: Data {
    get {
      if case .bytesVal(let v)? = value {return v}
      return Data()
    }
    set {value = .bytesVal(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Value: Equatable, Sendable {
    case doubleVal(Double)
    case floatVal(Float)
    case int32Val(Int32)
    case int64Val(Int64)
    case uint32Val(UInt32)
    case uint64Val(UInt64)
    case boolVal(Bool)
    case stringVal(String)
    case bytesVal(Data)

  }

  init() {}
}

/// Oneof with message, enum, bytes variants
struct Testcompat_OneofComplex: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var choice: Testcompat_OneofComplex.OneOf_Choice? = nil

  var intVal: Int32 {
    get {
      if case .intVal(let v)? = choice {return v}
      return 0
    }
    set {choice = .intVal(newValue)}
  }

  var stringVal: String {
    get {
      if case .stringVal(let v)? = choice {return v}
      return String()
    }
    set {choice = .stringVal(newValue)}
  }

  var msgVal: Testcompat_ScalarMessage {
    get {
      if case .msgVal(let v)? = choice {return v}
      return Testcompat_ScalarMessage()
    }
    set {choice = .msgVal(newValue)}
  }

  var bytesVal: Data {
    get {
      if case .bytesVal(let v)? = choice {return v}
      return Data()
    }
    set {choice = .bytesVal(newValue)}
  }

  var enumVal: Testcompat_Status {
    get {
      if case .enumVal(let v)? = choice {return v}
      return .unspecified
    }
    set {choice = .enumVal(newValue)}
  }

  var simpleVal: Testcompat_SimpleMessage {
    get {
      if case .simpleVal(let v)? = choice {return v}
      return Testcompat_SimpleMessage()
    }
    set {choice = .simpleVal(newValue)}
  }

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Choice: Equatable, Sendable {
    case intVal(Int32)
    case stringVal(String)
    case msgVal(Testcompat_ScalarMessage)
    case bytesVal(Data)
    case enumVal(Testcompat_Status)
    case simpleVal(Testcompat_SimpleMessage)

  }

  init() {}
}

/// Multiple oneof blocks in one message
struct Testcompat_MultiOneof: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var firstChoice: OneOf_FirstChoice? {
    get {return _storage._firstChoice}
    set {_uniqueStorage()._firstChoice = newValue}
  }

  var firstInt: Int32 {
    get {
      if case .firstInt(let v)? = _storage._firstChoice {return v}
      return 0
    }
    set {_uniqueStorage()._firstChoice = .firstInt(newValue)}
  }

  var firstStr: String {
    get {
      if case .firstStr(let v)? = _storage._firstChoice {return v}
      return String()
    }
    set {_uniqueStorage()._firstChoice = .firstStr(newValue)}
  }

  var firstBool: Bool {
    get {
      if case .firstBool(let v)? = _storage._firstChoice {return v}
      return false
    }
    set {_uniqueStorage()._firstChoice = .firstBool(newValue)}
  }

  var secondChoice: OneOf_SecondChoice? {
    get {return _storage._secondChoice}
    set {_uniqueStorage()._secondChoice = newValue}
  }

  var secondDbl: Double {
    get {
      if case .secondDbl(let v)? = _storage._secondChoice {return v}
      return 0
    }
    set {_uniqueStorage()._secondChoice = .secondDbl(newValue)}
  }

  var secondBytes: Data {
    get {
      if case .secondBytes(let v)? = _storage._secondChoice {return v}
      return Data()
    }
    set {_uniqueStorage()._secondChoice = .secondBytes(newValue)}
  }

  var secondEnum: Testcompat_Status {
    get {
      if case .secondEnum(let v)? = _storage._secondChoice {return v}
      return .unspecified
    }
    set {_uniqueStorage()._secondChoice = .secondEnum(newValue)}
  }

  var thirdChoice: OneOf_ThirdChoice? {
    get {return _storage._thirdChoice}
    set {_uniqueStorage()._thirdChoice = newValue}
  }

  var thirdMsg: Testcompat_SimpleMessage {
    get {
      if case .thirdMsg(let v)? = _storage._thirdChoice {return v}
      return Testcompat_SimpleMessage()
    }
    set {_uniqueStorage()._thirdChoice = .thirdMsg(newValue)}
  }

  var thirdScalar: Testcompat_ScalarMessage {
    get {
      if case .thirdScalar(let v)? = _storage._thirdChoice {return v}
      return Testcompat_ScalarMessage()
    }
    set {_uniqueStorage()._thirdChoice = .thirdScalar(newValue)}
  }

  var label: String {
    get {return _storage._label}
    set {_uniqueStorage()._label = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_FirstChoice: Equatable, Sendable {
    case firstInt(Int32)
    case firstStr(String)
    case firstBool(Bool)

  }

  enum OneOf_SecondChoice: Equatable, Sendable {
    case secondDbl(Double)
    case secondBytes(Data)
    case secondEnum(Testcompat_Status)

  }

  enum OneOf_ThirdChoice: Equatable, Sendable {
    case thirdMsg(Testcompat_SimpleMessage)
    case thirdScalar(Testcompat_ScalarMessage)

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Oneof with WKT variants
struct Testcompat_OneofWKT: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var wktChoice: Testcompat_OneofWKT.OneOf_WktChoice? = nil

  var tsVal: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {
      if case .tsVal(let v)? = wktChoice {return v}
      return SwiftProtobuf.Google_Protobuf_Timestamp()
    }
    set {wktChoice = .tsVal(newValue)}
  }

  var i64WVal: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {
      if case .i64WVal(let v)? = wktChoice {return v}
      return SwiftProtobuf.Google_Protobuf_Int64Value()
    }
    set {wktChoice = .i64WVal(newValue)}
  }

  var strwVal: SwiftProtobuf.Google_Protobuf_StringValue {
    get {
      if case .strwVal(let v)? = wktChoice {return v}
      return SwiftProtobuf.Google_Protobuf_StringValue()
    }
    set {wktChoice = .strwVal(newValue)}
  }

  var structVal: SwiftProtobuf.Google_Protobuf_Struct {
    get {
      if case .structVal(let v)? = wktChoice {return v}
      return SwiftProtobuf.Google_Protobuf_Struct()
    }
    set {wktChoice = .structVal(newValue)}
  }

  var boolwVal: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {
      if case .boolwVal(let v)? = wktChoice {return v}
      return SwiftProtobuf.Google_Protobuf_BoolValue()
    }
    set {wktChoice = .boolwVal(newValue)}
  }

  var tag: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_WktChoice: Equatable, Sendable {
    case tsVal(SwiftProtobuf.Google_Protobuf_Timestamp)
    case i64WVal(SwiftProtobuf.Google_Protobuf_Int64Value)
    case strwVal(SwiftProtobuf.Google_Protobuf_StringValue)
    case structVal(SwiftProtobuf.Google_Protobuf_Struct)
    case boolwVal(SwiftProtobuf.Google_Protobuf_BoolValue)

  }

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_OneofScalars: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OneofScalars"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}double_val\0\u{3}float_val\0\u{3}int32_val\0\u{3}int64_val\0\u{3}uint32_val\0\u{3}uint64_val\0\u{3}bool_val\0\u{3}string_val\0\u{3}bytes_val\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .doubleVal(v)
        }
      }()
      case 2: try {
        var v: Float?
        try decoder.decodeSingularFloatField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .floatVal(v)
        }
      }()
      case 3: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .int32Val(v)
        }
      }()
      case 4: try {
        var v: Int64?
        try decoder.decodeSingularInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .int64Val(v)
        }
      }()
      case 5: try {
        var v: UInt32?
        try decoder.decodeSingularUInt32Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .uint32Val(v)
        }
      }()
      case 6: try {
        var v: UInt64?
        try decoder.decodeSingularUInt64Field(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .uint64Val(v)
        }
      }()
      case 7: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .boolVal(v)
        }
      }()
      case 8: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .stringVal(v)
        }
      }()
      case 9: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.value != nil {try decoder.handleConflictingOneOf()}
          self.value = .bytesVal(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.value {
    case .doubleVal?: try {
      guard case .doubleVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    }()
    case .floatVal?: try {
      guard case .floatVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    }()
    case .int32Val?: try {
      guard case .int32Val(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    }()
    case .int64Val?: try {
      guard case .int64Val(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 4)
    }()
    case .uint32Val?: try {
      guard case .uint32Val(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    }()
    case .uint64Val?: try {
      guard case .uint64Val(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 6)
    }()
    case .boolVal?: try {
      guard case .boolVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 7)
    }()
    case .stringVal?: try {
      guard case .stringVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 8)
    }()
    case .bytesVal?: try {
      guard case .bytesVal(let v)? = self.value else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 9)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_OneofScalars, rhs: Testcompat_OneofScalars) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_OneofComplex: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OneofComplex"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}int_val\0\u{3}string_val\0\u{3}msg_val\0\u{3}bytes_val\0\u{3}enum_val\0\u{3}simple_val\0\u{2}\u{4}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .intVal(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .stringVal(v)
        }
      }()
      case 3: try {
        var v: Testcompat_ScalarMessage?
        var hadOneofValue = false
        if let current = self.choice {
          hadOneofValue = true
          if case .msgVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.choice = .msgVal(v)
        }
      }()
      case 4: try {
        var v: Data?
        try decoder.decodeSingularBytesField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .bytesVal(v)
        }
      }()
      case 5: try {
        var v: Testcompat_Status?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .enumVal(v)
        }
      }()
      case 6: try {
        var v: Testcompat_SimpleMessage?
        var hadOneofValue = false
        if let current = self.choice {
          hadOneofValue = true
          if case .simpleVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.choice = .simpleVal(v)
        }
      }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.choice {
    case .intVal?: try {
      guard case .intVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    }()
    case .stringVal?: try {
      guard case .stringVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case .msgVal?: try {
      guard case .msgVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .bytesVal?: try {
      guard case .bytesVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularBytesField(value: v, fieldNumber: 4)
    }()
    case .enumVal?: try {
      guard case .enumVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 5)
    }()
    case .simpleVal?: try {
      guard case .simpleVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
    }()
    case nil: break
    }
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_OneofComplex, rhs: Testcompat_OneofComplex) -> Bool {
    if lhs.choice != rhs.choice {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MultiOneof: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MultiOneof"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}first_int\0\u{3}first_str\0\u{3}first_bool\0\u{3}second_dbl\0\u{3}second_bytes\0\u{3}second_enum\0\u{3}third_msg\0\u{3}third_scalar\0\u{2}\u{c}label\0")

  fileprivate class _StorageClass {
    var _firstChoice: Testcompat_MultiOneof.OneOf_FirstChoice?
    var _secondChoice: Testcompat_MultiOneof.OneOf_SecondChoice?
    var _thirdChoice: Testcompat_MultiOneof.OneOf_ThirdChoice?
    var _label: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _firstChoice = source._firstChoice
      _secondChoice = source._secondChoice
      _thirdChoice = source._thirdChoice
      _label = source._label
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try {
          var v: Int32?
          try decoder.decodeSingularInt32Field(value: &v)
          if let v = v {
            if _storage._firstChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._firstChoice = .firstInt(v)
          }
        }()
        case 2: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._firstChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._firstChoice = .firstStr(v)
          }
        }()
        case 3: try {
          var v: Bool?
          try decoder.decodeSingularBoolField(value: &v)
          if let v = v {
            if _storage._firstChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._firstChoice = .firstBool(v)
          }
        }()
        case 4: try {
          var v: Double?
          try decoder.decodeSingularDoubleField(value: &v)
          if let v = v {
            if _storage._secondChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._secondChoice = .secondDbl(v)
          }
        }()
        case 5: try {
          var v: Data?
          try decoder.decodeSingularBytesField(value: &v)
          if let v = v {
            if _storage._secondChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._secondChoice = .secondBytes(v)
          }
        }()
        case 6: try {
          var v: Testcompat_Status?
          try decoder.decodeSingularEnumField(value: &v)
          if let v = v {
            if _storage._secondChoice != nil {try decoder.handleConflictingOneOf()}
            _storage._secondChoice = .secondEnum(v)
          }
        }()
        case 7: try {
          var v: Testcompat_SimpleMessage?
          var hadOneofValue = false
          if let current = _storage._thirdChoice {
            hadOneofValue = true
            if case .thirdMsg(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._thirdChoice = .thirdMsg(v)
          }
        }()
        case 8: try {
          var v: Testcompat_ScalarMessage?
          var hadOneofValue = false
          if let current = _storage._thirdChoice {
            hadOneofValue = true
            if case .thirdScalar(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._thirdChoice = .thirdScalar(v)
          }
        }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._label) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      switch _storage._firstChoice {
      case .firstInt?: try {
        guard case .firstInt(let v)? = _storage._firstChoice else { preconditionFailure() }
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
      }()
      case .firstStr?: try {
        guard case .firstStr(let v)? = _storage._firstChoice else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 2)
      }()
      case .firstBool?: try {
        guard case .firstBool(let v)? = _storage._firstChoice else { preconditionFailure() }
        try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
      }()
      case nil: break
      }
      switch _storage._secondChoice {
      case .secondDbl?: try {
        guard case .secondDbl(let v)? = _storage._secondChoice else { preconditionFailure() }
        try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
      }()
      case .secondBytes?: try {
        guard case .secondBytes(let v)? = _storage._secondChoice else { preconditionFailure() }
        try visitor.visitSingularBytesField(value: v, fieldNumber: 5)
      }()
      case .secondEnum?: try {
        guard case .secondEnum(let v)? = _storage._secondChoice else { preconditionFailure() }
        try visitor.visitSingularEnumField(value: v, fieldNumber: 6)
      }()
      case nil: break
      }
      switch _storage._thirdChoice {
      case .thirdMsg?: try {
        guard case .thirdMsg(let v)? = _storage._thirdChoice else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      }()
      case .thirdScalar?: try {
        guard case .thirdScalar(let v)? = _storage._thirdChoice else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      }()
      case nil: break
      }
      if !_storage._label.isEmpty {
        try visitor.visitSingularStringField(value: _storage._label, fieldNumber: 20)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MultiOneof, rhs: Testcompat_MultiOneof) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._firstChoice != rhs_storage._firstChoice {return false}
        if _storage._secondChoice != rhs_storage._secondChoice {return false}
        if _storage._thirdChoice != rhs_storage._thirdChoice {return false}
        if _storage._label != rhs_storage._label {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_OneofWKT: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OneofWKT"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ts_val\0\u{3}i64w_val\0\u{3}strw_val\0\u{3}struct_val\0\u{3}boolw_val\0\u{2}\u{5}tag\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_Timestamp?
        var hadOneofValue = false
        if let current = self.wktChoice {
          hadOneofValue = true
          if case .tsVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wktChoice = .tsVal(v)
        }
      }()
      case 2: try {
        var v: SwiftProtobuf.Google_Protobuf_Int64Value?
        var hadOneofValue = false
        if let current = self.wktChoice {
          hadOneofValue = true
          if case .i64WVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wktChoice = .i64WVal(v)
        }
      }()
      case 3: try {
        var v: SwiftProtobuf.Google_Protobuf_StringValue?
        var hadOneofValue = false
        if let current = self.wktChoice {
          hadOneofValue = true
          if case .strwVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wktChoice = .strwVal(v)
        }
      }()
      case 4: try {
        var v: SwiftProtobuf.Google_Protobuf_Struct?
        var hadOneofValue = false
        if let current = self.wktChoice {
          hadOneofValue = true
          if case .structVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wktChoice = .structVal(v)
        }
      }()
      case 5: try {
        var v: SwiftProtobuf.Google_Protobuf_BoolValue?
        var hadOneofValue = false
        if let current = self.wktChoice {
          hadOneofValue = true
          if case .boolwVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.wktChoice = .boolwVal(v)
        }
      }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.tag) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.wktChoice {
    case .tsVal?: try {
      guard case .tsVal(let v)? = self.wktChoice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    }()
    case .i64WVal?: try {
      guard case .i64WVal(let v)? = self.wktChoice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case .strwVal?: try {
      guard case .strwVal(let v)? = self.wktChoice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    }()
    case .structVal?: try {
      guard case .structVal(let v)? = self.wktChoice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case .boolwVal?: try {
      guard case .boolwVal(let v)? = self.wktChoice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    }()
    case nil: break
    }
    if self.tag != 0 {
      try visitor.visitSingularInt32Field(value: self.tag, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_OneofWKT, rhs: Testcompat_OneofWKT) -> Bool {
    if lhs.wktChoice != rhs.wktChoice {return false}
    if lhs.tag != rhs.tag {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
