// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: proto2_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// Proto2 enum
enum Testcompat2_Proto2Enum: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case p2Unspecified = 0
  case p2Alpha = 1
  case p2Beta = 2
  case p2Gamma = 3

  init() {
    self = .p2Unspecified
  }

}

/// Proto2 enum without zero value
enum Testcompat2_Proto2NoZero: Int, SwiftProtobuf.Enum, Swift.CaseIterable {
  case p2NzOne = 1
  case p2NzTwo = 2
  case p2NzThree = 3

  init() {
    self = .p2NzOne
  }

}

/// Basic proto2 with required and optional
struct Testcompat2_Proto2Basic: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var requiredString: String {
    get {return _requiredString ?? String()}
    set {_requiredString = newValue}
  }
  /// Returns true if `requiredString` has been explicitly set.
  var hasRequiredString: Bool {return self._requiredString != nil}
  /// Clears the value of `requiredString`. Subsequent reads from it will return its default value.
  mutating func clearRequiredString() {self._requiredString = nil}

  var requiredInt32: Int32 {
    get {return _requiredInt32 ?? 0}
    set {_requiredInt32 = newValue}
  }
  /// Returns true if `requiredInt32` has been explicitly set.
  var hasRequiredInt32: Bool {return self._requiredInt32 != nil}
  /// Clears the value of `requiredInt32`. Subsequent reads from it will return its default value.
  mutating func clearRequiredInt32() {self._requiredInt32 = nil}

  var optString: String {
    get {return _optString ?? String()}
    set {_optString = newValue}
  }
  /// Returns true if `optString` has been explicitly set.
  var hasOptString: Bool {return self._optString != nil}
  /// Clears the value of `optString`. Subsequent reads from it will return its default value.
  mutating func clearOptString() {self._optString = nil}

  var optInt32: Int32 {
    get {return _optInt32 ?? 0}
    set {_optInt32 = newValue}
  }
  /// Returns true if `optInt32` has been explicitly set.
  var hasOptInt32: Bool {return self._optInt32 != nil}
  /// Clears the value of `optInt32`. Subsequent reads from it will return its default value.
  mutating func clearOptInt32() {self._optInt32 = nil}

  var optBool: Bool {
    get {return _optBool ?? false}
    set {_optBool = newValue}
  }
  /// Returns true if `optBool` has been explicitly set.
  var hasOptBool: Bool {return self._optBool != nil}
  /// Clears the value of `optBool`. Subsequent reads from it will return its default value.
  mutating func clearOptBool() {self._optBool = nil}

  var optBytes: Data {
    get {return _optBytes ?? Data()}
    set {_optBytes = newValue}
  }
  /// Returns true if `optBytes` has been explicitly set.
  var hasOptBytes: Bool {return self._optBytes != nil}
  /// Clears the value of `optBytes`. Subsequent reads from it will return its default value.
  mutating func clearOptBytes() {self._optBytes = nil}

  var optDouble: Double {
    get {return _optDouble ?? 0}
    set {_optDouble = newValue}
  }
  /// Returns true if `optDouble` has been explicitly set.
  var hasOptDouble: Bool {return self._optDouble != nil}
  /// Clears the value of `optDouble`. Subsequent reads from it will return its default value.
  mutating func clearOptDouble() {self._optDouble = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _requiredString: String? = nil
  fileprivate var _requiredInt32: Int32? = nil
  fileprivate var _optString: String? = nil
  fileprivate var _optInt32: Int32? = nil
  fileprivate var _optBool: Bool? = nil
  fileprivate var _optBytes: Data? = nil
  fileprivate var _optDouble: Double? = nil
}

/// Proto2 with non-zero default values
struct Testcompat2_Proto2Defaults: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var count: Int32 {
    get {return _count ?? 42}
    set {_count = newValue}
  }
  /// Returns true if `count` has been explicitly set.
  var hasCount: Bool {return self._count != nil}
  /// Clears the value of `count`. Subsequent reads from it will return its default value.
  mutating func clearCount() {self._count = nil}

  var label: String {
    get {return _label ?? "hello"}
    set {_label = newValue}
  }
  /// Returns true if `label` has been explicitly set.
  var hasLabel: Bool {return self._label != nil}
  /// Clears the value of `label`. Subsequent reads from it will return its default value.
  mutating func clearLabel() {self._label = nil}

  var active: Bool {
    get {return _active ?? true}
    set {_active = newValue}
  }
  /// Returns true if `active` has been explicitly set.
  var hasActive: Bool {return self._active != nil}
  /// Clears the value of `active`. Subsequent reads from it will return its default value.
  mutating func clearActive() {self._active = nil}

  var rate: Double {
    get {return _rate ?? 3.14}
    set {_rate = newValue}
  }
  /// Returns true if `rate` has been explicitly set.
  var hasRate: Bool {return self._rate != nil}
  /// Clears the value of `rate`. Subsequent reads from it will return its default value.
  mutating func clearRate() {self._rate = nil}

  var ratio: Float {
    get {return _ratio ?? 0.5}
    set {_ratio = newValue}
  }
  /// Returns true if `ratio` has been explicitly set.
  var hasRatio: Bool {return self._ratio != nil}
  /// Clears the value of `ratio`. Subsequent reads from it will return its default value.
  mutating func clearRatio() {self._ratio = nil}

  var magic: Data {
    get {return _magic ?? Data([0, 1, 2])}
    set {_magic = newValue}
  }
  /// Returns true if `magic` has been explicitly set.
  var hasMagic: Bool {return self._magic != nil}
  /// Clears the value of `magic`. Subsequent reads from it will return its default value.
  mutating func clearMagic() {self._magic = nil}

  var kind: Testcompat2_Proto2Enum {
    get {return _kind ?? .p2Beta}
    set {_kind = newValue}
  }
  /// Returns true if `kind` has been explicitly set.
  var hasKind: Bool {return self._kind != nil}
  /// Clears the value of `kind`. Subsequent reads from it will return its default value.
  mutating func clearKind() {self._kind = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _count: Int32? = nil
  fileprivate var _label: String? = nil
  fileprivate var _active: Bool? = nil
  fileprivate var _rate: Double? = nil
  fileprivate var _ratio: Float? = nil
  fileprivate var _magic: Data? = nil
  fileprivate var _kind: Testcompat2_Proto2Enum? = nil
}

/// Proto2 with group
struct Testcompat2_Proto2WithGroup: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var id: Int32 {
    get {return _id ?? 0}
    set {_id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return self._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {self._id = nil}

  var myGroup: Testcompat2_Proto2WithGroup.MyGroup {
    get {return _myGroup ?? Testcompat2_Proto2WithGroup.MyGroup()}
    set {_myGroup = newValue}
  }
  /// Returns true if `myGroup` has been explicitly set.
  var hasMyGroup: Bool {return self._myGroup != nil}
  /// Clears the value of `myGroup`. Subsequent reads from it will return its default value.
  mutating func clearMyGroup() {self._myGroup = nil}

  var anotherGroup: Testcompat2_Proto2WithGroup.AnotherGroup {
    get {return _anotherGroup ?? Testcompat2_Proto2WithGroup.AnotherGroup()}
    set {_anotherGroup = newValue}
  }
  /// Returns true if `anotherGroup` has been explicitly set.
  var hasAnotherGroup: Bool {return self._anotherGroup != nil}
  /// Clears the value of `anotherGroup`. Subsequent reads from it will return its default value.
  mutating func clearAnotherGroup() {self._anotherGroup = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct MyGroup: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var name: String {
      get {return _name ?? String()}
      set {_name = newValue}
    }
    /// Returns true if `name` has been explicitly set.
    var hasName: Bool {return self._name != nil}
    /// Clears the value of `name`. Subsequent reads from it will return its default value.
    mutating func clearName() {self._name = nil}

    var value: Int32 {
      get {return _value ?? 0}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    var hasValue: Bool {return self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    mutating func clearValue() {self._value = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _name: String? = nil
    fileprivate var _value: Int32? = nil
  }

  struct AnotherGroup: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var flag: Bool {
      get {return _flag ?? false}
      set {_flag = newValue}
    }
    /// Returns true if `flag` has been explicitly set.
    var hasFlag: Bool {return self._flag != nil}
    /// Clears the value of `flag`. Subsequent reads from it will return its default value.
    mutating func clearFlag() {self._flag = nil}

    var detail: String {
      get {return _detail ?? String()}
      set {_detail = newValue}
    }
    /// Returns true if `detail` has been explicitly set.
    var hasDetail: Bool {return self._detail != nil}
    /// Clears the value of `detail`. Subsequent reads from it will return its default value.
    mutating func clearDetail() {self._detail = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _flag: Bool? = nil
    fileprivate var _detail: String? = nil
  }

  init() {}

  fileprivate var _id: Int32? = nil
  fileprivate var _myGroup: Testcompat2_Proto2WithGroup.MyGroup? = nil
  fileprivate var _anotherGroup: Testcompat2_Proto2WithGroup.AnotherGroup? = nil
}

/// Proto2 with extensions
struct Testcompat2_Proto2Extendable: SwiftProtobuf.ExtensibleMessage, Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var baseField: String {
    get {return _baseField ?? String()}
    set {_baseField = newValue}
  }
  /// Returns true if `baseField` has been explicitly set.
  var hasBaseField: Bool {return self._baseField != nil}
  /// Clears the value of `baseField`. Subsequent reads from it will return its default value.
  mutating func clearBaseField() {self._baseField = nil}

  var code: Int32 {
    get {return _code ?? 0}
    set {_code = newValue}
  }
  /// Returns true if `code` has been explicitly set.
  var hasCode: Bool {return self._code != nil}
  /// Clears the value of `code`. Subsequent reads from it will return its default value.
  mutating func clearCode() {self._code = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  var _protobuf_extensionFieldValues = SwiftProtobuf.ExtensionFieldValueSet()
  fileprivate var _baseField: String? = nil
  fileprivate var _code: Int32? = nil
}

/// Proto2 nested groups and complex structure
struct Testcompat2_Proto2Complex: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var title: String {
    get {return _title ?? String()}
    set {_title = newValue}
  }
  /// Returns true if `title` has been explicitly set.
  var hasTitle: Bool {return self._title != nil}
  /// Clears the value of `title`. Subsequent reads from it will return its default value.
  mutating func clearTitle() {self._title = nil}

  var version: Int32 {
    get {return _version ?? 0}
    set {_version = newValue}
  }
  /// Returns true if `version` has been explicitly set.
  var hasVersion: Bool {return self._version != nil}
  /// Clears the value of `version`. Subsequent reads from it will return its default value.
  mutating func clearVersion() {self._version = nil}

  var header: Testcompat2_Proto2Complex.Header {
    get {return _header ?? Testcompat2_Proto2Complex.Header()}
    set {_header = newValue}
  }
  /// Returns true if `header` has been explicitly set.
  var hasHeader: Bool {return self._header != nil}
  /// Clears the value of `header`. Subsequent reads from it will return its default value.
  mutating func clearHeader() {self._header = nil}

  var item: [Testcompat2_Proto2Complex.Item] = []

  var basic: Testcompat2_Proto2Basic {
    get {return _basic ?? Testcompat2_Proto2Basic()}
    set {_basic = newValue}
  }
  /// Returns true if `basic` has been explicitly set.
  var hasBasic: Bool {return self._basic != nil}
  /// Clears the value of `basic`. Subsequent reads from it will return its default value.
  mutating func clearBasic() {self._basic = nil}

  var items: [Testcompat2_Proto2Basic] = []

  var meta: Dictionary<String,String> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Header: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var key: String {
      get {return _key ?? String()}
      set {_key = newValue}
    }
    /// Returns true if `key` has been explicitly set.
    var hasKey: Bool {return self._key != nil}
    /// Clears the value of `key`. Subsequent reads from it will return its default value.
    mutating func clearKey() {self._key = nil}

    var value: String {
      get {return _value ?? String()}
      set {_value = newValue}
    }
    /// Returns true if `value` has been explicitly set.
    var hasValue: Bool {return self._value != nil}
    /// Clears the value of `value`. Subsequent reads from it will return its default value.
    mutating func clearValue() {self._value = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _key: String? = nil
    fileprivate var _value: String? = nil
  }

  struct Item: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var id: Int32 {
      get {return _id ?? 0}
      set {_id = newValue}
    }
    /// Returns true if `id` has been explicitly set.
    var hasID: Bool {return self._id != nil}
    /// Clears the value of `id`. Subsequent reads from it will return its default value.
    mutating func clearID() {self._id = nil}

    var label: String {
      get {return _label ?? String()}
      set {_label = newValue}
    }
    /// Returns true if `label` has been explicitly set.
    var hasLabel: Bool {return self._label != nil}
    /// Clears the value of `label`. Subsequent reads from it will return its default value.
    mutating func clearLabel() {self._label = nil}

    var kind: Testcompat2_Proto2Enum {
      get {return _kind ?? .p2Unspecified}
      set {_kind = newValue}
    }
    /// Returns true if `kind` has been explicitly set.
    var hasKind: Bool {return self._kind != nil}
    /// Clears the value of `kind`. Subsequent reads from it will return its default value.
    mutating func clearKind() {self._kind = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _id: Int32? = nil
    fileprivate var _label: String? = nil
    fileprivate var _kind: Testcompat2_Proto2Enum? = nil
  }

  init() {}

  fileprivate var _title: String? = nil
  fileprivate var _version: Int32? = nil
  fileprivate var _header: Testcompat2_Proto2Complex.Header? = nil
  fileprivate var _basic: Testcompat2_Proto2Basic? = nil
}

/// Proto2 with oneof (proto2 supports oneof too)
struct Testcompat2_Proto2Oneof: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var choice: Testcompat2_Proto2Oneof.OneOf_Choice? = nil

  var strVal: String {
    get {
      if case .strVal(let v)? = choice {return v}
      return String()
    }
    set {choice = .strVal(newValue)}
  }

  var intVal: Int32 {
    get {
      if case .intVal(let v)? = choice {return v}
      return 0
    }
    set {choice = .intVal(newValue)}
  }

  var boolVal: Bool {
    get {
      if case .boolVal(let v)? = choice {return v}
      return false
    }
    set {choice = .boolVal(newValue)}
  }

  var msgVal: Testcompat2_Proto2Basic {
    get {
      if case .msgVal(let v)? = choice {return v}
      return Testcompat2_Proto2Basic()
    }
    set {choice = .msgVal(newValue)}
  }

  var label: String {
    get {return _label ?? String()}
    set {_label = newValue}
  }
  /// Returns true if `label` has been explicitly set.
  var hasLabel: Bool {return self._label != nil}
  /// Clears the value of `label`. Subsequent reads from it will return its default value.
  mutating func clearLabel() {self._label = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Choice: Equatable, Sendable {
    case strVal(String)
    case intVal(Int32)
    case boolVal(Bool)
    case msgVal(Testcompat2_Proto2Basic)

    fileprivate var isInitialized: Bool {
      guard case .msgVal(let v) = self else {return true}
      return v.isInitialized
    }

  }

  init() {}

  fileprivate var _label: String? = nil
}

/// Proto2 with all features combined
struct Testcompat2_Proto2KitchenSink: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String {
    get {return _storage._name ?? String()}
    set {_uniqueStorage()._name = newValue}
  }
  /// Returns true if `name` has been explicitly set.
  var hasName: Bool {return _storage._name != nil}
  /// Clears the value of `name`. Subsequent reads from it will return its default value.
  mutating func clearName() {_uniqueStorage()._name = nil}

  var id: Int32 {
    get {return _storage._id ?? 0}
    set {_uniqueStorage()._id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  var hasID: Bool {return _storage._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  mutating func clearID() {_uniqueStorage()._id = nil}

  var status: Testcompat2_Proto2Enum {
    get {return _storage._status ?? .p2Unspecified}
    set {_uniqueStorage()._status = newValue}
  }
  /// Returns true if `status` has been explicitly set.
  var hasStatus: Bool {return _storage._status != nil}
  /// Clears the value of `status`. Subsequent reads from it will return its default value.
  mutating func clearStatus() {_uniqueStorage()._status = nil}

  var tags: [String] {
    get {return _storage._tags}
    set {_uniqueStorage()._tags = newValue}
  }

  var scores: Dictionary<String,Int32> {
    get {return _storage._scores}
    set {_uniqueStorage()._scores = newValue}
  }

  var detail: Testcompat2_Proto2KitchenSink.Detail {
    get {return _storage._detail ?? Testcompat2_Proto2KitchenSink.Detail()}
    set {_uniqueStorage()._detail = newValue}
  }
  /// Returns true if `detail` has been explicitly set.
  var hasDetail: Bool {return _storage._detail != nil}
  /// Clears the value of `detail`. Subsequent reads from it will return its default value.
  mutating func clearDetail() {_uniqueStorage()._detail = nil}

  var variant: OneOf_Variant? {
    get {return _storage._variant}
    set {_uniqueStorage()._variant = newValue}
  }

  var strVariant: String {
    get {
      if case .strVariant(let v)? = _storage._variant {return v}
      return String()
    }
    set {_uniqueStorage()._variant = .strVariant(newValue)}
  }

  var intVariant: Int32 {
    get {
      if case .intVariant(let v)? = _storage._variant {return v}
      return 0
    }
    set {_uniqueStorage()._variant = .intVariant(newValue)}
  }

  var nested: Testcompat2_Proto2Basic {
    get {return _storage._nested ?? Testcompat2_Proto2Basic()}
    set {_uniqueStorage()._nested = newValue}
  }
  /// Returns true if `nested` has been explicitly set.
  var hasNested: Bool {return _storage._nested != nil}
  /// Clears the value of `nested`. Subsequent reads from it will return its default value.
  mutating func clearNested() {_uniqueStorage()._nested = nil}

  var items: [Testcompat2_Proto2Basic] {
    get {return _storage._items}
    set {_uniqueStorage()._items = newValue}
  }

  var withDefaults: Testcompat2_Proto2Defaults {
    get {return _storage._withDefaults ?? Testcompat2_Proto2Defaults()}
    set {_uniqueStorage()._withDefaults = newValue}
  }
  /// Returns true if `withDefaults` has been explicitly set.
  var hasWithDefaults: Bool {return _storage._withDefaults != nil}
  /// Clears the value of `withDefaults`. Subsequent reads from it will return its default value.
  mutating func clearWithDefaults() {_uniqueStorage()._withDefaults = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Variant: Equatable, Sendable {
    case strVariant(String)
    case intVariant(Int32)

  }

  struct Detail: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var info: String {
      get {return _info ?? String()}
      set {_info = newValue}
    }
    /// Returns true if `info` has been explicitly set.
    var hasInfo: Bool {return self._info != nil}
    /// Clears the value of `info`. Subsequent reads from it will return its default value.
    mutating func clearInfo() {self._info = nil}

    var code: Int32 {
      get {return _code ?? 0}
      set {_code = newValue}
    }
    /// Returns true if `code` has been explicitly set.
    var hasCode: Bool {return self._code != nil}
    /// Clears the value of `code`. Subsequent reads from it will return its default value.
    mutating func clearCode() {self._code = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _info: String? = nil
    fileprivate var _code: Int32? = nil
  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Extension support defined in proto2_types.proto.

// MARK: - Extension Properties

// Swift Extensions on the extended Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension Testcompat2_Proto2Extendable {

  var Testcompat2_extName: String {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_name) ?? String()}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_name, value: newValue)}
  }
  /// Returns true if extension `Testcompat2_Extensions_ext_name`
  /// has been explicitly set.
  var hasTestcompat2_extName: Bool {
    return hasExtensionValue(ext: Testcompat2_Extensions_ext_name)
  }
  /// Clears the value of extension `Testcompat2_Extensions_ext_name`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTestcompat2_extName() {
    clearExtensionValue(ext: Testcompat2_Extensions_ext_name)
  }

  var Testcompat2_extCount: Int32 {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_count) ?? 0}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_count, value: newValue)}
  }
  /// Returns true if extension `Testcompat2_Extensions_ext_count`
  /// has been explicitly set.
  var hasTestcompat2_extCount: Bool {
    return hasExtensionValue(ext: Testcompat2_Extensions_ext_count)
  }
  /// Clears the value of extension `Testcompat2_Extensions_ext_count`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTestcompat2_extCount() {
    clearExtensionValue(ext: Testcompat2_Extensions_ext_count)
  }

  var Testcompat2_extFlag: Bool {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_flag) ?? false}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_flag, value: newValue)}
  }
  /// Returns true if extension `Testcompat2_Extensions_ext_flag`
  /// has been explicitly set.
  var hasTestcompat2_extFlag: Bool {
    return hasExtensionValue(ext: Testcompat2_Extensions_ext_flag)
  }
  /// Clears the value of extension `Testcompat2_Extensions_ext_flag`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTestcompat2_extFlag() {
    clearExtensionValue(ext: Testcompat2_Extensions_ext_flag)
  }

  var Testcompat2_extData: Data {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_data) ?? Data()}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_data, value: newValue)}
  }
  /// Returns true if extension `Testcompat2_Extensions_ext_data`
  /// has been explicitly set.
  var hasTestcompat2_extData: Bool {
    return hasExtensionValue(ext: Testcompat2_Extensions_ext_data)
  }
  /// Clears the value of extension `Testcompat2_Extensions_ext_data`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTestcompat2_extData() {
    clearExtensionValue(ext: Testcompat2_Extensions_ext_data)
  }

  var Testcompat2_extMsg: Testcompat2_Proto2Basic {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_msg) ?? Testcompat2_Proto2Basic()}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_msg, value: newValue)}
  }
  /// Returns true if extension `Testcompat2_Extensions_ext_msg`
  /// has been explicitly set.
  var hasTestcompat2_extMsg: Bool {
    return hasExtensionValue(ext: Testcompat2_Extensions_ext_msg)
  }
  /// Clears the value of extension `Testcompat2_Extensions_ext_msg`.
  /// Subsequent reads from it will return its default value.
  mutating func clearTestcompat2_extMsg() {
    clearExtensionValue(ext: Testcompat2_Extensions_ext_msg)
  }

  var Testcompat2_extTags: [String] {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_tags) ?? []}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_tags, value: newValue)}
  }

  var Testcompat2_extIds: [Int32] {
    get {return getExtensionValue(ext: Testcompat2_Extensions_ext_ids) ?? []}
    set {setExtensionValue(ext: Testcompat2_Extensions_ext_ids, value: newValue)}
  }

}

// MARK: - File's ExtensionMap: Testcompat2_Proto2Types_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Testcompat2_Proto2Types_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Testcompat2_Extensions_ext_name,
  Testcompat2_Extensions_ext_count,
  Testcompat2_Extensions_ext_flag,
  Testcompat2_Extensions_ext_data,
  Testcompat2_Extensions_ext_msg,
  Testcompat2_Extensions_ext_tags,
  Testcompat2_Extensions_ext_ids
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

let Testcompat2_Extensions_ext_name = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 100,
  fieldName: "testcompat2.ext_name"
)

let Testcompat2_Extensions_ext_count = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufInt32>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 101,
  fieldName: "testcompat2.ext_count"
)

let Testcompat2_Extensions_ext_flag = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufBool>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 102,
  fieldName: "testcompat2.ext_flag"
)

let Testcompat2_Extensions_ext_data = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufBytes>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 103,
  fieldName: "testcompat2.ext_data"
)

let Testcompat2_Extensions_ext_msg = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalMessageExtensionField<Testcompat2_Proto2Basic>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 104,
  fieldName: "testcompat2.ext_msg"
)

let Testcompat2_Extensions_ext_tags = SwiftProtobuf.MessageExtension<SwiftProtobuf.RepeatedExtensionField<SwiftProtobuf.ProtobufString>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 105,
  fieldName: "testcompat2.ext_tags"
)

let Testcompat2_Extensions_ext_ids = SwiftProtobuf.MessageExtension<SwiftProtobuf.RepeatedExtensionField<SwiftProtobuf.ProtobufInt32>, Testcompat2_Proto2Extendable>(
  _protobuf_fieldNumber: 106,
  fieldName: "testcompat2.ext_ids"
)

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat2"

extension Testcompat2_Proto2Enum: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0P2_UNSPECIFIED\0\u{1}P2_ALPHA\0\u{1}P2_BETA\0\u{1}P2_GAMMA\0")
}

extension Testcompat2_Proto2NoZero: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}P2NZ_ONE\0\u{1}P2NZ_TWO\0\u{1}P2NZ_THREE\0")
}

extension Testcompat2_Proto2Basic: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2Basic"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}required_string\0\u{3}required_int32\0\u{3}opt_string\0\u{3}opt_int32\0\u{3}opt_bool\0\u{3}opt_bytes\0\u{3}opt_double\0")

  public var isInitialized: Bool {
    if self._requiredString == nil {return false}
    if self._requiredInt32 == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._requiredString) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._requiredInt32) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self._optString) }()
      case 4: try { try decoder.decodeSingularInt32Field(value: &self._optInt32) }()
      case 5: try { try decoder.decodeSingularBoolField(value: &self._optBool) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._optBytes) }()
      case 7: try { try decoder.decodeSingularDoubleField(value: &self._optDouble) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._requiredString {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._requiredInt32 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._optString {
      try visitor.visitSingularStringField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._optInt32 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._optBool {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._optBytes {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._optDouble {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Basic, rhs: Testcompat2_Proto2Basic) -> Bool {
    if lhs._requiredString != rhs._requiredString {return false}
    if lhs._requiredInt32 != rhs._requiredInt32 {return false}
    if lhs._optString != rhs._optString {return false}
    if lhs._optInt32 != rhs._optInt32 {return false}
    if lhs._optBool != rhs._optBool {return false}
    if lhs._optBytes != rhs._optBytes {return false}
    if lhs._optDouble != rhs._optDouble {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2Defaults: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2Defaults"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}count\0\u{1}label\0\u{1}active\0\u{1}rate\0\u{1}ratio\0\u{1}magic\0\u{1}kind\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._count) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._label) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self._active) }()
      case 4: try { try decoder.decodeSingularDoubleField(value: &self._rate) }()
      case 5: try { try decoder.decodeSingularFloatField(value: &self._ratio) }()
      case 6: try { try decoder.decodeSingularBytesField(value: &self._magic) }()
      case 7: try { try decoder.decodeSingularEnumField(value: &self._kind) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._count {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._label {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._active {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._rate {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._ratio {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._magic {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._kind {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 7)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Defaults, rhs: Testcompat2_Proto2Defaults) -> Bool {
    if lhs._count != rhs._count {return false}
    if lhs._label != rhs._label {return false}
    if lhs._active != rhs._active {return false}
    if lhs._rate != rhs._rate {return false}
    if lhs._ratio != rhs._ratio {return false}
    if lhs._magic != rhs._magic {return false}
    if lhs._kind != rhs._kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2WithGroup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2WithGroup"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{7}MyGroup\0\u{7}AnotherGroup\0")

  public var isInitialized: Bool {
    if self._id == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._id) }()
      case 2: try { try decoder.decodeSingularGroupField(value: &self._myGroup) }()
      case 3: try { try decoder.decodeSingularGroupField(value: &self._anotherGroup) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._myGroup {
      try visitor.visitSingularGroupField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._anotherGroup {
      try visitor.visitSingularGroupField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2WithGroup, rhs: Testcompat2_Proto2WithGroup) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._myGroup != rhs._myGroup {return false}
    if lhs._anotherGroup != rhs._anotherGroup {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2WithGroup.MyGroup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat2_Proto2WithGroup.protoMessageName + ".MyGroup"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._name) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._name {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2WithGroup.MyGroup, rhs: Testcompat2_Proto2WithGroup.MyGroup) -> Bool {
    if lhs._name != rhs._name {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2WithGroup.AnotherGroup: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat2_Proto2WithGroup.protoMessageName + ".AnotherGroup"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}flag\0\u{1}detail\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularBoolField(value: &self._flag) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._detail) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._flag {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._detail {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2WithGroup.AnotherGroup, rhs: Testcompat2_Proto2WithGroup.AnotherGroup) -> Bool {
    if lhs._flag != rhs._flag {return false}
    if lhs._detail != rhs._detail {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2Extendable: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2Extendable"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}base_field\0\u{1}code\0")

  public var isInitialized: Bool {
    if !_protobuf_extensionFieldValues.isInitialized {return false}
    if self._baseField == nil {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._baseField) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._code) }()
      case 100..<300:
        try { try decoder.decodeExtensionField(values: &_protobuf_extensionFieldValues, messageType: Testcompat2_Proto2Extendable.self, fieldNumber: fieldNumber) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._baseField {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._code {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try visitor.visitExtensionFields(fields: _protobuf_extensionFieldValues, start: 100, end: 300)
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Extendable, rhs: Testcompat2_Proto2Extendable) -> Bool {
    if lhs._baseField != rhs._baseField {return false}
    if lhs._code != rhs._code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    if lhs._protobuf_extensionFieldValues != rhs._protobuf_extensionFieldValues {return false}
    return true
  }
}

extension Testcompat2_Proto2Complex: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2Complex"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}title\0\u{1}version\0\u{7}Header\0\u{7}Item\0\u{1}basic\0\u{1}items\0\u{1}meta\0")

  public var isInitialized: Bool {
    if self._title == nil {return false}
    if let v = self._basic, !v.isInitialized {return false}
    if !SwiftProtobuf.Internal.areAllInitialized(self.items) {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._title) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._version) }()
      case 3: try { try decoder.decodeSingularGroupField(value: &self._header) }()
      case 4: try { try decoder.decodeRepeatedGroupField(value: &self.item) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._basic) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.items) }()
      case 7: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: &self.meta) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._title {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._version {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._header {
      try visitor.visitSingularGroupField(value: v, fieldNumber: 3)
    } }()
    if !self.item.isEmpty {
      try visitor.visitRepeatedGroupField(value: self.item, fieldNumber: 4)
    }
    try { if let v = self._basic {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.items.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.items, fieldNumber: 6)
    }
    if !self.meta.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufString>.self, value: self.meta, fieldNumber: 7)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Complex, rhs: Testcompat2_Proto2Complex) -> Bool {
    if lhs._title != rhs._title {return false}
    if lhs._version != rhs._version {return false}
    if lhs._header != rhs._header {return false}
    if lhs.item != rhs.item {return false}
    if lhs._basic != rhs._basic {return false}
    if lhs.items != rhs.items {return false}
    if lhs.meta != rhs.meta {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2Complex.Header: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat2_Proto2Complex.protoMessageName + ".Header"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}key\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._key) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._value) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._key {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._value {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Complex.Header, rhs: Testcompat2_Proto2Complex.Header) -> Bool {
    if lhs._key != rhs._key {return false}
    if lhs._value != rhs._value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2Complex.Item: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat2_Proto2Complex.protoMessageName + ".Item"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}label\0\u{1}kind\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self._id) }()
      case 2: try { try decoder.decodeSingularStringField(value: &self._label) }()
      case 3: try { try decoder.decodeSingularEnumField(value: &self._kind) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._id {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._label {
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._kind {
      try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Complex.Item, rhs: Testcompat2_Proto2Complex.Item) -> Bool {
    if lhs._id != rhs._id {return false}
    if lhs._label != rhs._label {return false}
    if lhs._kind != rhs._kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2Oneof: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2Oneof"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}str_val\0\u{3}int_val\0\u{3}bool_val\0\u{3}msg_val\0\u{2}\u{6}label\0")

  public var isInitialized: Bool {
    if let v = self.choice, !v.isInitialized {return false}
    return true
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .strVal(v)
        }
      }()
      case 2: try {
        var v: Int32?
        try decoder.decodeSingularInt32Field(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .intVal(v)
        }
      }()
      case 3: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.choice != nil {try decoder.handleConflictingOneOf()}
          self.choice = .boolVal(v)
        }
      }()
      case 4: try {
        var v: Testcompat2_Proto2Basic?
        var hadOneofValue = false
        if let current = self.choice {
          hadOneofValue = true
          if case .msgVal(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.choice = .msgVal(v)
        }
      }()
      case 10: try { try decoder.decodeSingularStringField(value: &self._label) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.choice {
    case .strVal?: try {
      guard case .strVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    }()
    case .intVal?: try {
      guard case .intVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    }()
    case .boolVal?: try {
      guard case .boolVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 3)
    }()
    case .msgVal?: try {
      guard case .msgVal(let v)? = self.choice else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    }()
    case nil: break
    }
    try { if let v = self._label {
      try visitor.visitSingularStringField(value: v, fieldNumber: 10)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2Oneof, rhs: Testcompat2_Proto2Oneof) -> Bool {
    if lhs.choice != rhs.choice {return false}
    if lhs._label != rhs._label {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2KitchenSink: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto2KitchenSink"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}id\0\u{1}status\0\u{1}tags\0\u{1}scores\0\u{7}Detail\0\u{3}str_variant\0\u{3}int_variant\0\u{1}nested\0\u{1}items\0\u{3}with_defaults\0")

  fileprivate class _StorageClass {
    var _name: String? = nil
    var _id: Int32? = nil
    var _status: Testcompat2_Proto2Enum? = nil
    var _tags: [String] = []
    var _scores: Dictionary<String,Int32> = [:]
    var _detail: Testcompat2_Proto2KitchenSink.Detail? = nil
    var _variant: Testcompat2_Proto2KitchenSink.OneOf_Variant?
    var _nested: Testcompat2_Proto2Basic? = nil
    var _items: [Testcompat2_Proto2Basic] = []
    var _withDefaults: Testcompat2_Proto2Defaults? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _name = source._name
      _id = source._id
      _status = source._status
      _tags = source._tags
      _scores = source._scores
      _detail = source._detail
      _variant = source._variant
      _nested = source._nested
      _items = source._items
      _withDefaults = source._withDefaults
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public var isInitialized: Bool {
    return withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if _storage._name == nil {return false}
      if let v = _storage._nested, !v.isInitialized {return false}
      if !SwiftProtobuf.Internal.areAllInitialized(_storage._items) {return false}
      return true
    }
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 2: try { try decoder.decodeSingularInt32Field(value: &_storage._id) }()
        case 3: try { try decoder.decodeSingularEnumField(value: &_storage._status) }()
        case 4: try { try decoder.decodeRepeatedStringField(value: &_storage._tags) }()
        case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: &_storage._scores) }()
        case 6: try { try decoder.decodeSingularGroupField(value: &_storage._detail) }()
        case 7: try {
          var v: String?
          try decoder.decodeSingularStringField(value: &v)
          if let v = v {
            if _storage._variant != nil {try decoder.handleConflictingOneOf()}
            _storage._variant = .strVariant(v)
          }
        }()
        case 8: try {
          var v: Int32?
          try decoder.decodeSingularInt32Field(value: &v)
          if let v = v {
            if _storage._variant != nil {try decoder.handleConflictingOneOf()}
            _storage._variant = .intVariant(v)
          }
        }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._nested) }()
        case 10: try { try decoder.decodeRepeatedMessageField(value: &_storage._items) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._withDefaults) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._name {
        try visitor.visitSingularStringField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._id {
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._status {
        try visitor.visitSingularEnumField(value: v, fieldNumber: 3)
      } }()
      if !_storage._tags.isEmpty {
        try visitor.visitRepeatedStringField(value: _storage._tags, fieldNumber: 4)
      }
      if !_storage._scores.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.ProtobufInt32>.self, value: _storage._scores, fieldNumber: 5)
      }
      try { if let v = _storage._detail {
        try visitor.visitSingularGroupField(value: v, fieldNumber: 6)
      } }()
      switch _storage._variant {
      case .strVariant?: try {
        guard case .strVariant(let v)? = _storage._variant else { preconditionFailure() }
        try visitor.visitSingularStringField(value: v, fieldNumber: 7)
      }()
      case .intVariant?: try {
        guard case .intVariant(let v)? = _storage._variant else { preconditionFailure() }
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 8)
      }()
      case nil: break
      }
      try { if let v = _storage._nested {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      if !_storage._items.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._items, fieldNumber: 10)
      }
      try { if let v = _storage._withDefaults {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2KitchenSink, rhs: Testcompat2_Proto2KitchenSink) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._name != rhs_storage._name {return false}
        if _storage._id != rhs_storage._id {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._tags != rhs_storage._tags {return false}
        if _storage._scores != rhs_storage._scores {return false}
        if _storage._detail != rhs_storage._detail {return false}
        if _storage._variant != rhs_storage._variant {return false}
        if _storage._nested != rhs_storage._nested {return false}
        if _storage._items != rhs_storage._items {return false}
        if _storage._withDefaults != rhs_storage._withDefaults {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat2_Proto2KitchenSink.Detail: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat2_Proto2KitchenSink.protoMessageName + ".Detail"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}info\0\u{1}code\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self._info) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self._code) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._info {
      try visitor.visitSingularStringField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._code {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat2_Proto2KitchenSink.Detail, rhs: Testcompat2_Proto2KitchenSink.Detail) -> Bool {
    if lhs._info != rhs._info {return false}
    if lhs._code != rhs._code {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
