// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: realworld_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// --- Enum with non-sequential values (bitmask pattern) ---
enum Testcompat_IntentFlag: SwiftProtobuf.Enum, Swift.CaseIterable {
  typealias RawValue = Int
  case intentDefault // = 0
  case intentInformational // = 1
  case intentNavigational // = 2

  /// gap: 3 skipped
  case intentTransactional // = 4

  /// power-of-2
  case intentCommercial // = 8
  case UNRECOGNIZED(Int)

  init() {
    self = .intentDefault
  }

  init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .intentDefault
    case 1: self = .intentInformational
    case 2: self = .intentNavigational
    case 4: self = .intentTransactional
    case 8: self = .intentCommercial
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  var rawValue: Int {
    switch self {
    case .intentDefault: return 0
    case .intentInformational: return 1
    case .intentNavigational: return 2
    case .intentTransactional: return 4
    case .intentCommercial: return 8
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  static let allCases: [Testcompat_IntentFlag] = [
    .intentDefault,
    .intentInformational,
    .intentNavigational,
    .intentTransactional,
    .intentCommercial,
  ]

}

/// --- Nullable pattern: oneof with NullValue ---
/// Very common in production: nullable scalars via oneof
struct Testcompat_NullableUint32: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Testcompat_NullableUint32.OneOf_Kind? = nil

  var nullVal: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullVal(let v)? = kind {return v}
      return .nullValue
    }
    set {kind = .nullVal(newValue)}
  }

  var value: UInt32 {
    get {
      if case .value(let v)? = kind {return v}
      return 0
    }
    set {kind = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Kind: Equatable, Sendable {
    case nullVal(SwiftProtobuf.Google_Protobuf_NullValue)
    case value(UInt32)

  }

  init() {}
}

struct Testcompat_NullableDouble: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Testcompat_NullableDouble.OneOf_Kind? = nil

  var nullVal: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullVal(let v)? = kind {return v}
      return .nullValue
    }
    set {kind = .nullVal(newValue)}
  }

  var value: Double {
    get {
      if case .value(let v)? = kind {return v}
      return 0
    }
    set {kind = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Kind: Equatable, Sendable {
    case nullVal(SwiftProtobuf.Google_Protobuf_NullValue)
    case value(Double)

  }

  init() {}
}

struct Testcompat_NullableBool: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Testcompat_NullableBool.OneOf_Kind? = nil

  var nullVal: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullVal(let v)? = kind {return v}
      return .nullValue
    }
    set {kind = .nullVal(newValue)}
  }

  var value: Bool {
    get {
      if case .value(let v)? = kind {return v}
      return false
    }
    set {kind = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Kind: Equatable, Sendable {
    case nullVal(SwiftProtobuf.Google_Protobuf_NullValue)
    case value(Bool)

  }

  init() {}
}

struct Testcompat_NullableString: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Testcompat_NullableString.OneOf_Kind? = nil

  var nullVal: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullVal(let v)? = kind {return v}
      return .nullValue
    }
    set {kind = .nullVal(newValue)}
  }

  var value: String {
    get {
      if case .value(let v)? = kind {return v}
      return String()
    }
    set {kind = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Kind: Equatable, Sendable {
    case nullVal(SwiftProtobuf.Google_Protobuf_NullValue)
    case value(String)

  }

  init() {}
}

struct Testcompat_NullableMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var kind: Testcompat_NullableMessage.OneOf_Kind? = nil

  var nullVal: SwiftProtobuf.Google_Protobuf_NullValue {
    get {
      if case .nullVal(let v)? = kind {return v}
      return .nullValue
    }
    set {kind = .nullVal(newValue)}
  }

  var value: Testcompat_SimpleMessage {
    get {
      if case .value(let v)? = kind {return v}
      return Testcompat_SimpleMessage()
    }
    set {kind = .value(newValue)}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_Kind: Equatable, Sendable {
    case nullVal(SwiftProtobuf.Google_Protobuf_NullValue)
    case value(Testcompat_SimpleMessage)

  }

  init() {}
}

/// Message using nullable fields
struct Testcompat_WithNullables: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var count: Testcompat_NullableUint32 {
    get {return _count ?? Testcompat_NullableUint32()}
    set {_count = newValue}
  }
  /// Returns true if `count` has been explicitly set.
  var hasCount: Bool {return self._count != nil}
  /// Clears the value of `count`. Subsequent reads from it will return its default value.
  mutating func clearCount() {self._count = nil}

  var rate: Testcompat_NullableDouble {
    get {return _rate ?? Testcompat_NullableDouble()}
    set {_rate = newValue}
  }
  /// Returns true if `rate` has been explicitly set.
  var hasRate: Bool {return self._rate != nil}
  /// Clears the value of `rate`. Subsequent reads from it will return its default value.
  mutating func clearRate() {self._rate = nil}

  var active: Testcompat_NullableBool {
    get {return _active ?? Testcompat_NullableBool()}
    set {_active = newValue}
  }
  /// Returns true if `active` has been explicitly set.
  var hasActive: Bool {return self._active != nil}
  /// Clears the value of `active`. Subsequent reads from it will return its default value.
  mutating func clearActive() {self._active = nil}

  var label: Testcompat_NullableString {
    get {return _label ?? Testcompat_NullableString()}
    set {_label = newValue}
  }
  /// Returns true if `label` has been explicitly set.
  var hasLabel: Bool {return self._label != nil}
  /// Clears the value of `label`. Subsequent reads from it will return its default value.
  mutating func clearLabel() {self._label = nil}

  var detail: Testcompat_NullableMessage {
    get {return _detail ?? Testcompat_NullableMessage()}
    set {_detail = newValue}
  }
  /// Returns true if `detail` has been explicitly set.
  var hasDetail: Bool {return self._detail != nil}
  /// Clears the value of `detail`. Subsequent reads from it will return its default value.
  mutating func clearDetail() {self._detail = nil}

  var name: String = String()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _count: Testcompat_NullableUint32? = nil
  fileprivate var _rate: Testcompat_NullableDouble? = nil
  fileprivate var _active: Testcompat_NullableBool? = nil
  fileprivate var _label: Testcompat_NullableString? = nil
  fileprivate var _detail: Testcompat_NullableMessage? = nil
}

/// --- Non-sequential field numbers + large numbers ---
struct Testcompat_NonSequentialFields: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var code: Int32 = 0

  /// gap: 3-9 skipped
  var description_p: String = String()

  /// gap: 11-49 skipped
  var bigNumber: Int64 = 0

  /// gap: 51-99 skipped
  var flag: Bool = false

  var createdAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _createdAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_createdAt = newValue}
  }
  /// Returns true if `createdAt` has been explicitly set.
  var hasCreatedAt: Bool {return self._createdAt != nil}
  /// Clears the value of `createdAt`. Subsequent reads from it will return its default value.
  mutating func clearCreatedAt() {self._createdAt = nil}

  var updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _updatedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_updatedAt = newValue}
  }
  /// Returns true if `updatedAt` has been explicitly set.
  var hasUpdatedAt: Bool {return self._updatedAt != nil}
  /// Clears the value of `updatedAt`. Subsequent reads from it will return its default value.
  mutating func clearUpdatedAt() {self._updatedAt = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _createdAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
  fileprivate var _updatedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

/// --- Reserved fields ---
struct Testcompat_WithReserved: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var name: String = String()

  var version: Int32 = 0

  var status: String = String()

  var priority: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// --- Deeply nested sibling definitions (real-world report pattern) ---
struct Testcompat_ReportResponse: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var total: UInt32 = 0

  var limit: UInt32 = 0

  var offset: UInt32 = 0

  var keywords: [Testcompat_ReportResponse.Keyword] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Metrics: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var position: Int32 = 0

    var visibility: Float = 0

    var traffic: Float = 0

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Position: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var metrics: Testcompat_ReportResponse.Metrics {
      get {return _metrics ?? Testcompat_ReportResponse.Metrics()}
      set {_metrics = newValue}
    }
    /// Returns true if `metrics` has been explicitly set.
    var hasMetrics: Bool {return self._metrics != nil}
    /// Clears the value of `metrics`. Subsequent reads from it will return its default value.
    mutating func clearMetrics() {self._metrics = nil}

    var serpFeatures: [Testcompat_Status] = []

    var url: String = String()

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _metrics: Testcompat_ReportResponse.Metrics? = nil
  }

  struct CompetitorData: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var competitor: Testcompat_SimpleMessage {
      get {return _competitor ?? Testcompat_SimpleMessage()}
      set {_competitor = newValue}
    }
    /// Returns true if `competitor` has been explicitly set.
    var hasCompetitor: Bool {return self._competitor != nil}
    /// Clears the value of `competitor`. Subsequent reads from it will return its default value.
    mutating func clearCompetitor() {self._competitor = nil}

    var position: Testcompat_ReportResponse.Position {
      get {return _position ?? Testcompat_ReportResponse.Position()}
      set {_position = newValue}
    }
    /// Returns true if `position` has been explicitly set.
    var hasPosition: Bool {return self._position != nil}
    /// Clears the value of `position`. Subsequent reads from it will return its default value.
    mutating func clearPosition() {self._position = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _competitor: Testcompat_SimpleMessage? = nil
    fileprivate var _position: Testcompat_ReportResponse.Position? = nil
  }

  struct DateEntry: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var date: String = String()

    var isCrawled: Bool = false

    var competitors: [Testcompat_ReportResponse.CompetitorData] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}
  }

  struct Interval: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var begin: Testcompat_ReportResponse.DateEntry {
      get {return _begin ?? Testcompat_ReportResponse.DateEntry()}
      set {_begin = newValue}
    }
    /// Returns true if `begin` has been explicitly set.
    var hasBegin: Bool {return self._begin != nil}
    /// Clears the value of `begin`. Subsequent reads from it will return its default value.
    mutating func clearBegin() {self._begin = nil}

    var end: Testcompat_ReportResponse.DateEntry {
      get {return _end ?? Testcompat_ReportResponse.DateEntry()}
      set {_end = newValue}
    }
    /// Returns true if `end` has been explicitly set.
    var hasEnd: Bool {return self._end != nil}
    /// Clears the value of `end`. Subsequent reads from it will return its default value.
    mutating func clearEnd() {self._end = nil}

    var diff: [Testcompat_ReportResponse.CompetitorData] = []

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _begin: Testcompat_ReportResponse.DateEntry? = nil
    fileprivate var _end: Testcompat_ReportResponse.DateEntry? = nil
  }

  struct Keyword: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var keyword: String = String()

    var tags: [String] = []

    var cpc: Testcompat_NullableDouble {
      get {return _cpc ?? Testcompat_NullableDouble()}
      set {_cpc = newValue}
    }
    /// Returns true if `cpc` has been explicitly set.
    var hasCpc: Bool {return self._cpc != nil}
    /// Clears the value of `cpc`. Subsequent reads from it will return its default value.
    mutating func clearCpc() {self._cpc = nil}

    var volume: Testcompat_NullableUint32 {
      get {return _volume ?? Testcompat_NullableUint32()}
      set {_volume = newValue}
    }
    /// Returns true if `volume` has been explicitly set.
    var hasVolume: Bool {return self._volume != nil}
    /// Clears the value of `volume`. Subsequent reads from it will return its default value.
    mutating func clearVolume() {self._volume = nil}

    var serps: Testcompat_ReportResponse.Interval {
      get {return _serps ?? Testcompat_ReportResponse.Interval()}
      set {_serps = newValue}
    }
    /// Returns true if `serps` has been explicitly set.
    var hasSerps: Bool {return self._serps != nil}
    /// Clears the value of `serps`. Subsequent reads from it will return its default value.
    mutating func clearSerps() {self._serps = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _cpc: Testcompat_NullableDouble? = nil
    fileprivate var _volume: Testcompat_NullableUint32? = nil
    fileprivate var _serps: Testcompat_ReportResponse.Interval? = nil
  }

  init() {}
}

/// --- Duplicate message name across packages (tested via cross_file) ---
/// This DateValue is in package testcompat, while proto2_types.proto is in testcompat2.
/// Cross-file tests verify correct resolution.
struct Testcompat_DateValue: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var year: Int32 = 0

  var month: Int32 = 0

  var day: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// --- optional message fields in proto3 ---
struct Testcompat_Proto3OptionalMessages: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var optSimple: Testcompat_SimpleMessage {
    get {return _storage._optSimple ?? Testcompat_SimpleMessage()}
    set {_uniqueStorage()._optSimple = newValue}
  }
  /// Returns true if `optSimple` has been explicitly set.
  var hasOptSimple: Bool {return _storage._optSimple != nil}
  /// Clears the value of `optSimple`. Subsequent reads from it will return its default value.
  mutating func clearOptSimple() {_uniqueStorage()._optSimple = nil}

  var optScalar: Testcompat_ScalarMessage {
    get {return _storage._optScalar ?? Testcompat_ScalarMessage()}
    set {_uniqueStorage()._optScalar = newValue}
  }
  /// Returns true if `optScalar` has been explicitly set.
  var hasOptScalar: Bool {return _storage._optScalar != nil}
  /// Clears the value of `optScalar`. Subsequent reads from it will return its default value.
  mutating func clearOptScalar() {_uniqueStorage()._optScalar = nil}

  var optTs: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._optTs ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._optTs = newValue}
  }
  /// Returns true if `optTs` has been explicitly set.
  var hasOptTs: Bool {return _storage._optTs != nil}
  /// Clears the value of `optTs`. Subsequent reads from it will return its default value.
  mutating func clearOptTs() {_uniqueStorage()._optTs = nil}

  var optWrapper: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {return _storage._optWrapper ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._optWrapper = newValue}
  }
  /// Returns true if `optWrapper` has been explicitly set.
  var hasOptWrapper: Bool {return _storage._optWrapper != nil}
  /// Clears the value of `optWrapper`. Subsequent reads from it will return its default value.
  mutating func clearOptWrapper() {_uniqueStorage()._optWrapper = nil}

  /// implicit presence for comparison
  var plainSimple: Testcompat_SimpleMessage {
    get {return _storage._plainSimple ?? Testcompat_SimpleMessage()}
    set {_uniqueStorage()._plainSimple = newValue}
  }
  /// Returns true if `plainSimple` has been explicitly set.
  var hasPlainSimple: Bool {return _storage._plainSimple != nil}
  /// Clears the value of `plainSimple`. Subsequent reads from it will return its default value.
  mutating func clearPlainSimple() {_uniqueStorage()._plainSimple = nil}

  var label: String {
    get {return _storage._label}
    set {_uniqueStorage()._label = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// --- Message with enum with gaps + repeated of it ---
struct Testcompat_IntentHolder: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var intent: Testcompat_IntentFlag = .intentDefault

  var allIntents: [Testcompat_IntentFlag] = []

  var byName: Dictionary<String,Testcompat_IntentFlag> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_IntentFlag: SwiftProtobuf._ProtoNameProviding {
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0INTENT_DEFAULT\0\u{1}INTENT_INFORMATIONAL\0\u{1}INTENT_NAVIGATIONAL\0\u{2}\u{2}INTENT_TRANSACTIONAL\0\u{2}\u{4}INTENT_COMMERCIAL\0")
}

extension Testcompat_NullableUint32: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NullableUint32"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_val\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .nullVal(v)
        }
      }()
      case 2: try {
        var v: UInt32?
        try decoder.decodeSingularUInt32Field(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .nullVal?: try {
      guard case .nullVal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NullableUint32, rhs: Testcompat_NullableUint32) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_NullableDouble: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NullableDouble"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_val\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .nullVal(v)
        }
      }()
      case 2: try {
        var v: Double?
        try decoder.decodeSingularDoubleField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .nullVal?: try {
      guard case .nullVal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NullableDouble, rhs: Testcompat_NullableDouble) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_NullableBool: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NullableBool"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_val\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .nullVal(v)
        }
      }()
      case 2: try {
        var v: Bool?
        try decoder.decodeSingularBoolField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .nullVal?: try {
      guard case .nullVal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularBoolField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NullableBool, rhs: Testcompat_NullableBool) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_NullableString: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NullableString"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_val\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .nullVal(v)
        }
      }()
      case 2: try {
        var v: String?
        try decoder.decodeSingularStringField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .nullVal?: try {
      guard case .nullVal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularStringField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NullableString, rhs: Testcompat_NullableString) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_NullableMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NullableMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}null_val\0\u{1}value\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try {
        var v: SwiftProtobuf.Google_Protobuf_NullValue?
        try decoder.decodeSingularEnumField(value: &v)
        if let v = v {
          if self.kind != nil {try decoder.handleConflictingOneOf()}
          self.kind = .nullVal(v)
        }
      }()
      case 2: try {
        var v: Testcompat_SimpleMessage?
        var hadOneofValue = false
        if let current = self.kind {
          hadOneofValue = true
          if case .value(let m) = current {v = m}
        }
        try decoder.decodeSingularMessageField(value: &v)
        if let v = v {
          if hadOneofValue {try decoder.handleConflictingOneOf()}
          self.kind = .value(v)
        }
      }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    switch self.kind {
    case .nullVal?: try {
      guard case .nullVal(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularEnumField(value: v, fieldNumber: 1)
    }()
    case .value?: try {
      guard case .value(let v)? = self.kind else { preconditionFailure() }
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    }()
    case nil: break
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NullableMessage, rhs: Testcompat_NullableMessage) -> Bool {
    if lhs.kind != rhs.kind {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WithNullables: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WithNullables"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}count\0\u{1}rate\0\u{1}active\0\u{1}label\0\u{1}detail\0\u{2}\u{5}name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._count) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._rate) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._active) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._label) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._detail) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.name) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._count {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._rate {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._active {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._label {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._detail {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WithNullables, rhs: Testcompat_WithNullables) -> Bool {
    if lhs._count != rhs._count {return false}
    if lhs._rate != rhs._rate {return false}
    if lhs._active != rhs._active {return false}
    if lhs._label != rhs._label {return false}
    if lhs._detail != rhs._detail {return false}
    if lhs.name != rhs.name {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_NonSequentialFields: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".NonSequentialFields"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{1}code\0\u{2}\u{8}description\0\u{4}(big_number\0\u{4}\u{15}created_at\0\u{3}updated_at\0\u{2}\u{1c}flag\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.code) }()
      case 10: try { try decoder.decodeSingularStringField(value: &self.description_p) }()
      case 50: try { try decoder.decodeSingularInt64Field(value: &self.bigNumber) }()
      case 71: try { try decoder.decodeSingularMessageField(value: &self._createdAt) }()
      case 72: try { try decoder.decodeSingularMessageField(value: &self._updatedAt) }()
      case 100: try { try decoder.decodeSingularBoolField(value: &self.flag) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.code != 0 {
      try visitor.visitSingularInt32Field(value: self.code, fieldNumber: 2)
    }
    if !self.description_p.isEmpty {
      try visitor.visitSingularStringField(value: self.description_p, fieldNumber: 10)
    }
    if self.bigNumber != 0 {
      try visitor.visitSingularInt64Field(value: self.bigNumber, fieldNumber: 50)
    }
    try { if let v = self._createdAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 71)
    } }()
    try { if let v = self._updatedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 72)
    } }()
    if self.flag != false {
      try visitor.visitSingularBoolField(value: self.flag, fieldNumber: 100)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_NonSequentialFields, rhs: Testcompat_NonSequentialFields) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.code != rhs.code {return false}
    if lhs.description_p != rhs.description_p {return false}
    if lhs.bigNumber != rhs.bigNumber {return false}
    if lhs.flag != rhs.flag {return false}
    if lhs._createdAt != rhs._createdAt {return false}
    if lhs._updatedAt != rhs._updatedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WithReserved: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WithReserved"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}name\0\u{2}\u{4}version\0\u{2}\u{4}status\0\u{1}priority\0\u{b}old_field\0\u{b}deprecated_field\0\u{c}\u{2}\u{1}\u{c}\u{3}\u{1}\u{c}\u{4}\u{1}\u{c}\u{6}\u{3}")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.name) }()
      case 5: try { try decoder.decodeSingularInt32Field(value: &self.version) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.status) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.priority) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.name.isEmpty {
      try visitor.visitSingularStringField(value: self.name, fieldNumber: 1)
    }
    if self.version != 0 {
      try visitor.visitSingularInt32Field(value: self.version, fieldNumber: 5)
    }
    if !self.status.isEmpty {
      try visitor.visitSingularStringField(value: self.status, fieldNumber: 9)
    }
    if self.priority != 0 {
      try visitor.visitSingularInt32Field(value: self.priority, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WithReserved, rhs: Testcompat_WithReserved) -> Bool {
    if lhs.name != rhs.name {return false}
    if lhs.version != rhs.version {return false}
    if lhs.status != rhs.status {return false}
    if lhs.priority != rhs.priority {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ReportResponse"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}total\0\u{1}limit\0\u{1}offset\0\u{1}keywords\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularUInt32Field(value: &self.total) }()
      case 2: try { try decoder.decodeSingularUInt32Field(value: &self.limit) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.offset) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.keywords) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.total != 0 {
      try visitor.visitSingularUInt32Field(value: self.total, fieldNumber: 1)
    }
    if self.limit != 0 {
      try visitor.visitSingularUInt32Field(value: self.limit, fieldNumber: 2)
    }
    if self.offset != 0 {
      try visitor.visitSingularUInt32Field(value: self.offset, fieldNumber: 3)
    }
    if !self.keywords.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.keywords, fieldNumber: 4)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse, rhs: Testcompat_ReportResponse) -> Bool {
    if lhs.total != rhs.total {return false}
    if lhs.limit != rhs.limit {return false}
    if lhs.offset != rhs.offset {return false}
    if lhs.keywords != rhs.keywords {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.Metrics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".Metrics"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}position\0\u{1}visibility\0\u{1}traffic\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.position) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.visibility) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.traffic) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.position != 0 {
      try visitor.visitSingularInt32Field(value: self.position, fieldNumber: 1)
    }
    if self.visibility.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.visibility, fieldNumber: 2)
    }
    if self.traffic.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.traffic, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.Metrics, rhs: Testcompat_ReportResponse.Metrics) -> Bool {
    if lhs.position != rhs.position {return false}
    if lhs.visibility != rhs.visibility {return false}
    if lhs.traffic != rhs.traffic {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.Position: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".Position"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}metrics\0\u{3}serp_features\0\u{1}url\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._metrics) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.serpFeatures) }()
      case 3: try { try decoder.decodeSingularStringField(value: &self.url) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._metrics {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.serpFeatures.isEmpty {
      try visitor.visitPackedEnumField(value: self.serpFeatures, fieldNumber: 2)
    }
    if !self.url.isEmpty {
      try visitor.visitSingularStringField(value: self.url, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.Position, rhs: Testcompat_ReportResponse.Position) -> Bool {
    if lhs._metrics != rhs._metrics {return false}
    if lhs.serpFeatures != rhs.serpFeatures {return false}
    if lhs.url != rhs.url {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.CompetitorData: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".CompetitorData"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}competitor\0\u{1}position\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._competitor) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._position) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._competitor {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._position {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.CompetitorData, rhs: Testcompat_ReportResponse.CompetitorData) -> Bool {
    if lhs._competitor != rhs._competitor {return false}
    if lhs._position != rhs._position {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.DateEntry: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".DateEntry"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}date\0\u{3}is_crawled\0\u{1}competitors\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.date) }()
      case 2: try { try decoder.decodeSingularBoolField(value: &self.isCrawled) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.competitors) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.date.isEmpty {
      try visitor.visitSingularStringField(value: self.date, fieldNumber: 1)
    }
    if self.isCrawled != false {
      try visitor.visitSingularBoolField(value: self.isCrawled, fieldNumber: 2)
    }
    if !self.competitors.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.competitors, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.DateEntry, rhs: Testcompat_ReportResponse.DateEntry) -> Bool {
    if lhs.date != rhs.date {return false}
    if lhs.isCrawled != rhs.isCrawled {return false}
    if lhs.competitors != rhs.competitors {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.Interval: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".Interval"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}begin\0\u{1}end\0\u{1}diff\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._begin) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._end) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.diff) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._begin {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._end {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    if !self.diff.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.diff, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.Interval, rhs: Testcompat_ReportResponse.Interval) -> Bool {
    if lhs._begin != rhs._begin {return false}
    if lhs._end != rhs._end {return false}
    if lhs.diff != rhs.diff {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_ReportResponse.Keyword: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_ReportResponse.protoMessageName + ".Keyword"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}keyword\0\u{1}tags\0\u{1}cpc\0\u{1}volume\0\u{1}serps\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.keyword) }()
      case 2: try { try decoder.decodeRepeatedStringField(value: &self.tags) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._cpc) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._volume) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._serps) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if !self.keyword.isEmpty {
      try visitor.visitSingularStringField(value: self.keyword, fieldNumber: 1)
    }
    if !self.tags.isEmpty {
      try visitor.visitRepeatedStringField(value: self.tags, fieldNumber: 2)
    }
    try { if let v = self._cpc {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._volume {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._serps {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ReportResponse.Keyword, rhs: Testcompat_ReportResponse.Keyword) -> Bool {
    if lhs.keyword != rhs.keyword {return false}
    if lhs.tags != rhs.tags {return false}
    if lhs._cpc != rhs._cpc {return false}
    if lhs._volume != rhs._volume {return false}
    if lhs._serps != rhs._serps {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_DateValue: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".DateValue"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}year\0\u{1}month\0\u{1}day\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularInt32Field(value: &self.year) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.month) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.day) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.year != 0 {
      try visitor.visitSingularInt32Field(value: self.year, fieldNumber: 1)
    }
    if self.month != 0 {
      try visitor.visitSingularInt32Field(value: self.month, fieldNumber: 2)
    }
    if self.day != 0 {
      try visitor.visitSingularInt32Field(value: self.day, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_DateValue, rhs: Testcompat_DateValue) -> Bool {
    if lhs.year != rhs.year {return false}
    if lhs.month != rhs.month {return false}
    if lhs.day != rhs.day {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_Proto3OptionalMessages: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".Proto3OptionalMessages"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}opt_simple\0\u{3}opt_scalar\0\u{3}opt_ts\0\u{3}opt_wrapper\0\u{3}plain_simple\0\u{2}\u{5}label\0")

  fileprivate class _StorageClass {
    var _optSimple: Testcompat_SimpleMessage? = nil
    var _optScalar: Testcompat_ScalarMessage? = nil
    var _optTs: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _optWrapper: SwiftProtobuf.Google_Protobuf_Int64Value? = nil
    var _plainSimple: Testcompat_SimpleMessage? = nil
    var _label: String = String()

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _optSimple = source._optSimple
      _optScalar = source._optScalar
      _optTs = source._optTs
      _optWrapper = source._optWrapper
      _plainSimple = source._plainSimple
      _label = source._label
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._optSimple) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._optScalar) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._optTs) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._optWrapper) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._plainSimple) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._label) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._optSimple {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._optScalar {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._optTs {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._optWrapper {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._plainSimple {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if !_storage._label.isEmpty {
        try visitor.visitSingularStringField(value: _storage._label, fieldNumber: 10)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_Proto3OptionalMessages, rhs: Testcompat_Proto3OptionalMessages) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._optSimple != rhs_storage._optSimple {return false}
        if _storage._optScalar != rhs_storage._optScalar {return false}
        if _storage._optTs != rhs_storage._optTs {return false}
        if _storage._optWrapper != rhs_storage._optWrapper {return false}
        if _storage._plainSimple != rhs_storage._plainSimple {return false}
        if _storage._label != rhs_storage._label {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_IntentHolder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".IntentHolder"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}intent\0\u{3}all_intents\0\u{3}by_name\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularEnumField(value: &self.intent) }()
      case 2: try { try decoder.decodeRepeatedEnumField(value: &self.allIntents) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_IntentFlag>.self, value: &self.byName) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.intent != .intentDefault {
      try visitor.visitSingularEnumField(value: self.intent, fieldNumber: 1)
    }
    if !self.allIntents.isEmpty {
      try visitor.visitPackedEnumField(value: self.allIntents, fieldNumber: 2)
    }
    if !self.byName.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufEnumMap<SwiftProtobuf.ProtobufString,Testcompat_IntentFlag>.self, value: self.byName, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_IntentHolder, rhs: Testcompat_IntentHolder) -> Bool {
    if lhs.intent != rhs.intent {return false}
    if lhs.allIntents != rhs.allIntents {return false}
    if lhs.byName != rhs.byName {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
