// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: scalar_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// All 15 scalar types
struct Testcompat_ScalarMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var doubleField: Double = 0

  var floatField: Float = 0

  var int32Field: Int32 = 0

  var int64Field: Int64 = 0

  var uint32Field: UInt32 = 0

  var uint64Field: UInt64 = 0

  var sint32Field: Int32 = 0

  var sint64Field: Int64 = 0

  var fixed32Field: UInt32 = 0

  var fixed64Field: UInt64 = 0

  var sfixed32Field: Int32 = 0

  var sfixed64Field: Int64 = 0

  var boolField: Bool = false

  var stringField: String = String()

  var bytesField: Data = Data()

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Proto3 optional (explicit presence)
struct Testcompat_OptionalScalarMessage: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var optDouble: Double {
    get {return _optDouble ?? 0}
    set {_optDouble = newValue}
  }
  /// Returns true if `optDouble` has been explicitly set.
  var hasOptDouble: Bool {return self._optDouble != nil}
  /// Clears the value of `optDouble`. Subsequent reads from it will return its default value.
  mutating func clearOptDouble() {self._optDouble = nil}

  var optFloat: Float {
    get {return _optFloat ?? 0}
    set {_optFloat = newValue}
  }
  /// Returns true if `optFloat` has been explicitly set.
  var hasOptFloat: Bool {return self._optFloat != nil}
  /// Clears the value of `optFloat`. Subsequent reads from it will return its default value.
  mutating func clearOptFloat() {self._optFloat = nil}

  var optInt32: Int32 {
    get {return _optInt32 ?? 0}
    set {_optInt32 = newValue}
  }
  /// Returns true if `optInt32` has been explicitly set.
  var hasOptInt32: Bool {return self._optInt32 != nil}
  /// Clears the value of `optInt32`. Subsequent reads from it will return its default value.
  mutating func clearOptInt32() {self._optInt32 = nil}

  var optInt64: Int64 {
    get {return _optInt64 ?? 0}
    set {_optInt64 = newValue}
  }
  /// Returns true if `optInt64` has been explicitly set.
  var hasOptInt64: Bool {return self._optInt64 != nil}
  /// Clears the value of `optInt64`. Subsequent reads from it will return its default value.
  mutating func clearOptInt64() {self._optInt64 = nil}

  var optUint32: UInt32 {
    get {return _optUint32 ?? 0}
    set {_optUint32 = newValue}
  }
  /// Returns true if `optUint32` has been explicitly set.
  var hasOptUint32: Bool {return self._optUint32 != nil}
  /// Clears the value of `optUint32`. Subsequent reads from it will return its default value.
  mutating func clearOptUint32() {self._optUint32 = nil}

  var optUint64: UInt64 {
    get {return _optUint64 ?? 0}
    set {_optUint64 = newValue}
  }
  /// Returns true if `optUint64` has been explicitly set.
  var hasOptUint64: Bool {return self._optUint64 != nil}
  /// Clears the value of `optUint64`. Subsequent reads from it will return its default value.
  mutating func clearOptUint64() {self._optUint64 = nil}

  var optSint32: Int32 {
    get {return _optSint32 ?? 0}
    set {_optSint32 = newValue}
  }
  /// Returns true if `optSint32` has been explicitly set.
  var hasOptSint32: Bool {return self._optSint32 != nil}
  /// Clears the value of `optSint32`. Subsequent reads from it will return its default value.
  mutating func clearOptSint32() {self._optSint32 = nil}

  var optSint64: Int64 {
    get {return _optSint64 ?? 0}
    set {_optSint64 = newValue}
  }
  /// Returns true if `optSint64` has been explicitly set.
  var hasOptSint64: Bool {return self._optSint64 != nil}
  /// Clears the value of `optSint64`. Subsequent reads from it will return its default value.
  mutating func clearOptSint64() {self._optSint64 = nil}

  var optFixed32: UInt32 {
    get {return _optFixed32 ?? 0}
    set {_optFixed32 = newValue}
  }
  /// Returns true if `optFixed32` has been explicitly set.
  var hasOptFixed32: Bool {return self._optFixed32 != nil}
  /// Clears the value of `optFixed32`. Subsequent reads from it will return its default value.
  mutating func clearOptFixed32() {self._optFixed32 = nil}

  var optFixed64: UInt64 {
    get {return _optFixed64 ?? 0}
    set {_optFixed64 = newValue}
  }
  /// Returns true if `optFixed64` has been explicitly set.
  var hasOptFixed64: Bool {return self._optFixed64 != nil}
  /// Clears the value of `optFixed64`. Subsequent reads from it will return its default value.
  mutating func clearOptFixed64() {self._optFixed64 = nil}

  var optSfixed32: Int32 {
    get {return _optSfixed32 ?? 0}
    set {_optSfixed32 = newValue}
  }
  /// Returns true if `optSfixed32` has been explicitly set.
  var hasOptSfixed32: Bool {return self._optSfixed32 != nil}
  /// Clears the value of `optSfixed32`. Subsequent reads from it will return its default value.
  mutating func clearOptSfixed32() {self._optSfixed32 = nil}

  var optSfixed64: Int64 {
    get {return _optSfixed64 ?? 0}
    set {_optSfixed64 = newValue}
  }
  /// Returns true if `optSfixed64` has been explicitly set.
  var hasOptSfixed64: Bool {return self._optSfixed64 != nil}
  /// Clears the value of `optSfixed64`. Subsequent reads from it will return its default value.
  mutating func clearOptSfixed64() {self._optSfixed64 = nil}

  var optBool: Bool {
    get {return _optBool ?? false}
    set {_optBool = newValue}
  }
  /// Returns true if `optBool` has been explicitly set.
  var hasOptBool: Bool {return self._optBool != nil}
  /// Clears the value of `optBool`. Subsequent reads from it will return its default value.
  mutating func clearOptBool() {self._optBool = nil}

  var optString: String {
    get {return _optString ?? String()}
    set {_optString = newValue}
  }
  /// Returns true if `optString` has been explicitly set.
  var hasOptString: Bool {return self._optString != nil}
  /// Clears the value of `optString`. Subsequent reads from it will return its default value.
  mutating func clearOptString() {self._optString = nil}

  var optBytes: Data {
    get {return _optBytes ?? Data()}
    set {_optBytes = newValue}
  }
  /// Returns true if `optBytes` has been explicitly set.
  var hasOptBytes: Bool {return self._optBytes != nil}
  /// Clears the value of `optBytes`. Subsequent reads from it will return its default value.
  mutating func clearOptBytes() {self._optBytes = nil}

  /// implicit presence for comparison
  var plainInt32: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _optDouble: Double? = nil
  fileprivate var _optFloat: Float? = nil
  fileprivate var _optInt32: Int32? = nil
  fileprivate var _optInt64: Int64? = nil
  fileprivate var _optUint32: UInt32? = nil
  fileprivate var _optUint64: UInt64? = nil
  fileprivate var _optSint32: Int32? = nil
  fileprivate var _optSint64: Int64? = nil
  fileprivate var _optFixed32: UInt32? = nil
  fileprivate var _optFixed64: UInt64? = nil
  fileprivate var _optSfixed32: Int32? = nil
  fileprivate var _optSfixed64: Int64? = nil
  fileprivate var _optBool: Bool? = nil
  fileprivate var _optString: String? = nil
  fileprivate var _optBytes: Data? = nil
}

/// Field name edge cases
struct Testcompat_FieldNameEdgeCases: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// -> myFieldName
  var myFieldName: String = String()

  /// -> aLongFieldNameHere
  var aLongFieldNameHere: Int32 = 0

  /// -> httpRequest
  var httpRequest: Bool = false

  /// -> myRpc
  var myRpc: String = String()

  /// -> DoubleLeading
  var _DoubleLeading: String = String()

  /// -> trailing
  var trailing_: String = String()

  var customJson: String = String()

  /// -> ALLCAPS (no change)
  var allcaps: String = String()

  /// -> CamelCase (no change)
  var camelCase: String = String()

  /// -> field10
  var field10: Int32 = 0

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Message with 50+ fields for stress testing
struct Testcompat_WideMessage: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var f1: String {
    get {return _storage._f1}
    set {_uniqueStorage()._f1 = newValue}
  }

  var f2: String {
    get {return _storage._f2}
    set {_uniqueStorage()._f2 = newValue}
  }

  var f3: String {
    get {return _storage._f3}
    set {_uniqueStorage()._f3 = newValue}
  }

  var f4: String {
    get {return _storage._f4}
    set {_uniqueStorage()._f4 = newValue}
  }

  var f5: String {
    get {return _storage._f5}
    set {_uniqueStorage()._f5 = newValue}
  }

  var f6: String {
    get {return _storage._f6}
    set {_uniqueStorage()._f6 = newValue}
  }

  var f7: String {
    get {return _storage._f7}
    set {_uniqueStorage()._f7 = newValue}
  }

  var f8: String {
    get {return _storage._f8}
    set {_uniqueStorage()._f8 = newValue}
  }

  var f9: String {
    get {return _storage._f9}
    set {_uniqueStorage()._f9 = newValue}
  }

  var f10: String {
    get {return _storage._f10}
    set {_uniqueStorage()._f10 = newValue}
  }

  var f11: String {
    get {return _storage._f11}
    set {_uniqueStorage()._f11 = newValue}
  }

  var f12: String {
    get {return _storage._f12}
    set {_uniqueStorage()._f12 = newValue}
  }

  var f13: String {
    get {return _storage._f13}
    set {_uniqueStorage()._f13 = newValue}
  }

  var f14: String {
    get {return _storage._f14}
    set {_uniqueStorage()._f14 = newValue}
  }

  var f15: String {
    get {return _storage._f15}
    set {_uniqueStorage()._f15 = newValue}
  }

  var f16: String {
    get {return _storage._f16}
    set {_uniqueStorage()._f16 = newValue}
  }

  var f17: String {
    get {return _storage._f17}
    set {_uniqueStorage()._f17 = newValue}
  }

  var f18: String {
    get {return _storage._f18}
    set {_uniqueStorage()._f18 = newValue}
  }

  var f19: String {
    get {return _storage._f19}
    set {_uniqueStorage()._f19 = newValue}
  }

  var f20: String {
    get {return _storage._f20}
    set {_uniqueStorage()._f20 = newValue}
  }

  var i1: Int32 {
    get {return _storage._i1}
    set {_uniqueStorage()._i1 = newValue}
  }

  var i2: Int32 {
    get {return _storage._i2}
    set {_uniqueStorage()._i2 = newValue}
  }

  var i3: Int32 {
    get {return _storage._i3}
    set {_uniqueStorage()._i3 = newValue}
  }

  var i4: Int32 {
    get {return _storage._i4}
    set {_uniqueStorage()._i4 = newValue}
  }

  var i5: Int32 {
    get {return _storage._i5}
    set {_uniqueStorage()._i5 = newValue}
  }

  var i6: Int32 {
    get {return _storage._i6}
    set {_uniqueStorage()._i6 = newValue}
  }

  var i7: Int32 {
    get {return _storage._i7}
    set {_uniqueStorage()._i7 = newValue}
  }

  var i8: Int32 {
    get {return _storage._i8}
    set {_uniqueStorage()._i8 = newValue}
  }

  var i9: Int32 {
    get {return _storage._i9}
    set {_uniqueStorage()._i9 = newValue}
  }

  var i10: Int32 {
    get {return _storage._i10}
    set {_uniqueStorage()._i10 = newValue}
  }

  var d1: Double {
    get {return _storage._d1}
    set {_uniqueStorage()._d1 = newValue}
  }

  var d2: Double {
    get {return _storage._d2}
    set {_uniqueStorage()._d2 = newValue}
  }

  var d3: Double {
    get {return _storage._d3}
    set {_uniqueStorage()._d3 = newValue}
  }

  var d4: Double {
    get {return _storage._d4}
    set {_uniqueStorage()._d4 = newValue}
  }

  var d5: Double {
    get {return _storage._d5}
    set {_uniqueStorage()._d5 = newValue}
  }

  var b1: Bool {
    get {return _storage._b1}
    set {_uniqueStorage()._b1 = newValue}
  }

  var b2: Bool {
    get {return _storage._b2}
    set {_uniqueStorage()._b2 = newValue}
  }

  var b3: Bool {
    get {return _storage._b3}
    set {_uniqueStorage()._b3 = newValue}
  }

  var b4: Bool {
    get {return _storage._b4}
    set {_uniqueStorage()._b4 = newValue}
  }

  var b5: Bool {
    get {return _storage._b5}
    set {_uniqueStorage()._b5 = newValue}
  }

  var by1: Data {
    get {return _storage._by1}
    set {_uniqueStorage()._by1 = newValue}
  }

  var by2: Data {
    get {return _storage._by2}
    set {_uniqueStorage()._by2 = newValue}
  }

  var by3: Data {
    get {return _storage._by3}
    set {_uniqueStorage()._by3 = newValue}
  }

  var l1: Int64 {
    get {return _storage._l1}
    set {_uniqueStorage()._l1 = newValue}
  }

  var l2: Int64 {
    get {return _storage._l2}
    set {_uniqueStorage()._l2 = newValue}
  }

  var l3: Int64 {
    get {return _storage._l3}
    set {_uniqueStorage()._l3 = newValue}
  }

  var u1: UInt64 {
    get {return _storage._u1}
    set {_uniqueStorage()._u1 = newValue}
  }

  var u2: UInt64 {
    get {return _storage._u2}
    set {_uniqueStorage()._u2 = newValue}
  }

  var fl1: Float {
    get {return _storage._fl1}
    set {_uniqueStorage()._fl1 = newValue}
  }

  var fl2: Float {
    get {return _storage._fl2}
    set {_uniqueStorage()._fl2 = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_ScalarMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".ScalarMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}double_field\0\u{3}float_field\0\u{3}int32_field\0\u{3}int64_field\0\u{3}uint32_field\0\u{3}uint64_field\0\u{3}sint32_field\0\u{3}sint64_field\0\u{3}fixed32_field\0\u{3}fixed64_field\0\u{3}sfixed32_field\0\u{3}sfixed64_field\0\u{3}bool_field\0\u{3}string_field\0\u{3}bytes_field\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self.doubleField) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.floatField) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self.int32Field) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self.int64Field) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.uint32Field) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self.uint64Field) }()
      case 7: try { try decoder.decodeSingularSInt32Field(value: &self.sint32Field) }()
      case 8: try { try decoder.decodeSingularSInt64Field(value: &self.sint64Field) }()
      case 9: try { try decoder.decodeSingularFixed32Field(value: &self.fixed32Field) }()
      case 10: try { try decoder.decodeSingularFixed64Field(value: &self.fixed64Field) }()
      case 11: try { try decoder.decodeSingularSFixed32Field(value: &self.sfixed32Field) }()
      case 12: try { try decoder.decodeSingularSFixed64Field(value: &self.sfixed64Field) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self.boolField) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self.stringField) }()
      case 15: try { try decoder.decodeSingularBytesField(value: &self.bytesField) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.doubleField.bitPattern != 0 {
      try visitor.visitSingularDoubleField(value: self.doubleField, fieldNumber: 1)
    }
    if self.floatField.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.floatField, fieldNumber: 2)
    }
    if self.int32Field != 0 {
      try visitor.visitSingularInt32Field(value: self.int32Field, fieldNumber: 3)
    }
    if self.int64Field != 0 {
      try visitor.visitSingularInt64Field(value: self.int64Field, fieldNumber: 4)
    }
    if self.uint32Field != 0 {
      try visitor.visitSingularUInt32Field(value: self.uint32Field, fieldNumber: 5)
    }
    if self.uint64Field != 0 {
      try visitor.visitSingularUInt64Field(value: self.uint64Field, fieldNumber: 6)
    }
    if self.sint32Field != 0 {
      try visitor.visitSingularSInt32Field(value: self.sint32Field, fieldNumber: 7)
    }
    if self.sint64Field != 0 {
      try visitor.visitSingularSInt64Field(value: self.sint64Field, fieldNumber: 8)
    }
    if self.fixed32Field != 0 {
      try visitor.visitSingularFixed32Field(value: self.fixed32Field, fieldNumber: 9)
    }
    if self.fixed64Field != 0 {
      try visitor.visitSingularFixed64Field(value: self.fixed64Field, fieldNumber: 10)
    }
    if self.sfixed32Field != 0 {
      try visitor.visitSingularSFixed32Field(value: self.sfixed32Field, fieldNumber: 11)
    }
    if self.sfixed64Field != 0 {
      try visitor.visitSingularSFixed64Field(value: self.sfixed64Field, fieldNumber: 12)
    }
    if self.boolField != false {
      try visitor.visitSingularBoolField(value: self.boolField, fieldNumber: 13)
    }
    if !self.stringField.isEmpty {
      try visitor.visitSingularStringField(value: self.stringField, fieldNumber: 14)
    }
    if !self.bytesField.isEmpty {
      try visitor.visitSingularBytesField(value: self.bytesField, fieldNumber: 15)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_ScalarMessage, rhs: Testcompat_ScalarMessage) -> Bool {
    if lhs.doubleField != rhs.doubleField {return false}
    if lhs.floatField != rhs.floatField {return false}
    if lhs.int32Field != rhs.int32Field {return false}
    if lhs.int64Field != rhs.int64Field {return false}
    if lhs.uint32Field != rhs.uint32Field {return false}
    if lhs.uint64Field != rhs.uint64Field {return false}
    if lhs.sint32Field != rhs.sint32Field {return false}
    if lhs.sint64Field != rhs.sint64Field {return false}
    if lhs.fixed32Field != rhs.fixed32Field {return false}
    if lhs.fixed64Field != rhs.fixed64Field {return false}
    if lhs.sfixed32Field != rhs.sfixed32Field {return false}
    if lhs.sfixed64Field != rhs.sfixed64Field {return false}
    if lhs.boolField != rhs.boolField {return false}
    if lhs.stringField != rhs.stringField {return false}
    if lhs.bytesField != rhs.bytesField {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_OptionalScalarMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".OptionalScalarMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}opt_double\0\u{3}opt_float\0\u{3}opt_int32\0\u{3}opt_int64\0\u{3}opt_uint32\0\u{3}opt_uint64\0\u{3}opt_sint32\0\u{3}opt_sint64\0\u{3}opt_fixed32\0\u{3}opt_fixed64\0\u{3}opt_sfixed32\0\u{3}opt_sfixed64\0\u{3}opt_bool\0\u{3}opt_string\0\u{3}opt_bytes\0\u{3}plain_int32\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularDoubleField(value: &self._optDouble) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self._optFloat) }()
      case 3: try { try decoder.decodeSingularInt32Field(value: &self._optInt32) }()
      case 4: try { try decoder.decodeSingularInt64Field(value: &self._optInt64) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self._optUint32) }()
      case 6: try { try decoder.decodeSingularUInt64Field(value: &self._optUint64) }()
      case 7: try { try decoder.decodeSingularSInt32Field(value: &self._optSint32) }()
      case 8: try { try decoder.decodeSingularSInt64Field(value: &self._optSint64) }()
      case 9: try { try decoder.decodeSingularFixed32Field(value: &self._optFixed32) }()
      case 10: try { try decoder.decodeSingularFixed64Field(value: &self._optFixed64) }()
      case 11: try { try decoder.decodeSingularSFixed32Field(value: &self._optSfixed32) }()
      case 12: try { try decoder.decodeSingularSFixed64Field(value: &self._optSfixed64) }()
      case 13: try { try decoder.decodeSingularBoolField(value: &self._optBool) }()
      case 14: try { try decoder.decodeSingularStringField(value: &self._optString) }()
      case 15: try { try decoder.decodeSingularBytesField(value: &self._optBytes) }()
      case 16: try { try decoder.decodeSingularInt32Field(value: &self.plainInt32) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._optDouble {
      try visitor.visitSingularDoubleField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._optFloat {
      try visitor.visitSingularFloatField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._optInt32 {
      try visitor.visitSingularInt32Field(value: v, fieldNumber: 3)
    } }()
    try { if let v = self._optInt64 {
      try visitor.visitSingularInt64Field(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._optUint32 {
      try visitor.visitSingularUInt32Field(value: v, fieldNumber: 5)
    } }()
    try { if let v = self._optUint64 {
      try visitor.visitSingularUInt64Field(value: v, fieldNumber: 6)
    } }()
    try { if let v = self._optSint32 {
      try visitor.visitSingularSInt32Field(value: v, fieldNumber: 7)
    } }()
    try { if let v = self._optSint64 {
      try visitor.visitSingularSInt64Field(value: v, fieldNumber: 8)
    } }()
    try { if let v = self._optFixed32 {
      try visitor.visitSingularFixed32Field(value: v, fieldNumber: 9)
    } }()
    try { if let v = self._optFixed64 {
      try visitor.visitSingularFixed64Field(value: v, fieldNumber: 10)
    } }()
    try { if let v = self._optSfixed32 {
      try visitor.visitSingularSFixed32Field(value: v, fieldNumber: 11)
    } }()
    try { if let v = self._optSfixed64 {
      try visitor.visitSingularSFixed64Field(value: v, fieldNumber: 12)
    } }()
    try { if let v = self._optBool {
      try visitor.visitSingularBoolField(value: v, fieldNumber: 13)
    } }()
    try { if let v = self._optString {
      try visitor.visitSingularStringField(value: v, fieldNumber: 14)
    } }()
    try { if let v = self._optBytes {
      try visitor.visitSingularBytesField(value: v, fieldNumber: 15)
    } }()
    if self.plainInt32 != 0 {
      try visitor.visitSingularInt32Field(value: self.plainInt32, fieldNumber: 16)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_OptionalScalarMessage, rhs: Testcompat_OptionalScalarMessage) -> Bool {
    if lhs._optDouble != rhs._optDouble {return false}
    if lhs._optFloat != rhs._optFloat {return false}
    if lhs._optInt32 != rhs._optInt32 {return false}
    if lhs._optInt64 != rhs._optInt64 {return false}
    if lhs._optUint32 != rhs._optUint32 {return false}
    if lhs._optUint64 != rhs._optUint64 {return false}
    if lhs._optSint32 != rhs._optSint32 {return false}
    if lhs._optSint64 != rhs._optSint64 {return false}
    if lhs._optFixed32 != rhs._optFixed32 {return false}
    if lhs._optFixed64 != rhs._optFixed64 {return false}
    if lhs._optSfixed32 != rhs._optSfixed32 {return false}
    if lhs._optSfixed64 != rhs._optSfixed64 {return false}
    if lhs._optBool != rhs._optBool {return false}
    if lhs._optString != rhs._optString {return false}
    if lhs._optBytes != rhs._optBytes {return false}
    if lhs.plainInt32 != rhs.plainInt32 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_FieldNameEdgeCases: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".FieldNameEdgeCases"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}my_field_name\0\u{3}a_long_field_name_here\0\u{3}http_request\0\u{3}my_rpc\0\u{3}__double_leading\0\u{3}trailing_\0\u{5}custom_json\0customOverride\0\u{1}ALLCAPS\0\u{1}CamelCase\0\u{3}field_10\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.myFieldName) }()
      case 2: try { try decoder.decodeSingularInt32Field(value: &self.aLongFieldNameHere) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.httpRequest) }()
      case 4: try { try decoder.decodeSingularStringField(value: &self.myRpc) }()
      case 5: try { try decoder.decodeSingularStringField(value: &self._DoubleLeading) }()
      case 6: try { try decoder.decodeSingularStringField(value: &self.trailing_) }()
      case 7: try { try decoder.decodeSingularStringField(value: &self.customJson) }()
      case 8: try { try decoder.decodeSingularStringField(value: &self.allcaps) }()
      case 9: try { try decoder.decodeSingularStringField(value: &self.camelCase) }()
      case 10: try { try decoder.decodeSingularInt32Field(value: &self.field10) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.myFieldName.isEmpty {
      try visitor.visitSingularStringField(value: self.myFieldName, fieldNumber: 1)
    }
    if self.aLongFieldNameHere != 0 {
      try visitor.visitSingularInt32Field(value: self.aLongFieldNameHere, fieldNumber: 2)
    }
    if self.httpRequest != false {
      try visitor.visitSingularBoolField(value: self.httpRequest, fieldNumber: 3)
    }
    if !self.myRpc.isEmpty {
      try visitor.visitSingularStringField(value: self.myRpc, fieldNumber: 4)
    }
    if !self._DoubleLeading.isEmpty {
      try visitor.visitSingularStringField(value: self._DoubleLeading, fieldNumber: 5)
    }
    if !self.trailing_.isEmpty {
      try visitor.visitSingularStringField(value: self.trailing_, fieldNumber: 6)
    }
    if !self.customJson.isEmpty {
      try visitor.visitSingularStringField(value: self.customJson, fieldNumber: 7)
    }
    if !self.allcaps.isEmpty {
      try visitor.visitSingularStringField(value: self.allcaps, fieldNumber: 8)
    }
    if !self.camelCase.isEmpty {
      try visitor.visitSingularStringField(value: self.camelCase, fieldNumber: 9)
    }
    if self.field10 != 0 {
      try visitor.visitSingularInt32Field(value: self.field10, fieldNumber: 10)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_FieldNameEdgeCases, rhs: Testcompat_FieldNameEdgeCases) -> Bool {
    if lhs.myFieldName != rhs.myFieldName {return false}
    if lhs.aLongFieldNameHere != rhs.aLongFieldNameHere {return false}
    if lhs.httpRequest != rhs.httpRequest {return false}
    if lhs.myRpc != rhs.myRpc {return false}
    if lhs._DoubleLeading != rhs._DoubleLeading {return false}
    if lhs.trailing_ != rhs.trailing_ {return false}
    if lhs.customJson != rhs.customJson {return false}
    if lhs.allcaps != rhs.allcaps {return false}
    if lhs.camelCase != rhs.camelCase {return false}
    if lhs.field10 != rhs.field10 {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WideMessage: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WideMessage"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}f1\0\u{1}f2\0\u{1}f3\0\u{1}f4\0\u{1}f5\0\u{1}f6\0\u{1}f7\0\u{1}f8\0\u{1}f9\0\u{1}f10\0\u{1}f11\0\u{1}f12\0\u{1}f13\0\u{1}f14\0\u{1}f15\0\u{1}f16\0\u{1}f17\0\u{1}f18\0\u{1}f19\0\u{1}f20\0\u{1}i1\0\u{1}i2\0\u{1}i3\0\u{1}i4\0\u{1}i5\0\u{1}i6\0\u{1}i7\0\u{1}i8\0\u{1}i9\0\u{1}i10\0\u{1}d1\0\u{1}d2\0\u{1}d3\0\u{1}d4\0\u{1}d5\0\u{1}b1\0\u{1}b2\0\u{1}b3\0\u{1}b4\0\u{1}b5\0\u{1}by1\0\u{1}by2\0\u{1}by3\0\u{1}l1\0\u{1}l2\0\u{1}l3\0\u{1}u1\0\u{1}u2\0\u{1}fl1\0\u{1}fl2\0")

  fileprivate class _StorageClass {
    var _f1: String = String()
    var _f2: String = String()
    var _f3: String = String()
    var _f4: String = String()
    var _f5: String = String()
    var _f6: String = String()
    var _f7: String = String()
    var _f8: String = String()
    var _f9: String = String()
    var _f10: String = String()
    var _f11: String = String()
    var _f12: String = String()
    var _f13: String = String()
    var _f14: String = String()
    var _f15: String = String()
    var _f16: String = String()
    var _f17: String = String()
    var _f18: String = String()
    var _f19: String = String()
    var _f20: String = String()
    var _i1: Int32 = 0
    var _i2: Int32 = 0
    var _i3: Int32 = 0
    var _i4: Int32 = 0
    var _i5: Int32 = 0
    var _i6: Int32 = 0
    var _i7: Int32 = 0
    var _i8: Int32 = 0
    var _i9: Int32 = 0
    var _i10: Int32 = 0
    var _d1: Double = 0
    var _d2: Double = 0
    var _d3: Double = 0
    var _d4: Double = 0
    var _d5: Double = 0
    var _b1: Bool = false
    var _b2: Bool = false
    var _b3: Bool = false
    var _b4: Bool = false
    var _b5: Bool = false
    var _by1: Data = Data()
    var _by2: Data = Data()
    var _by3: Data = Data()
    var _l1: Int64 = 0
    var _l2: Int64 = 0
    var _l3: Int64 = 0
    var _u1: UInt64 = 0
    var _u2: UInt64 = 0
    var _fl1: Float = 0
    var _fl2: Float = 0

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _f1 = source._f1
      _f2 = source._f2
      _f3 = source._f3
      _f4 = source._f4
      _f5 = source._f5
      _f6 = source._f6
      _f7 = source._f7
      _f8 = source._f8
      _f9 = source._f9
      _f10 = source._f10
      _f11 = source._f11
      _f12 = source._f12
      _f13 = source._f13
      _f14 = source._f14
      _f15 = source._f15
      _f16 = source._f16
      _f17 = source._f17
      _f18 = source._f18
      _f19 = source._f19
      _f20 = source._f20
      _i1 = source._i1
      _i2 = source._i2
      _i3 = source._i3
      _i4 = source._i4
      _i5 = source._i5
      _i6 = source._i6
      _i7 = source._i7
      _i8 = source._i8
      _i9 = source._i9
      _i10 = source._i10
      _d1 = source._d1
      _d2 = source._d2
      _d3 = source._d3
      _d4 = source._d4
      _d5 = source._d5
      _b1 = source._b1
      _b2 = source._b2
      _b3 = source._b3
      _b4 = source._b4
      _b5 = source._b5
      _by1 = source._by1
      _by2 = source._by2
      _by3 = source._by3
      _l1 = source._l1
      _l2 = source._l2
      _l3 = source._l3
      _u1 = source._u1
      _u2 = source._u2
      _fl1 = source._fl1
      _fl2 = source._fl2
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularStringField(value: &_storage._f1) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._f2) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._f3) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._f4) }()
        case 5: try { try decoder.decodeSingularStringField(value: &_storage._f5) }()
        case 6: try { try decoder.decodeSingularStringField(value: &_storage._f6) }()
        case 7: try { try decoder.decodeSingularStringField(value: &_storage._f7) }()
        case 8: try { try decoder.decodeSingularStringField(value: &_storage._f8) }()
        case 9: try { try decoder.decodeSingularStringField(value: &_storage._f9) }()
        case 10: try { try decoder.decodeSingularStringField(value: &_storage._f10) }()
        case 11: try { try decoder.decodeSingularStringField(value: &_storage._f11) }()
        case 12: try { try decoder.decodeSingularStringField(value: &_storage._f12) }()
        case 13: try { try decoder.decodeSingularStringField(value: &_storage._f13) }()
        case 14: try { try decoder.decodeSingularStringField(value: &_storage._f14) }()
        case 15: try { try decoder.decodeSingularStringField(value: &_storage._f15) }()
        case 16: try { try decoder.decodeSingularStringField(value: &_storage._f16) }()
        case 17: try { try decoder.decodeSingularStringField(value: &_storage._f17) }()
        case 18: try { try decoder.decodeSingularStringField(value: &_storage._f18) }()
        case 19: try { try decoder.decodeSingularStringField(value: &_storage._f19) }()
        case 20: try { try decoder.decodeSingularStringField(value: &_storage._f20) }()
        case 21: try { try decoder.decodeSingularInt32Field(value: &_storage._i1) }()
        case 22: try { try decoder.decodeSingularInt32Field(value: &_storage._i2) }()
        case 23: try { try decoder.decodeSingularInt32Field(value: &_storage._i3) }()
        case 24: try { try decoder.decodeSingularInt32Field(value: &_storage._i4) }()
        case 25: try { try decoder.decodeSingularInt32Field(value: &_storage._i5) }()
        case 26: try { try decoder.decodeSingularInt32Field(value: &_storage._i6) }()
        case 27: try { try decoder.decodeSingularInt32Field(value: &_storage._i7) }()
        case 28: try { try decoder.decodeSingularInt32Field(value: &_storage._i8) }()
        case 29: try { try decoder.decodeSingularInt32Field(value: &_storage._i9) }()
        case 30: try { try decoder.decodeSingularInt32Field(value: &_storage._i10) }()
        case 31: try { try decoder.decodeSingularDoubleField(value: &_storage._d1) }()
        case 32: try { try decoder.decodeSingularDoubleField(value: &_storage._d2) }()
        case 33: try { try decoder.decodeSingularDoubleField(value: &_storage._d3) }()
        case 34: try { try decoder.decodeSingularDoubleField(value: &_storage._d4) }()
        case 35: try { try decoder.decodeSingularDoubleField(value: &_storage._d5) }()
        case 36: try { try decoder.decodeSingularBoolField(value: &_storage._b1) }()
        case 37: try { try decoder.decodeSingularBoolField(value: &_storage._b2) }()
        case 38: try { try decoder.decodeSingularBoolField(value: &_storage._b3) }()
        case 39: try { try decoder.decodeSingularBoolField(value: &_storage._b4) }()
        case 40: try { try decoder.decodeSingularBoolField(value: &_storage._b5) }()
        case 41: try { try decoder.decodeSingularBytesField(value: &_storage._by1) }()
        case 42: try { try decoder.decodeSingularBytesField(value: &_storage._by2) }()
        case 43: try { try decoder.decodeSingularBytesField(value: &_storage._by3) }()
        case 44: try { try decoder.decodeSingularInt64Field(value: &_storage._l1) }()
        case 45: try { try decoder.decodeSingularInt64Field(value: &_storage._l2) }()
        case 46: try { try decoder.decodeSingularInt64Field(value: &_storage._l3) }()
        case 47: try { try decoder.decodeSingularUInt64Field(value: &_storage._u1) }()
        case 48: try { try decoder.decodeSingularUInt64Field(value: &_storage._u2) }()
        case 49: try { try decoder.decodeSingularFloatField(value: &_storage._fl1) }()
        case 50: try { try decoder.decodeSingularFloatField(value: &_storage._fl2) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      if !_storage._f1.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f1, fieldNumber: 1)
      }
      if !_storage._f2.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f2, fieldNumber: 2)
      }
      if !_storage._f3.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f3, fieldNumber: 3)
      }
      if !_storage._f4.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f4, fieldNumber: 4)
      }
      if !_storage._f5.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f5, fieldNumber: 5)
      }
      if !_storage._f6.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f6, fieldNumber: 6)
      }
      if !_storage._f7.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f7, fieldNumber: 7)
      }
      if !_storage._f8.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f8, fieldNumber: 8)
      }
      if !_storage._f9.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f9, fieldNumber: 9)
      }
      if !_storage._f10.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f10, fieldNumber: 10)
      }
      if !_storage._f11.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f11, fieldNumber: 11)
      }
      if !_storage._f12.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f12, fieldNumber: 12)
      }
      if !_storage._f13.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f13, fieldNumber: 13)
      }
      if !_storage._f14.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f14, fieldNumber: 14)
      }
      if !_storage._f15.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f15, fieldNumber: 15)
      }
      if !_storage._f16.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f16, fieldNumber: 16)
      }
      if !_storage._f17.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f17, fieldNumber: 17)
      }
      if !_storage._f18.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f18, fieldNumber: 18)
      }
      if !_storage._f19.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f19, fieldNumber: 19)
      }
      if !_storage._f20.isEmpty {
        try visitor.visitSingularStringField(value: _storage._f20, fieldNumber: 20)
      }
      if _storage._i1 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i1, fieldNumber: 21)
      }
      if _storage._i2 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i2, fieldNumber: 22)
      }
      if _storage._i3 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i3, fieldNumber: 23)
      }
      if _storage._i4 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i4, fieldNumber: 24)
      }
      if _storage._i5 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i5, fieldNumber: 25)
      }
      if _storage._i6 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i6, fieldNumber: 26)
      }
      if _storage._i7 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i7, fieldNumber: 27)
      }
      if _storage._i8 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i8, fieldNumber: 28)
      }
      if _storage._i9 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i9, fieldNumber: 29)
      }
      if _storage._i10 != 0 {
        try visitor.visitSingularInt32Field(value: _storage._i10, fieldNumber: 30)
      }
      if _storage._d1.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._d1, fieldNumber: 31)
      }
      if _storage._d2.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._d2, fieldNumber: 32)
      }
      if _storage._d3.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._d3, fieldNumber: 33)
      }
      if _storage._d4.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._d4, fieldNumber: 34)
      }
      if _storage._d5.bitPattern != 0 {
        try visitor.visitSingularDoubleField(value: _storage._d5, fieldNumber: 35)
      }
      if _storage._b1 != false {
        try visitor.visitSingularBoolField(value: _storage._b1, fieldNumber: 36)
      }
      if _storage._b2 != false {
        try visitor.visitSingularBoolField(value: _storage._b2, fieldNumber: 37)
      }
      if _storage._b3 != false {
        try visitor.visitSingularBoolField(value: _storage._b3, fieldNumber: 38)
      }
      if _storage._b4 != false {
        try visitor.visitSingularBoolField(value: _storage._b4, fieldNumber: 39)
      }
      if _storage._b5 != false {
        try visitor.visitSingularBoolField(value: _storage._b5, fieldNumber: 40)
      }
      if !_storage._by1.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._by1, fieldNumber: 41)
      }
      if !_storage._by2.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._by2, fieldNumber: 42)
      }
      if !_storage._by3.isEmpty {
        try visitor.visitSingularBytesField(value: _storage._by3, fieldNumber: 43)
      }
      if _storage._l1 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._l1, fieldNumber: 44)
      }
      if _storage._l2 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._l2, fieldNumber: 45)
      }
      if _storage._l3 != 0 {
        try visitor.visitSingularInt64Field(value: _storage._l3, fieldNumber: 46)
      }
      if _storage._u1 != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._u1, fieldNumber: 47)
      }
      if _storage._u2 != 0 {
        try visitor.visitSingularUInt64Field(value: _storage._u2, fieldNumber: 48)
      }
      if _storage._fl1.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._fl1, fieldNumber: 49)
      }
      if _storage._fl2.bitPattern != 0 {
        try visitor.visitSingularFloatField(value: _storage._fl2, fieldNumber: 50)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WideMessage, rhs: Testcompat_WideMessage) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._f1 != rhs_storage._f1 {return false}
        if _storage._f2 != rhs_storage._f2 {return false}
        if _storage._f3 != rhs_storage._f3 {return false}
        if _storage._f4 != rhs_storage._f4 {return false}
        if _storage._f5 != rhs_storage._f5 {return false}
        if _storage._f6 != rhs_storage._f6 {return false}
        if _storage._f7 != rhs_storage._f7 {return false}
        if _storage._f8 != rhs_storage._f8 {return false}
        if _storage._f9 != rhs_storage._f9 {return false}
        if _storage._f10 != rhs_storage._f10 {return false}
        if _storage._f11 != rhs_storage._f11 {return false}
        if _storage._f12 != rhs_storage._f12 {return false}
        if _storage._f13 != rhs_storage._f13 {return false}
        if _storage._f14 != rhs_storage._f14 {return false}
        if _storage._f15 != rhs_storage._f15 {return false}
        if _storage._f16 != rhs_storage._f16 {return false}
        if _storage._f17 != rhs_storage._f17 {return false}
        if _storage._f18 != rhs_storage._f18 {return false}
        if _storage._f19 != rhs_storage._f19 {return false}
        if _storage._f20 != rhs_storage._f20 {return false}
        if _storage._i1 != rhs_storage._i1 {return false}
        if _storage._i2 != rhs_storage._i2 {return false}
        if _storage._i3 != rhs_storage._i3 {return false}
        if _storage._i4 != rhs_storage._i4 {return false}
        if _storage._i5 != rhs_storage._i5 {return false}
        if _storage._i6 != rhs_storage._i6 {return false}
        if _storage._i7 != rhs_storage._i7 {return false}
        if _storage._i8 != rhs_storage._i8 {return false}
        if _storage._i9 != rhs_storage._i9 {return false}
        if _storage._i10 != rhs_storage._i10 {return false}
        if _storage._d1 != rhs_storage._d1 {return false}
        if _storage._d2 != rhs_storage._d2 {return false}
        if _storage._d3 != rhs_storage._d3 {return false}
        if _storage._d4 != rhs_storage._d4 {return false}
        if _storage._d5 != rhs_storage._d5 {return false}
        if _storage._b1 != rhs_storage._b1 {return false}
        if _storage._b2 != rhs_storage._b2 {return false}
        if _storage._b3 != rhs_storage._b3 {return false}
        if _storage._b4 != rhs_storage._b4 {return false}
        if _storage._b5 != rhs_storage._b5 {return false}
        if _storage._by1 != rhs_storage._by1 {return false}
        if _storage._by2 != rhs_storage._by2 {return false}
        if _storage._by3 != rhs_storage._by3 {return false}
        if _storage._l1 != rhs_storage._l1 {return false}
        if _storage._l2 != rhs_storage._l2 {return false}
        if _storage._l3 != rhs_storage._l3 {return false}
        if _storage._u1 != rhs_storage._u1 {return false}
        if _storage._u2 != rhs_storage._u2 {return false}
        if _storage._fl1 != rhs_storage._fl1 {return false}
        if _storage._fl2 != rhs_storage._fl2 {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
