// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: wkt_types.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

/// All WKT types as singular fields
struct Testcompat_WKTHolder: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  var hasTs: Bool {return _storage._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  mutating func clearTs() {_uniqueStorage()._ts = nil}

  var dur: SwiftProtobuf.Google_Protobuf_Duration {
    get {return _storage._dur ?? SwiftProtobuf.Google_Protobuf_Duration()}
    set {_uniqueStorage()._dur = newValue}
  }
  /// Returns true if `dur` has been explicitly set.
  var hasDur: Bool {return _storage._dur != nil}
  /// Clears the value of `dur`. Subsequent reads from it will return its default value.
  mutating func clearDur() {_uniqueStorage()._dur = nil}

  var mask: SwiftProtobuf.Google_Protobuf_FieldMask {
    get {return _storage._mask ?? SwiftProtobuf.Google_Protobuf_FieldMask()}
    set {_uniqueStorage()._mask = newValue}
  }
  /// Returns true if `mask` has been explicitly set.
  var hasMask: Bool {return _storage._mask != nil}
  /// Clears the value of `mask`. Subsequent reads from it will return its default value.
  mutating func clearMask() {_uniqueStorage()._mask = nil}

  var anyVal: SwiftProtobuf.Google_Protobuf_Any {
    get {return _storage._anyVal ?? SwiftProtobuf.Google_Protobuf_Any()}
    set {_uniqueStorage()._anyVal = newValue}
  }
  /// Returns true if `anyVal` has been explicitly set.
  var hasAnyVal: Bool {return _storage._anyVal != nil}
  /// Clears the value of `anyVal`. Subsequent reads from it will return its default value.
  mutating func clearAnyVal() {_uniqueStorage()._anyVal = nil}

  var structVal: SwiftProtobuf.Google_Protobuf_Struct {
    get {return _storage._structVal ?? SwiftProtobuf.Google_Protobuf_Struct()}
    set {_uniqueStorage()._structVal = newValue}
  }
  /// Returns true if `structVal` has been explicitly set.
  var hasStructVal: Bool {return _storage._structVal != nil}
  /// Clears the value of `structVal`. Subsequent reads from it will return its default value.
  mutating func clearStructVal() {_uniqueStorage()._structVal = nil}

  var valueVal: SwiftProtobuf.Google_Protobuf_Value {
    get {return _storage._valueVal ?? SwiftProtobuf.Google_Protobuf_Value()}
    set {_uniqueStorage()._valueVal = newValue}
  }
  /// Returns true if `valueVal` has been explicitly set.
  var hasValueVal: Bool {return _storage._valueVal != nil}
  /// Clears the value of `valueVal`. Subsequent reads from it will return its default value.
  mutating func clearValueVal() {_uniqueStorage()._valueVal = nil}

  var listVal: SwiftProtobuf.Google_Protobuf_ListValue {
    get {return _storage._listVal ?? SwiftProtobuf.Google_Protobuf_ListValue()}
    set {_uniqueStorage()._listVal = newValue}
  }
  /// Returns true if `listVal` has been explicitly set.
  var hasListVal: Bool {return _storage._listVal != nil}
  /// Clears the value of `listVal`. Subsequent reads from it will return its default value.
  mutating func clearListVal() {_uniqueStorage()._listVal = nil}

  var dblW: SwiftProtobuf.Google_Protobuf_DoubleValue {
    get {return _storage._dblW ?? SwiftProtobuf.Google_Protobuf_DoubleValue()}
    set {_uniqueStorage()._dblW = newValue}
  }
  /// Returns true if `dblW` has been explicitly set.
  var hasDblW: Bool {return _storage._dblW != nil}
  /// Clears the value of `dblW`. Subsequent reads from it will return its default value.
  mutating func clearDblW() {_uniqueStorage()._dblW = nil}

  var fltW: SwiftProtobuf.Google_Protobuf_FloatValue {
    get {return _storage._fltW ?? SwiftProtobuf.Google_Protobuf_FloatValue()}
    set {_uniqueStorage()._fltW = newValue}
  }
  /// Returns true if `fltW` has been explicitly set.
  var hasFltW: Bool {return _storage._fltW != nil}
  /// Clears the value of `fltW`. Subsequent reads from it will return its default value.
  mutating func clearFltW() {_uniqueStorage()._fltW = nil}

  var i64W: SwiftProtobuf.Google_Protobuf_Int64Value {
    get {return _storage._i64W ?? SwiftProtobuf.Google_Protobuf_Int64Value()}
    set {_uniqueStorage()._i64W = newValue}
  }
  /// Returns true if `i64W` has been explicitly set.
  var hasI64W: Bool {return _storage._i64W != nil}
  /// Clears the value of `i64W`. Subsequent reads from it will return its default value.
  mutating func clearI64W() {_uniqueStorage()._i64W = nil}

  var u64W: SwiftProtobuf.Google_Protobuf_UInt64Value {
    get {return _storage._u64W ?? SwiftProtobuf.Google_Protobuf_UInt64Value()}
    set {_uniqueStorage()._u64W = newValue}
  }
  /// Returns true if `u64W` has been explicitly set.
  var hasU64W: Bool {return _storage._u64W != nil}
  /// Clears the value of `u64W`. Subsequent reads from it will return its default value.
  mutating func clearU64W() {_uniqueStorage()._u64W = nil}

  var i32W: SwiftProtobuf.Google_Protobuf_Int32Value {
    get {return _storage._i32W ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
    set {_uniqueStorage()._i32W = newValue}
  }
  /// Returns true if `i32W` has been explicitly set.
  var hasI32W: Bool {return _storage._i32W != nil}
  /// Clears the value of `i32W`. Subsequent reads from it will return its default value.
  mutating func clearI32W() {_uniqueStorage()._i32W = nil}

  var u32W: SwiftProtobuf.Google_Protobuf_UInt32Value {
    get {return _storage._u32W ?? SwiftProtobuf.Google_Protobuf_UInt32Value()}
    set {_uniqueStorage()._u32W = newValue}
  }
  /// Returns true if `u32W` has been explicitly set.
  var hasU32W: Bool {return _storage._u32W != nil}
  /// Clears the value of `u32W`. Subsequent reads from it will return its default value.
  mutating func clearU32W() {_uniqueStorage()._u32W = nil}

  var boolW: SwiftProtobuf.Google_Protobuf_BoolValue {
    get {return _storage._boolW ?? SwiftProtobuf.Google_Protobuf_BoolValue()}
    set {_uniqueStorage()._boolW = newValue}
  }
  /// Returns true if `boolW` has been explicitly set.
  var hasBoolW: Bool {return _storage._boolW != nil}
  /// Clears the value of `boolW`. Subsequent reads from it will return its default value.
  mutating func clearBoolW() {_uniqueStorage()._boolW = nil}

  var strW: SwiftProtobuf.Google_Protobuf_StringValue {
    get {return _storage._strW ?? SwiftProtobuf.Google_Protobuf_StringValue()}
    set {_uniqueStorage()._strW = newValue}
  }
  /// Returns true if `strW` has been explicitly set.
  var hasStrW: Bool {return _storage._strW != nil}
  /// Clears the value of `strW`. Subsequent reads from it will return its default value.
  mutating func clearStrW() {_uniqueStorage()._strW = nil}

  var bytesW: SwiftProtobuf.Google_Protobuf_BytesValue {
    get {return _storage._bytesW ?? SwiftProtobuf.Google_Protobuf_BytesValue()}
    set {_uniqueStorage()._bytesW = newValue}
  }
  /// Returns true if `bytesW` has been explicitly set.
  var hasBytesW: Bool {return _storage._bytesW != nil}
  /// Clears the value of `bytesW`. Subsequent reads from it will return its default value.
  mutating func clearBytesW() {_uniqueStorage()._bytesW = nil}

  var emptyVal: SwiftProtobuf.Google_Protobuf_Empty {
    get {return _storage._emptyVal ?? SwiftProtobuf.Google_Protobuf_Empty()}
    set {_uniqueStorage()._emptyVal = newValue}
  }
  /// Returns true if `emptyVal` has been explicitly set.
  var hasEmptyVal: Bool {return _storage._emptyVal != nil}
  /// Clears the value of `emptyVal`. Subsequent reads from it will return its default value.
  mutating func clearEmptyVal() {_uniqueStorage()._emptyVal = nil}

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

/// Repeated WKTs
struct Testcompat_RepeatedWKTs: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var timestamps: [SwiftProtobuf.Google_Protobuf_Timestamp] = []

  var durations: [SwiftProtobuf.Google_Protobuf_Duration] = []

  var int64Vals: [SwiftProtobuf.Google_Protobuf_Int64Value] = []

  var stringVals: [SwiftProtobuf.Google_Protobuf_StringValue] = []

  var boolVals: [SwiftProtobuf.Google_Protobuf_BoolValue] = []

  var structs: [SwiftProtobuf.Google_Protobuf_Struct] = []

  var values: [SwiftProtobuf.Google_Protobuf_Value] = []

  var anys: [SwiftProtobuf.Google_Protobuf_Any] = []

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// Map with WKT values
struct Testcompat_MapWKTValues: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var tsMap: Dictionary<String,SwiftProtobuf.Google_Protobuf_Timestamp> = [:]

  var i64WMap: Dictionary<String,SwiftProtobuf.Google_Protobuf_Int64Value> = [:]

  var strwMap: Dictionary<String,SwiftProtobuf.Google_Protobuf_StringValue> = [:]

  var structMap: Dictionary<String,SwiftProtobuf.Google_Protobuf_Struct> = [:]

  var anyMap: Dictionary<String,SwiftProtobuf.Google_Protobuf_Any> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  init() {}
}

/// WKT inside nested message
struct Testcompat_WKTNested: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var primary: Testcompat_WKTNested.Inner {
    get {return _primary ?? Testcompat_WKTNested.Inner()}
    set {_primary = newValue}
  }
  /// Returns true if `primary` has been explicitly set.
  var hasPrimary: Bool {return self._primary != nil}
  /// Clears the value of `primary`. Subsequent reads from it will return its default value.
  mutating func clearPrimary() {self._primary = nil}

  var history: [Testcompat_WKTNested.Inner] = []

  var named: Dictionary<String,Testcompat_WKTNested.Inner> = [:]

  var unknownFields = SwiftProtobuf.UnknownStorage()

  struct Inner: Sendable {
    // SwiftProtobuf.Message conformance is added in an extension below. See the
    // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
    // methods supported on all messages.

    var created: SwiftProtobuf.Google_Protobuf_Timestamp {
      get {return _created ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
      set {_created = newValue}
    }
    /// Returns true if `created` has been explicitly set.
    var hasCreated: Bool {return self._created != nil}
    /// Clears the value of `created`. Subsequent reads from it will return its default value.
    mutating func clearCreated() {self._created = nil}

    var ttl: SwiftProtobuf.Google_Protobuf_Duration {
      get {return _ttl ?? SwiftProtobuf.Google_Protobuf_Duration()}
      set {_ttl = newValue}
    }
    /// Returns true if `ttl` has been explicitly set.
    var hasTtl: Bool {return self._ttl != nil}
    /// Clears the value of `ttl`. Subsequent reads from it will return its default value.
    mutating func clearTtl() {self._ttl = nil}

    var count: SwiftProtobuf.Google_Protobuf_Int32Value {
      get {return _count ?? SwiftProtobuf.Google_Protobuf_Int32Value()}
      set {_count = newValue}
    }
    /// Returns true if `count` has been explicitly set.
    var hasCount: Bool {return self._count != nil}
    /// Clears the value of `count`. Subsequent reads from it will return its default value.
    mutating func clearCount() {self._count = nil}

    var unknownFields = SwiftProtobuf.UnknownStorage()

    init() {}

    fileprivate var _created: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    fileprivate var _ttl: SwiftProtobuf.Google_Protobuf_Duration? = nil
    fileprivate var _count: SwiftProtobuf.Google_Protobuf_Int32Value? = nil
  }

  init() {}

  fileprivate var _primary: Testcompat_WKTNested.Inner? = nil
}

/// WKT mixed with all other features
struct Testcompat_WKTMixed: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  var ts: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {return _storage._ts ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._ts = newValue}
  }
  /// Returns true if `ts` has been explicitly set.
  var hasTs: Bool {return _storage._ts != nil}
  /// Clears the value of `ts`. Subsequent reads from it will return its default value.
  mutating func clearTs() {_uniqueStorage()._ts = nil}

  var labels: [SwiftProtobuf.Google_Protobuf_StringValue] {
    get {return _storage._labels}
    set {_uniqueStorage()._labels = newValue}
  }

  var counters: Dictionary<String,SwiftProtobuf.Google_Protobuf_Int64Value> {
    get {return _storage._counters}
    set {_uniqueStorage()._counters = newValue}
  }

  var wktOrScalar: OneOf_WktOrScalar? {
    get {return _storage._wktOrScalar}
    set {_uniqueStorage()._wktOrScalar = newValue}
  }

  var durVal: SwiftProtobuf.Google_Protobuf_Duration {
    get {
      if case .durVal(let v)? = _storage._wktOrScalar {return v}
      return SwiftProtobuf.Google_Protobuf_Duration()
    }
    set {_uniqueStorage()._wktOrScalar = .durVal(newValue)}
  }

  var intVal: Int32 {
    get {
      if case .intVal(let v)? = _storage._wktOrScalar {return v}
      return 0
    }
    set {_uniqueStorage()._wktOrScalar = .intVal(newValue)}
  }

  var structVal: SwiftProtobuf.Google_Protobuf_Struct {
    get {
      if case .structVal(let v)? = _storage._wktOrScalar {return v}
      return SwiftProtobuf.Google_Protobuf_Struct()
    }
    set {_uniqueStorage()._wktOrScalar = .structVal(newValue)}
  }

  var simple: Testcompat_SimpleMessage {
    get {return _storage._simple ?? Testcompat_SimpleMessage()}
    set {_uniqueStorage()._simple = newValue}
  }
  /// Returns true if `simple` has been explicitly set.
  var hasSimple: Bool {return _storage._simple != nil}
  /// Clears the value of `simple`. Subsequent reads from it will return its default value.
  mutating func clearSimple() {_uniqueStorage()._simple = nil}

  var detail: Testcompat_ScalarMessage {
    get {return _storage._detail ?? Testcompat_ScalarMessage()}
    set {_uniqueStorage()._detail = newValue}
  }
  /// Returns true if `detail` has been explicitly set.
  var hasDetail: Bool {return _storage._detail != nil}
  /// Clears the value of `detail`. Subsequent reads from it will return its default value.
  mutating func clearDetail() {_uniqueStorage()._detail = nil}

  var status: Testcompat_Status {
    get {return _storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  var unknownFields = SwiftProtobuf.UnknownStorage()

  enum OneOf_WktOrScalar: Equatable, Sendable {
    case durVal(SwiftProtobuf.Google_Protobuf_Duration)
    case intVal(Int32)
    case structVal(SwiftProtobuf.Google_Protobuf_Struct)

  }

  init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "testcompat"

extension Testcompat_WKTHolder: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WKTHolder"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ts\0\u{1}dur\0\u{1}mask\0\u{3}any_val\0\u{3}struct_val\0\u{3}value_val\0\u{3}list_val\0\u{3}dbl_w\0\u{3}flt_w\0\u{3}i64_w\0\u{3}u64_w\0\u{3}i32_w\0\u{3}u32_w\0\u{3}bool_w\0\u{3}str_w\0\u{3}bytes_w\0\u{3}empty_val\0")

  fileprivate class _StorageClass {
    var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _dur: SwiftProtobuf.Google_Protobuf_Duration? = nil
    var _mask: SwiftProtobuf.Google_Protobuf_FieldMask? = nil
    var _anyVal: SwiftProtobuf.Google_Protobuf_Any? = nil
    var _structVal: SwiftProtobuf.Google_Protobuf_Struct? = nil
    var _valueVal: SwiftProtobuf.Google_Protobuf_Value? = nil
    var _listVal: SwiftProtobuf.Google_Protobuf_ListValue? = nil
    var _dblW: SwiftProtobuf.Google_Protobuf_DoubleValue? = nil
    var _fltW: SwiftProtobuf.Google_Protobuf_FloatValue? = nil
    var _i64W: SwiftProtobuf.Google_Protobuf_Int64Value? = nil
    var _u64W: SwiftProtobuf.Google_Protobuf_UInt64Value? = nil
    var _i32W: SwiftProtobuf.Google_Protobuf_Int32Value? = nil
    var _u32W: SwiftProtobuf.Google_Protobuf_UInt32Value? = nil
    var _boolW: SwiftProtobuf.Google_Protobuf_BoolValue? = nil
    var _strW: SwiftProtobuf.Google_Protobuf_StringValue? = nil
    var _bytesW: SwiftProtobuf.Google_Protobuf_BytesValue? = nil
    var _emptyVal: SwiftProtobuf.Google_Protobuf_Empty? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _ts = source._ts
      _dur = source._dur
      _mask = source._mask
      _anyVal = source._anyVal
      _structVal = source._structVal
      _valueVal = source._valueVal
      _listVal = source._listVal
      _dblW = source._dblW
      _fltW = source._fltW
      _i64W = source._i64W
      _u64W = source._u64W
      _i32W = source._i32W
      _u32W = source._u32W
      _boolW = source._boolW
      _strW = source._strW
      _bytesW = source._bytesW
      _emptyVal = source._emptyVal
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._ts) }()
        case 2: try { try decoder.decodeSingularMessageField(value: &_storage._dur) }()
        case 3: try { try decoder.decodeSingularMessageField(value: &_storage._mask) }()
        case 4: try { try decoder.decodeSingularMessageField(value: &_storage._anyVal) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._structVal) }()
        case 6: try { try decoder.decodeSingularMessageField(value: &_storage._valueVal) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._listVal) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._dblW) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._fltW) }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._i64W) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._u64W) }()
        case 12: try { try decoder.decodeSingularMessageField(value: &_storage._i32W) }()
        case 13: try { try decoder.decodeSingularMessageField(value: &_storage._u32W) }()
        case 14: try { try decoder.decodeSingularMessageField(value: &_storage._boolW) }()
        case 15: try { try decoder.decodeSingularMessageField(value: &_storage._strW) }()
        case 16: try { try decoder.decodeSingularMessageField(value: &_storage._bytesW) }()
        case 17: try { try decoder.decodeSingularMessageField(value: &_storage._emptyVal) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._ts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      try { if let v = _storage._dur {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
      } }()
      try { if let v = _storage._mask {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
      } }()
      try { if let v = _storage._anyVal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      } }()
      try { if let v = _storage._structVal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      try { if let v = _storage._valueVal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      } }()
      try { if let v = _storage._listVal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._dblW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._fltW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
      try { if let v = _storage._i64W {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._u64W {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      try { if let v = _storage._i32W {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 12)
      } }()
      try { if let v = _storage._u32W {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 13)
      } }()
      try { if let v = _storage._boolW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 14)
      } }()
      try { if let v = _storage._strW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 15)
      } }()
      try { if let v = _storage._bytesW {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 16)
      } }()
      try { if let v = _storage._emptyVal {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 17)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WKTHolder, rhs: Testcompat_WKTHolder) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._ts != rhs_storage._ts {return false}
        if _storage._dur != rhs_storage._dur {return false}
        if _storage._mask != rhs_storage._mask {return false}
        if _storage._anyVal != rhs_storage._anyVal {return false}
        if _storage._structVal != rhs_storage._structVal {return false}
        if _storage._valueVal != rhs_storage._valueVal {return false}
        if _storage._listVal != rhs_storage._listVal {return false}
        if _storage._dblW != rhs_storage._dblW {return false}
        if _storage._fltW != rhs_storage._fltW {return false}
        if _storage._i64W != rhs_storage._i64W {return false}
        if _storage._u64W != rhs_storage._u64W {return false}
        if _storage._i32W != rhs_storage._i32W {return false}
        if _storage._u32W != rhs_storage._u32W {return false}
        if _storage._boolW != rhs_storage._boolW {return false}
        if _storage._strW != rhs_storage._strW {return false}
        if _storage._bytesW != rhs_storage._bytesW {return false}
        if _storage._emptyVal != rhs_storage._emptyVal {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_RepeatedWKTs: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".RepeatedWKTs"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}timestamps\0\u{1}durations\0\u{3}int64_vals\0\u{3}string_vals\0\u{3}bool_vals\0\u{1}structs\0\u{1}values\0\u{1}anys\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeRepeatedMessageField(value: &self.timestamps) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.durations) }()
      case 3: try { try decoder.decodeRepeatedMessageField(value: &self.int64Vals) }()
      case 4: try { try decoder.decodeRepeatedMessageField(value: &self.stringVals) }()
      case 5: try { try decoder.decodeRepeatedMessageField(value: &self.boolVals) }()
      case 6: try { try decoder.decodeRepeatedMessageField(value: &self.structs) }()
      case 7: try { try decoder.decodeRepeatedMessageField(value: &self.values) }()
      case 8: try { try decoder.decodeRepeatedMessageField(value: &self.anys) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.timestamps.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.timestamps, fieldNumber: 1)
    }
    if !self.durations.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.durations, fieldNumber: 2)
    }
    if !self.int64Vals.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.int64Vals, fieldNumber: 3)
    }
    if !self.stringVals.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.stringVals, fieldNumber: 4)
    }
    if !self.boolVals.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.boolVals, fieldNumber: 5)
    }
    if !self.structs.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.structs, fieldNumber: 6)
    }
    if !self.values.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.values, fieldNumber: 7)
    }
    if !self.anys.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.anys, fieldNumber: 8)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_RepeatedWKTs, rhs: Testcompat_RepeatedWKTs) -> Bool {
    if lhs.timestamps != rhs.timestamps {return false}
    if lhs.durations != rhs.durations {return false}
    if lhs.int64Vals != rhs.int64Vals {return false}
    if lhs.stringVals != rhs.stringVals {return false}
    if lhs.boolVals != rhs.boolVals {return false}
    if lhs.structs != rhs.structs {return false}
    if lhs.values != rhs.values {return false}
    if lhs.anys != rhs.anys {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_MapWKTValues: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".MapWKTValues"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}ts_map\0\u{3}i64w_map\0\u{3}strw_map\0\u{3}struct_map\0\u{3}any_map\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Timestamp>.self, value: &self.tsMap) }()
      case 2: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Int64Value>.self, value: &self.i64WMap) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_StringValue>.self, value: &self.strwMap) }()
      case 4: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Struct>.self, value: &self.structMap) }()
      case 5: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Any>.self, value: &self.anyMap) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.tsMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Timestamp>.self, value: self.tsMap, fieldNumber: 1)
    }
    if !self.i64WMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Int64Value>.self, value: self.i64WMap, fieldNumber: 2)
    }
    if !self.strwMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_StringValue>.self, value: self.strwMap, fieldNumber: 3)
    }
    if !self.structMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Struct>.self, value: self.structMap, fieldNumber: 4)
    }
    if !self.anyMap.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Any>.self, value: self.anyMap, fieldNumber: 5)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_MapWKTValues, rhs: Testcompat_MapWKTValues) -> Bool {
    if lhs.tsMap != rhs.tsMap {return false}
    if lhs.i64WMap != rhs.i64WMap {return false}
    if lhs.strwMap != rhs.strwMap {return false}
    if lhs.structMap != rhs.structMap {return false}
    if lhs.anyMap != rhs.anyMap {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WKTNested: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WKTNested"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}primary\0\u{1}history\0\u{1}named\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._primary) }()
      case 2: try { try decoder.decodeRepeatedMessageField(value: &self.history) }()
      case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_WKTNested.Inner>.self, value: &self.named) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._primary {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    if !self.history.isEmpty {
      try visitor.visitRepeatedMessageField(value: self.history, fieldNumber: 2)
    }
    if !self.named.isEmpty {
      try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,Testcompat_WKTNested.Inner>.self, value: self.named, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WKTNested, rhs: Testcompat_WKTNested) -> Bool {
    if lhs._primary != rhs._primary {return false}
    if lhs.history != rhs.history {return false}
    if lhs.named != rhs.named {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WKTNested.Inner: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = Testcompat_WKTNested.protoMessageName + ".Inner"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}created\0\u{1}ttl\0\u{1}count\0")

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularMessageField(value: &self._created) }()
      case 2: try { try decoder.decodeSingularMessageField(value: &self._ttl) }()
      case 3: try { try decoder.decodeSingularMessageField(value: &self._count) }()
      default: break
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    try { if let v = self._created {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
    } }()
    try { if let v = self._ttl {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 2)
    } }()
    try { if let v = self._count {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 3)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WKTNested.Inner, rhs: Testcompat_WKTNested.Inner) -> Bool {
    if lhs._created != rhs._created {return false}
    if lhs._ttl != rhs._ttl {return false}
    if lhs._count != rhs._count {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Testcompat_WKTMixed: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  static let protoMessageName: String = _protobuf_package + ".WKTMixed"
  static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}ts\0\u{1}labels\0\u{1}counters\0\u{3}dur_val\0\u{3}int_val\0\u{3}struct_val\0\u{2}\u{4}simple\0\u{1}detail\0\u{1}status\0")

  fileprivate class _StorageClass {
    var _ts: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _labels: [SwiftProtobuf.Google_Protobuf_StringValue] = []
    var _counters: Dictionary<String,SwiftProtobuf.Google_Protobuf_Int64Value> = [:]
    var _wktOrScalar: Testcompat_WKTMixed.OneOf_WktOrScalar?
    var _simple: Testcompat_SimpleMessage? = nil
    var _detail: Testcompat_ScalarMessage? = nil
    var _status: Testcompat_Status = .unspecified

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _ts = source._ts
      _labels = source._labels
      _counters = source._counters
      _wktOrScalar = source._wktOrScalar
      _simple = source._simple
      _detail = source._detail
      _status = source._status
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._ts) }()
        case 2: try { try decoder.decodeRepeatedMessageField(value: &_storage._labels) }()
        case 3: try { try decoder.decodeMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Int64Value>.self, value: &_storage._counters) }()
        case 4: try {
          var v: SwiftProtobuf.Google_Protobuf_Duration?
          var hadOneofValue = false
          if let current = _storage._wktOrScalar {
            hadOneofValue = true
            if case .durVal(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._wktOrScalar = .durVal(v)
          }
        }()
        case 5: try {
          var v: Int32?
          try decoder.decodeSingularInt32Field(value: &v)
          if let v = v {
            if _storage._wktOrScalar != nil {try decoder.handleConflictingOneOf()}
            _storage._wktOrScalar = .intVal(v)
          }
        }()
        case 6: try {
          var v: SwiftProtobuf.Google_Protobuf_Struct?
          var hadOneofValue = false
          if let current = _storage._wktOrScalar {
            hadOneofValue = true
            if case .structVal(let m) = current {v = m}
          }
          try decoder.decodeSingularMessageField(value: &v)
          if let v = v {
            if hadOneofValue {try decoder.handleConflictingOneOf()}
            _storage._wktOrScalar = .structVal(v)
          }
        }()
        case 10: try { try decoder.decodeSingularMessageField(value: &_storage._simple) }()
        case 11: try { try decoder.decodeSingularMessageField(value: &_storage._detail) }()
        case 12: try { try decoder.decodeSingularEnumField(value: &_storage._status) }()
        default: break
        }
      }
    }
  }

  func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._ts {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._labels.isEmpty {
        try visitor.visitRepeatedMessageField(value: _storage._labels, fieldNumber: 2)
      }
      if !_storage._counters.isEmpty {
        try visitor.visitMapField(fieldType: SwiftProtobuf._ProtobufMessageMap<SwiftProtobuf.ProtobufString,SwiftProtobuf.Google_Protobuf_Int64Value>.self, value: _storage._counters, fieldNumber: 3)
      }
      switch _storage._wktOrScalar {
      case .durVal?: try {
        guard case .durVal(let v)? = _storage._wktOrScalar else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
      }()
      case .intVal?: try {
        guard case .intVal(let v)? = _storage._wktOrScalar else { preconditionFailure() }
        try visitor.visitSingularInt32Field(value: v, fieldNumber: 5)
      }()
      case .structVal?: try {
        guard case .structVal(let v)? = _storage._wktOrScalar else { preconditionFailure() }
        try visitor.visitSingularMessageField(value: v, fieldNumber: 6)
      }()
      case nil: break
      }
      try { if let v = _storage._simple {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 10)
      } }()
      try { if let v = _storage._detail {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 11)
      } }()
      if _storage._status != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 12)
      }
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  static func ==(lhs: Testcompat_WKTMixed, rhs: Testcompat_WKTMixed) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._ts != rhs_storage._ts {return false}
        if _storage._labels != rhs_storage._labels {return false}
        if _storage._counters != rhs_storage._counters {return false}
        if _storage._wktOrScalar != rhs_storage._wktOrScalar {return false}
        if _storage._simple != rhs_storage._simple {return false}
        if _storage._detail != rhs_storage._detail {return false}
        if _storage._status != rhs_storage._status {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
