//
// Bridge.swift (public API)
// SwiftProtoReflect
//
// Public surface for converting between static SwiftProtobuf messages and dynamic messages,
// and between SwiftProtobuf descriptors and SwiftProtoReflect descriptors.
// Internal implementations live in Bridge/_DescriptorBridge.swift
// and Bridge/_StaticMessageBridge.swift.
//

import Foundation
import SwiftProtobuf

// MARK: - DescriptorBridgeError

/// Errors that occur during descriptor conversion between SwiftProtobuf and SwiftProtoReflect.
public enum DescriptorBridgeError: Error, LocalizedError {
  case unsupportedFieldType(Int)
  case conversionFailed(String)
  case missingRequiredField(String)
  case invalidDescriptorStructure(String)

  public var errorDescription: String? {
    switch self {
    case .unsupportedFieldType(let value):
      return "Unsupported field type: \(value)"
    case .conversionFailed(let details):
      return "Conversion error: \(details)"
    case .missingRequiredField(let fieldName):
      return "Missing required field: \(fieldName)"
    case .invalidDescriptorStructure(let details):
      return "Invalid descriptor structure: \(details)"
    }
  }
}

extension DescriptorBridgeError {
  init(from impl: _DescriptorBridgeError) {
    switch impl {
    case .unsupportedFieldType(let v): self = .unsupportedFieldType(v)
    case .conversionFailed(let d): self = .conversionFailed(d)
    case .missingRequiredField(let f): self = .missingRequiredField(f)
    case .invalidDescriptorStructure(let d): self = .invalidDescriptorStructure(d)
    }
  }
}

// MARK: - DescriptorBridge

/// Converts between SwiftProtobuf descriptor types and SwiftProtoReflect descriptor types.
///
/// Provides bidirectional conversion between `Google_Protobuf_DescriptorProto` and
/// `MessageDescriptor`, enabling interoperability with code generated by protoc.
public struct DescriptorBridge {

  private let impl: _DescriptorBridge

  // MARK: - Initialization

  /// Creates a new DescriptorBridge instance.
  public init() {
    self.impl = _DescriptorBridge()
  }

  // MARK: - Message Descriptor Conversion

  /// Converts a SwiftProtoReflect `MessageDescriptor` to a `Google_Protobuf_DescriptorProto`.
  ///
  /// - Parameter messageDescriptor: The descriptor to convert.
  /// - Returns: The equivalent SwiftProtobuf descriptor proto.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func toProtobufDescriptor(
    from messageDescriptor: MessageDescriptor
  ) throws -> Google_Protobuf_DescriptorProto {
    do {
      return try impl.toSwiftProtobuf(from: _MessageDescriptor(from: messageDescriptor))
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  /// Converts a `Google_Protobuf_DescriptorProto` to a SwiftProtoReflect `MessageDescriptor`.
  ///
  /// - Parameters:
  ///   - protobufDescriptor: The SwiftProtobuf descriptor proto to convert.
  ///   - parent: Optional parent descriptor. Defaults to `nil`.
  /// - Returns: The equivalent SwiftProtoReflect descriptor.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func fromProtobufDescriptor(
    _ protobufDescriptor: Google_Protobuf_DescriptorProto,
    parent: (any DescriptorParent)? = nil
  ) throws -> MessageDescriptor {
    do {
      let internalParent: (any _DescriptorParent)? = parent.flatMap { p in
        if let msg = p as? MessageDescriptor { return _MessageDescriptor(from: msg) }
        if let file = p as? FileDescriptor { return _FileDescriptor(from: file) }
        return nil
      }
      let result = try impl.fromProtobufDescriptor(protobufDescriptor, parent: internalParent)
      return MessageDescriptor(from: result)
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  // MARK: - Field Descriptor Conversion

  /// Converts a SwiftProtoReflect `FieldDescriptor` to a `Google_Protobuf_FieldDescriptorProto`.
  ///
  /// - Parameter fieldDescriptor: The field descriptor to convert.
  /// - Returns: The equivalent SwiftProtobuf field descriptor proto.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func toProtobufFieldDescriptor(
    from fieldDescriptor: FieldDescriptor
  ) throws -> Google_Protobuf_FieldDescriptorProto {
    do {
      return try impl.toProtobufFieldDescriptor(from: _FieldDescriptor(from: fieldDescriptor))
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  /// Converts a `Google_Protobuf_FieldDescriptorProto` to a SwiftProtoReflect `FieldDescriptor`.
  ///
  /// - Parameters:
  ///   - protobufDescriptor: The SwiftProtobuf field descriptor proto to convert.
  ///   - syntax: Proto syntax version. Defaults to `"proto3"`.
  /// - Returns: The equivalent SwiftProtoReflect field descriptor.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func fromProtobufFieldDescriptor(
    _ protobufDescriptor: Google_Protobuf_FieldDescriptorProto,
    syntax: String = "proto3"
  ) throws -> FieldDescriptor {
    do {
      let result = try impl.fromProtobufFieldDescriptor(protobufDescriptor, syntax: syntax)
      return FieldDescriptor(from: result)
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  // MARK: - Enum Descriptor Conversion

  /// Converts a SwiftProtoReflect `EnumDescriptor` to a `Google_Protobuf_EnumDescriptorProto`.
  ///
  /// - Parameter enumDescriptor: The enum descriptor to convert.
  /// - Returns: The equivalent SwiftProtobuf enum descriptor proto.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func toProtobufEnumDescriptor(
    from enumDescriptor: EnumDescriptor
  ) throws -> Google_Protobuf_EnumDescriptorProto {
    do {
      return try impl.toProtobufEnumDescriptor(from: _EnumDescriptor(from: enumDescriptor))
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  /// Converts a `Google_Protobuf_EnumDescriptorProto` to a SwiftProtoReflect `EnumDescriptor`.
  ///
  /// - Parameters:
  ///   - protobufDescriptor: The SwiftProtobuf enum descriptor proto to convert.
  ///   - parent: Optional parent descriptor. Defaults to `nil`.
  /// - Returns: The equivalent SwiftProtoReflect enum descriptor.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func fromProtobufEnumDescriptor(
    _ protobufDescriptor: Google_Protobuf_EnumDescriptorProto,
    parent: (any DescriptorParent)? = nil
  ) throws -> EnumDescriptor {
    do {
      let internalParent: (any _DescriptorParent)? = parent.flatMap { p in
        if let msg = p as? MessageDescriptor { return _MessageDescriptor(from: msg) }
        if let file = p as? FileDescriptor { return _FileDescriptor(from: file) }
        return nil
      }
      let result = try impl.fromProtobufEnumDescriptor(protobufDescriptor, parent: internalParent)
      return EnumDescriptor(from: result)
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  // MARK: - File Descriptor Conversion

  /// Converts a SwiftProtoReflect `FileDescriptor` to a `Google_Protobuf_FileDescriptorProto`.
  ///
  /// - Parameter fileDescriptor: The file descriptor to convert.
  /// - Returns: The equivalent SwiftProtobuf file descriptor proto.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func toProtobufFileDescriptor(
    from fileDescriptor: FileDescriptor
  ) throws -> Google_Protobuf_FileDescriptorProto {
    do {
      return try impl.toProtobufFileDescriptor(from: _FileDescriptor(from: fileDescriptor))
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  /// Converts a `Google_Protobuf_FileDescriptorProto` to a SwiftProtoReflect `FileDescriptor`.
  ///
  /// - Parameter protobufDescriptor: The SwiftProtobuf file descriptor proto to convert.
  /// - Returns: The equivalent SwiftProtoReflect file descriptor.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func fromProtobufFileDescriptor(
    _ protobufDescriptor: Google_Protobuf_FileDescriptorProto
  ) throws -> FileDescriptor {
    do {
      let result = try impl.fromProtobufFileDescriptor(protobufDescriptor)
      return FileDescriptor(from: result)
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  // MARK: - Service Descriptor Conversion

  /// Converts a SwiftProtoReflect `ServiceDescriptor` to a `Google_Protobuf_ServiceDescriptorProto`.
  ///
  /// - Parameter serviceDescriptor: The service descriptor to convert.
  /// - Returns: The equivalent SwiftProtobuf service descriptor proto.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func toProtobufServiceDescriptor(
    from serviceDescriptor: ServiceDescriptor
  ) throws -> Google_Protobuf_ServiceDescriptorProto {
    do {
      return try impl.toProtobufServiceDescriptor(from: _ServiceDescriptor(from: serviceDescriptor))
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }

  /// Converts a `Google_Protobuf_ServiceDescriptorProto` to a SwiftProtoReflect `ServiceDescriptor`.
  ///
  /// - Parameters:
  ///   - protobufDescriptor: The SwiftProtobuf service descriptor proto to convert.
  ///   - parent: Optional parent file descriptor. Defaults to `nil`.
  /// - Returns: The equivalent SwiftProtoReflect service descriptor.
  /// - Throws: `DescriptorBridgeError` if conversion fails.
  public func fromProtobufServiceDescriptor(
    _ protobufDescriptor: Google_Protobuf_ServiceDescriptorProto,
    parent: FileDescriptor? = nil
  ) throws -> ServiceDescriptor {
    do {
      let internalParent = parent.map { _FileDescriptor(from: $0) }
      let result = try impl.fromProtobufServiceDescriptor(protobufDescriptor, parent: internalParent)
      return ServiceDescriptor(from: result)
    }
    catch let e as _DescriptorBridgeError {
      throw DescriptorBridgeError(from: e)
    }
  }
}

// MARK: - StaticMessageBridgeError

/// Errors that occur during static↔dynamic message conversion.
public enum StaticMessageBridgeError: Error, LocalizedError {
  case incompatibleTypes(staticType: String, descriptorType: String)
  case serializationFailed(underlying: Error)
  case deserializationFailed(underlying: Error)
  case descriptorCreationFailed(messageType: String)
  case unsupportedMessageType(String)

  public var errorDescription: String? {
    switch self {
    case .incompatibleTypes(let staticType, let descriptorType):
      return "Incompatible types: static type '\(staticType)' does not match descriptor '\(descriptorType)'"
    case .serializationFailed(let underlying):
      return "Serialization error: \(underlying.localizedDescription)"
    case .deserializationFailed(let underlying):
      return "Deserialization error: \(underlying.localizedDescription)"
    case .descriptorCreationFailed(let messageType):
      return "Failed to create descriptor for message type '\(messageType)'"
    case .unsupportedMessageType(let messageType):
      return "Unsupported message type: '\(messageType)'"
    }
  }
}

extension StaticMessageBridgeError {
  init(from impl: _StaticMessageBridgeError) {
    switch impl {
    case .incompatibleTypes(let s, let d): self = .incompatibleTypes(staticType: s, descriptorType: d)
    case .serializationFailed(let e): self = .serializationFailed(underlying: e)
    case .deserializationFailed(let e): self = .deserializationFailed(underlying: e)
    case .descriptorCreationFailed(let m): self = .descriptorCreationFailed(messageType: m)
    case .unsupportedMessageType(let m): self = .unsupportedMessageType(m)
    }
  }
}

// MARK: - StaticMessageBridge

/// Converts between static SwiftProtobuf messages and dynamic SwiftProtoReflect messages.
///
/// Provides bidirectional conversion between statically-typed `SwiftProtobuf.Message`
/// instances and `DynamicMessage`, enabling interoperability between code-generated
/// and runtime-built message representations.
public struct StaticMessageBridge {

  private let impl: _StaticMessageBridge

  // MARK: - Initialization

  /// Creates a new StaticMessageBridge instance.
  public init() {
    self.impl = _StaticMessageBridge()
  }

  // MARK: - Static to Dynamic Conversion

  /// Converts a static SwiftProtobuf message to a dynamic message using a descriptor.
  ///
  /// - Parameters:
  ///   - staticMessage: The static SwiftProtobuf message to convert.
  ///   - descriptor: The descriptor to use for the resulting dynamic message.
  /// - Returns: A dynamic message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toDynamicMessage<T: SwiftProtobuf.Message>(
    from staticMessage: T,
    using descriptor: MessageDescriptor
  ) throws -> DynamicMessage {
    do {
      let result = try impl.toDynamicMessage(
        from: staticMessage,
        using: _MessageDescriptor(from: descriptor)
      )
      return DynamicMessage(from: result)
    }
    catch let e as _StaticMessageBridgeError {
      throw StaticMessageBridgeError(from: e)
    }
  }

  /// Converts a static SwiftProtobuf message to a dynamic message.
  ///
  /// Generates a descriptor automatically from the message's structure.
  ///
  /// - Parameter staticMessage: The static SwiftProtobuf message to convert.
  /// - Returns: A dynamic message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toDynamicMessage<T: SwiftProtobuf.Message>(
    from staticMessage: T
  ) throws -> DynamicMessage {
    do {
      let result = try impl.toDynamicMessage(from: staticMessage)
      return DynamicMessage(from: result)
    }
    catch let e as _StaticMessageBridgeError {
      throw StaticMessageBridgeError(from: e)
    }
  }

  // MARK: - Dynamic to Static Conversion

  /// Converts a dynamic message to a static SwiftProtobuf message.
  ///
  /// - Parameters:
  ///   - dynamicMessage: The dynamic message to convert.
  ///   - messageType: The target static message type.
  /// - Returns: A static message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toStaticMessage<T: SwiftProtobuf.Message>(
    from dynamicMessage: DynamicMessage,
    as messageType: T.Type
  ) throws -> T {
    do {
      return try impl.toStaticMessage(from: _DynamicMessage(from: dynamicMessage), as: messageType)
    }
    catch let e as _StaticMessageBridgeError {
      throw StaticMessageBridgeError(from: e)
    }
  }

  // MARK: - Batch Conversions

  /// Converts multiple static SwiftProtobuf messages to dynamic messages using a descriptor.
  ///
  /// - Parameters:
  ///   - staticMessages: The static messages to convert.
  ///   - descriptor: The descriptor to use for the resulting dynamic messages.
  /// - Returns: An array of dynamic messages.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toDynamicMessages<T: SwiftProtobuf.Message>(
    from staticMessages: [T],
    using descriptor: MessageDescriptor
  ) throws -> [DynamicMessage] {
    do {
      let internalDescriptor = _MessageDescriptor(from: descriptor)
      return try impl.toDynamicMessages(from: staticMessages, using: internalDescriptor)
        .map { DynamicMessage(from: $0) }
    }
    catch let e as _StaticMessageBridgeError {
      throw StaticMessageBridgeError(from: e)
    }
  }

  /// Converts multiple dynamic messages to static SwiftProtobuf messages.
  ///
  /// - Parameters:
  ///   - dynamicMessages: The dynamic messages to convert.
  ///   - messageType: The target static message type.
  /// - Returns: An array of static messages.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toStaticMessages<T: SwiftProtobuf.Message>(
    from dynamicMessages: [DynamicMessage],
    as messageType: T.Type
  ) throws -> [T] {
    do {
      return try impl.toStaticMessages(
        from: dynamicMessages.map { _DynamicMessage(from: $0) },
        as: messageType
      )
    }
    catch let e as _StaticMessageBridgeError {
      throw StaticMessageBridgeError(from: e)
    }
  }

  // MARK: - Compatibility Checks

  /// Returns whether a static message is structurally compatible with a descriptor.
  ///
  /// - Parameters:
  ///   - staticMessage: The static SwiftProtobuf message to check.
  ///   - descriptor: The descriptor to check compatibility against.
  /// - Returns: `true` if the message can be deserialized using the descriptor.
  public func isCompatible<T: SwiftProtobuf.Message>(
    staticMessage: T,
    with descriptor: MessageDescriptor
  ) -> Bool {
    return impl.isCompatible(staticMessage: staticMessage, with: _MessageDescriptor(from: descriptor))
  }

  /// Returns whether a dynamic message is structurally compatible with a static message type.
  ///
  /// - Parameters:
  ///   - dynamicMessage: The dynamic message to check.
  ///   - messageType: The target static message type to check compatibility against.
  /// - Returns: `true` if the dynamic message can be deserialized as the static type.
  public func isCompatible<T: SwiftProtobuf.Message>(
    dynamicMessage: DynamicMessage,
    with messageType: T.Type
  ) -> Bool {
    return impl.isCompatible(
      dynamicMessage: _DynamicMessage(from: dynamicMessage),
      with: messageType
    )
  }
}

// MARK: - DynamicMessage Convenience Extensions

extension DynamicMessage {

  /// Converts this dynamic message to a static SwiftProtobuf message.
  ///
  /// - Parameter messageType: The target static message type.
  /// - Returns: A static message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toStaticMessage<T: SwiftProtobuf.Message>(as messageType: T.Type) throws -> T {
    return try StaticMessageBridge().toStaticMessage(from: self, as: messageType)
  }
}

// MARK: - SwiftProtobuf.Message Convenience Extensions

extension SwiftProtobuf.Message {

  /// Converts this static message to a dynamic message using a descriptor.
  ///
  /// - Parameter descriptor: The descriptor to use for the resulting dynamic message.
  /// - Returns: A dynamic message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toDynamicMessage(using descriptor: MessageDescriptor) throws -> DynamicMessage {
    return try StaticMessageBridge().toDynamicMessage(from: self, using: descriptor)
  }

  /// Converts this static message to a dynamic message, generating a descriptor automatically.
  ///
  /// - Returns: A dynamic message containing the same field values.
  /// - Throws: `StaticMessageBridgeError` if conversion fails.
  public func toDynamicMessage() throws -> DynamicMessage {
    return try StaticMessageBridge().toDynamicMessage(from: self)
  }
}
