//
// GoogleConformanceTests.swift
// SwiftProtoReflect
//
// Tests validating conformance with the official Google Protocol Buffers specification.
// These tests verify our dynamic message handling against known-good binary payloads
// that match the canonical protobuf encoding.
//

import Foundation
import XCTest

@testable import SwiftProtoReflect

final class GoogleConformanceTests: XCTestCase {

  // MARK: - Canonical varint encoding

  func test_canonicalVarint_int32FieldOne() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "a", number: 1, type: .int32))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(Int32(150), forField: "a")

    let data = try BinarySerializer().serialize(msg)
    XCTAssertEqual(data, Data([0x08, 0x96, 0x01]), "Must match protoc output for int32 field=1 value=150")
  }

  // MARK: - Default values not on wire (proto3)

  func test_defaultValuesNotOnWire() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "id", number: 1, type: .int32))
    desc.addField(FieldDescriptor(name: "name", number: 2, type: .string))

    let msg = MessageFactory().createMessage(from: desc)
    let data = try BinarySerializer().serialize(msg)
    XCTAssertTrue(data.isEmpty, "Proto3 message with all defaults should serialize to zero bytes")
  }

  // MARK: - String field encoding

  func test_stringField_helloWorld() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "val", number: 2, type: .string))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set("testing", forField: "val")

    let data = try BinarySerializer().serialize(msg)
    // field 2, wire type 2 → tag = (2 << 3) | 2 = 0x12
    // length 7 → 0x07
    // "testing" → [0x74, 0x65, 0x73, 0x74, 0x69, 0x6E, 0x67]
    let expected = Data([0x12, 0x07, 0x74, 0x65, 0x73, 0x74, 0x69, 0x6E, 0x67])
    XCTAssertEqual(data, expected, "Must match protoc-generated bytes for string 'testing'")
  }

  // MARK: - Bool field encoding

  func test_boolField_true() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "flag", number: 1, type: .bool))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(true, forField: "flag")

    let data = try BinarySerializer().serialize(msg)
    XCTAssertEqual(data, Data([0x08, 0x01]))
  }

  func test_boolField_false_notSerialized() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "flag", number: 1, type: .bool))

    let msg = MessageFactory().createMessage(from: desc)
    let data = try BinarySerializer().serialize(msg)
    XCTAssertTrue(data.isEmpty, "Proto3 bool with default false should not be on wire")
  }

  // MARK: - Negative int32 uses 10-byte varint

  func test_negativeInt32_tenByteVarint() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "val", number: 1, type: .int32))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(Int32(-1), forField: "val")

    let data = try BinarySerializer().serialize(msg)
    // tag 0x08 + 10 bytes for -1 as sign-extended uint64
    XCTAssertEqual(data.count, 11, "Negative int32 must be 10-byte varint on wire (per spec)")
  }

  // MARK: - JSON conformance

  func test_jsonInt64AsString() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "big", number: 1, type: .int64))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(Int64.max, forField: "big")

    let json = try await JSONSerializer(options: .init(typeRegistry: TypeRegistry())).serializeToJSONObject(msg)
    XCTAssertTrue(json["big"] is String, "int64 must be a JSON string per proto3 spec")
  }

  func test_jsonUint64AsString() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "big", number: 1, type: .uint64))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(UInt64.max, forField: "big")

    let json = try await JSONSerializer(options: .init(typeRegistry: TypeRegistry())).serializeToJSONObject(msg)
    XCTAssertTrue(json["big"] is String, "uint64 must be a JSON string per proto3 spec")
  }

  func test_jsonBytesAsBase64() async throws {
    var desc = MessageDescriptor(name: "M", fullName: "conformance.M")
    desc.addField(FieldDescriptor(name: "payload", number: 1, type: .bytes))

    var msg = MessageFactory().createMessage(from: desc)
    try msg.set(Data([0x00, 0x01, 0x02, 0xFF]), forField: "payload")

    let json = try await JSONSerializer(options: .init(typeRegistry: TypeRegistry())).serializeToJSONObject(msg)
    let b64 = json["payload"] as? String
    XCTAssertNotNil(b64)
    XCTAssertEqual(Data(base64Encoded: b64!)!, Data([0x00, 0x01, 0x02, 0xFF]))
  }
}
