name: Swift Test

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]

jobs:
  test:
    runs-on: macos-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up Swift
        uses: swift-actions/setup-swift@v2
        with:
          swift-version: '6.0'

      - name: Build and test with coverage
        run: make test
